#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
${symbol_pound}${symbol_pound} Maven properties
maven.name=${symbol_dollar}{project.name}
maven.version=${symbol_dollar}{project.version}
maven.build.date=${symbol_dollar}{buildTimestamp}
