#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
application.name = ${artifactIdUpper}
properties.whitelist.0 = mc${symbol_escape}${symbol_escape}.gouv${symbol_escape}${symbol_escape}.appfactory${symbol_escape}${symbol_escape}.front${symbol_escape}${symbol_escape}.login${symbol_escape}${symbol_escape}..*
properties.whitelist.1 = mc${symbol_escape}${symbol_escape}.gouv${symbol_escape}${symbol_escape}.appfactory${symbol_escape}${symbol_escape}.${artifactIdLower}${symbol_escape}${symbol_escape}.front${symbol_escape}${symbol_escape}..*
properties.whitelist.2 = mc${symbol_escape}${symbol_escape}.gouv${symbol_escape}${symbol_escape}.piwik${symbol_escape}${symbol_escape}.external${symbol_escape}${symbol_escape}..*
properties.required.0 = mc.gouv.appfactory.front.login.keepalive.url
properties.required.1 = mc.gouv.appfactory.front.login.url
properties.required.2 = mc.gouv.appfactory.front.login.profil.url
properties.required.3 = mc.gouv.appfactory.${artifactIdLower}.front.copyright.years
properties.required.4 = mc.gouv.piwik.external.piwikUrl
properties.required.5 = mc.gouv.piwik.external.${artifactIdUpper}.piwikSiteId
properties.required.6 = mc.gouv.appfactory.${artifactIdLower}.front.login.contact.url
properties.required.7 = mc.gouv.appfactory.${artifactIdLower}.front.quitterTsUrl.fr
properties.required.8 = mc.gouv.appfactory.${artifactIdLower}.front.ficheDemarcheUrl.fr
properties.required.9 = mc.gouv.appfactory.${artifactIdLower}.front.sondageUrl.fr
properties.required.10 = mc.gouv.appfactory.${artifactIdLower}.front.sondageAbandonUrl.fr
properties.required.11 = mc.gouv.appfactory.${artifactIdLower}.front.joDemarcheUrl.fr
properties.required.12 = mc.gouv.appfactory.${artifactIdLower}.front.joCcinUrl.fr
properties.required.13 = mc.gouv.appfactory.${artifactIdLower}.front.cgu.url.fr
pages.post.login.file = /acces_teleservice.html
pages.login.home.file = /home.xhtml
pages.extension = .html
pages.error.file = /erreur.html
pages.expired.file = /expire.html
pages.download.url = /filedownload/