-- #12285 - Garder une trace du Prénom, Nom et Email de l'usager qui a fait la demande
ALTER TABLE ${artifactIdUpper}.DEM_DEMANDES ADD COLUMN USAGER_NOM CHARACTER VARYING(256);
ALTER TABLE ${artifactIdUpper}.DEM_DEMANDES ADD COLUMN USAGER_PRENOM CHARACTER VARYING(256);
ALTER TABLE ${artifactIdUpper}.DEM_DEMANDES ADD COLUMN USAGER_EMAIL CHARACTER VARYING(256);
