# Ne pas modifier ni renommer ce fichier, il est utilise pour transmettre des proprietes en provenance du build maven
# Lors du lancement d'un module applicatif sur les serveurs, il est importe avec la commande:
# --spring.config.location=classpath:/build.infos.properties
# Maven properties
maven.name=@project.name@
maven.version=@project.version@
maven.build.date=@buildDate@
xaf.version=@xaf.version@