server.servlet.context-path=/${application.name}

# Postgres
spring.sql.init.mode=never
spring.sql.init.platform=postgres
spring.jpa.database-platform=mc.gouv.xaf.back.config.CustomPostgreSQLDialect

# BPMN
spring.activiti.processDefinitionLocationPrefix=classpath*:/processes/
flowable.database-schema-update=none

# Gouv
mc.gouv.appli.shared.backapi.back.url=http://localhost:${back.port}${server.servlet.context-path}
mc.gouv.appli.shared.backapi.front.url=http://localhost:${front.port}${front.context}
mc.gouv.shared.backapi.rest.pagesize=250

# Usercache
mc.gouv.backapi.usagerscache.duration=60000
# Spring Global
spring.messages.basename=messages/messages
spring.jpa.open-in-view=false

# Database
mc.gouv.database.class=org.postgresql.Driver

mc.gouv.appli.shared.backapi.database.url=jdbc:postgresql://localhost:5432${server.servlet.context-path}
mc.gouv.appli.shared.backapi.database.user=${application.name}
mc.gouv.appli.shared.backapi.database.pass=${application.name}

# File
mc.gouv.appli.shared.backapi.file.containerId=ROOT

# Kafka
logging.level.org.apache.kafka=OFF
mc.gouv.appli.shared.backapi.kafka.enabled=true
mc.gouv.busmsg.kafka.server.name=localhost:9092
mc.gouv.appli.shared.backapi.kafka.ssl.enabled=false
mc.gouv.appli.shared.backapi.kafka.ssl.truststore.location=
mc.gouv.appli.shared.backapi.kafka.ssl.truststore.password=
mc.gouv.appli.shared.backapi.kafka.ssl.keystore.location=
mc.gouv.appli.shared.backapi.kafka.ssl.keystore.password=

# Logon
mc.gouv.logon.url=http://localhost:9081/logon
mc.gouv.logon.api.url=http://linuxas-dev.monaco-gouvernement.mc/logon/rest

# Quartz
spring.quartz.job-store-type=jdbc
spring.quartz.jdbc.initialize-schema=never
spring.quartz.properties.org.quartz.jobStore.dataSource=dataSource
spring.quartz.properties.org.quartz.jobStore.class=org.springframework.scheduling.quartz.LocalDataSourceJobStore
spring.quartz.properties.org.quartz.jobStore.isClustered=true
spring.quartz.properties.org.quartz.jobStore.driverDelegateClass = org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
spring.quartz.properties.org.quartz.scheduler.instanceId=AUTO

# Nomen
mc.gouv.payscache.duration=86400000

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db
spring.flyway.schemas=${application.name}
spring.flyway.placeholderPrefix=@@
spring.flyway.placeholderSuffix=@@

#Ulis
mc.gouv.appli.shared.backapi.ulis.authentication.user=${APPLI_SHARED_ULIS_AUTH_USER:}
mc.gouv.appli.shared.backapi.ulis.account=${APPLI_SHARED_ULIS_ACCOUNT:}
mc.gouv.appli.shared.backapi.ulis.authentication.password=${APPLI_SHARED_ULIS_PASSWORD:}

# File
mc.gouv.appli.shared.backapi.file.jwt=${APPLI_SHARED_FILE_JWT}

# Mail
mc.gouv.appli.shared.backapi.mail.jwt=${APPLI_SHARED_MAIL_JWT}

# Vscan
mc.gouv.appli.shared.backapi.vscan.jwt=${APPLI_SHARED_VSCAN_JWT}

# SMS
mc.gouv.appli.shared.backapi.sms.enabled=false
mc.gouv.appli.shared.backapi.sms.jwt=${APPLI_SHARED_SMS_JWT}

# Nomen
mc.gouv.shared.backapi.nomen.jwt=${APPLI_SHARED_NOMEN_JWT}

# GED everteam - Ulis
mc.gouv.appli.shared.backapi.gedeverteam.ulis.user=${APPLI_SHARED_GED_EVERTEAM_USER:}
mc.gouv.appli.shared.backapi.gedeverteam.ulis.token=${APPLI_SHARED_GED_EVERTEAM_TOKEN:}
