spring.profiles.active=local,stdout
spring.web.resources.cache.period=60000
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=16MB

# Logs
logging.file.path=/www/local/logs

# File
mc.gouv.file.api.url=http://localhost:30490/file/api/v1/file

# Mail
mc.gouv.mail.api.url=http://localhost:30480/mail/api/v1/mail

# VScan
mc.gouv.vscan.api.url=https://vscan-api-dev.monaco-gouvernement.mc/vscan/api/v1/scan
mc.gouv.vscan.activated=true

# MonGuichet
mc.gouv.gichuni.front.url=https://gichuni-front-dev.monaco-gouvernement.mc
mc.gouv.gichkey.url=${mc.gouv.gichuni.front.url}/auth/realms/gichuni
mc.gouv.gichuni.api.url=https://gichuni-api-dev.monaco-gouvernement.mc

# Matomo
mc.gouv.matomo.api.url=https://front-dev.monaco-gouvernement.mc/stats

# Tgf
mc.gouv.tgf.api.url=https://tgf-api-dev.monaco-gouvernement.mc/tgfapi/api/v1/verification-iban/

# Nomen
mc.gouv.nomen.api.url=https://mocksts-back-dev.monaco-gouvernement.mc

# Sms
mc.gouv.sms.api.url=https://sms-api-dev.monaco-gouvernement.mc/sms/api/v1

# Ulis
mc.gouv.ulis.api.url=https://ulis-api-mig.monaco-gouvernement.mc/ULISMIG_API

# Ged Everteam - Ulis
mc.gouv.gedeverteam.ulis.uri=https://ulis-ged-mig.monaco-gouvernement.mc/GEDULIS98
