application.module=backserver
server.port=${back.port}
# Server
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=true
# Spring
spring.security.filter.dispatcher-types=ASYNC, FORWARD, INCLUDE, REQUEST, ERROR
# la valeur est a true sur env distant, en local on met a false pour pouvoir faire du hot reload
spring.thymeleaf.cache=false
# Hibernate
spring.jpa.properties.hibernate.query.plan_cache_max_size=512
mc.gouv.backserver.help.url=http://intra
mc.gouv.backserver.contact.support.url=https://sos.monaco-gouvernement.mc/glpi/front/central.php
mc.gouv.backserver.env.name=Local
mc.gouv.backserver.env.color=#80D8FF
mc.gouv.backserver.env.displaystacktrace=true

mc.gouv.appli.backserver.matomo.site_id=0
# Gouv
mc.gouv.appli.backserver.front.key=${APPLI_BACK_FRONT_KEY}
# MonGuichet
mc.gouv.appli.backserver.gichkey.client_secret=${APPLI_BACK_GICHKEY_CLIENT_SECRET}
mc.gouv.appli.backserver.gichkey.client_id=${gichkey.client_id}
