<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>mc.gouv.xaf</groupId>
		<artifactId>xaf</artifactId>
		<version>11.0.0-SNAPSHOT</version>
	</parent>
	<artifactId>xaf-sup</artifactId>

	<dependencies>
		<dependency>
			<groupId>mc.gouv.xaf</groupId>
			<artifactId>xaf-apiclient</artifactId>
			<version>11.0.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>commons-cli</groupId>
			<artifactId>commons-cli</artifactId>
			<version>1.5.0</version>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-simple</artifactId>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>log4j-over-slf4j</artifactId>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>jul-to-slf4j</artifactId>
		</dependency>
		<dependency>
			<groupId>commons-io</groupId>
			<artifactId>commons-io</artifactId>
			<version>2.6</version>
		</dependency>
	</dependencies>
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-resources-plugin</artifactId>
				<configuration>
					<delimiters>
						<delimiter>@</delimiter>
					</delimiters>
					<useDefaultDelimiters>true</useDefaultDelimiters>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-dependency-plugin</artifactId>
				<executions>
					<execution>
						<id>copy-dependencies</id>
						<phase>package</phase>
						<goals>
							<goal>copy-dependencies</goal>
						</goals>
						<configuration>
							<outputDirectory>${project.build.directory}/lib</outputDirectory>
							<overWriteReleases>false</overWriteReleases>
							<overWriteSnapshots>false</overWriteSnapshots>
							<overWriteIfNewer>true</overWriteIfNewer>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-jar-plugin</artifactId>
				<configuration>
					<archive>
						<manifest>
							<addClasspath>true</addClasspath>
							<classpathPrefix>lib/</classpathPrefix>
						</manifest>
					</archive>
				</configuration>
			</plugin>
			<plugin>
				<artifactId>maven-assembly-plugin</artifactId>
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>single</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<descriptorRefs>
						<descriptorRef>jar-with-dependencies</descriptorRef>
					</descriptorRefs>
				</configuration>
			</plugin>
		</plugins>
	</build>


	<profiles>
		<profile>
			<id>gents-dev</id>
			<!-- <activation> <file> <exists>src/main/resources/vars/${tscode}/dev.properties</exists> 
				</file> </activation> -->
			<properties>
				<env>dev</env>
				<env.id>1</env.id>

				<global.mc.modules.dir.name>mc_modules</global.mc.modules.dir.name>
				<global.inventory.dir.name>inventory</global.inventory.dir.name>
				<global.properties.dir.name>properties</global.properties.dir.name>

				<global.generated.source.dir>${basedir}/target/generated-run/${tscode}/${env}</global.generated.source.dir>
				<global.generated.target.dir>${basedir}/target/generated-run/${env.id}-${env}/${tscode}</global.generated.target.dir>

				<global.generated.mc.modules.source.path>${global.generated.source.dir}/${global.mc.modules.dir.name}</global.generated.mc.modules.source.path>
				<global.generated.mc.modules.target.path>${global.generated.target.dir}/${global.mc.modules.dir.name}</global.generated.mc.modules.target.path>

				<global.generated.inventory.source.path>${global.generated.source.dir}/${global.inventory.dir.name}</global.generated.inventory.source.path>
				<global.generated.inventory.target.path>${global.generated.target.dir}/${global.inventory.dir.name}</global.generated.inventory.target.path>

				<global.generated.properties.source.path>${global.generated.source.dir}/${global.properties.dir.name}</global.generated.properties.source.path>
				<global.generated.properties.target.path>${global.generated.target.dir}/${global.properties.dir.name}</global.generated.properties.target.path>
			</properties>
			<build>
				<filters>
					<!-- <filter>src/main/resources/vars/${tscode}/dev.properties</filter> -->
					<filter>${vars-path}</filter>
				</filters>
				<plugins>
					<plugin>
						<artifactId>maven-resources-plugin</artifactId>
						<version>3.1.0</version>

						<configuration>
							<encoding>UTF-8</encoding>
							<resources>
								<resource>
									<directory>src/main/resources/templates/gents/${env}</directory>
									<filtering>true</filtering>
									<includes>
										<include>**/*.yml</include>
										<include>**/*.properties</include>
										<include>**/*modules</include>
										<include>**/*.html</include>
									</includes>
									<excludes>
										<exclude>**/*.MD</exclude>
									</excludes>
								</resource>
								<resource>
									<directory>src/main/resources/templates/${env}/generic</directory>
									<filtering>false</filtering>
									<excludes>
										<exclude />
									</excludes>
								</resource>
								<resource>
									<directory>src/test/resources</directory>
									<filtering>false</filtering>
								</resource>
							</resources>
						</configuration>

						<executions>
							<execution>
								<id>copy-resources</id>
								<!-- here the phase you need -->
								<phase>validate</phase>
								<goals>
									<goal>copy-resources</goal>
								</goals>
								<configuration>
									<outputDirectory>${basedir}/target/generated-run/${tscode}/${env}</outputDirectory>
									<resources>
										<resource>
											<directory>src/main/resources/templates/gents/${env}</directory>
											<filtering>true</filtering>
										</resource>
									</resources>
								</configuration>
							</execution>
						</executions>
					</plugin>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-antrun-plugin</artifactId>
						<version>1.8</version>
						<executions>
							<execution>
								<phase>package</phase>
								<goals>
									<goal>run</goal>
								</goals>
								<configuration>

									<target name="Renomage des fichiers pour le Teleservice [${tscode}] pour l'envrionnement [${env}]">
										<echo>Renommage du fichier [README.MD]</echo>
										<!-- <move file="${global.generated.source.dir}/README.MD" tofile="${global.generated.target.dir}/README.MD" verbose="true" /> -->

										<echo>Renommage des fichiers de [mc_modules]</echo>
										<move file="${global.generated.mc.modules.source.path}/apiserver.yml" tofile="${global.generated.mc.modules.target.path}/${tscode}-apiserver.yml" verbose="true" />
										<move file="${global.generated.mc.modules.source.path}/backserver.yml" tofile="${global.generated.mc.modules.target.path}/${tscode}-backserver.yml" verbose="true" />
										<move file="${global.generated.mc.modules.source.path}/frontserver.yml" tofile="${global.generated.mc.modules.target.path}/${tscode}-frontserver.yml" verbose="true" />

										<echo>Renommage des fichiers de [properties]</echo>
										<move file="${global.generated.properties.source.path}/apiserver.properties" tofile="${global.generated.properties.target.path}/${tscode}-apiserver.properties" verbose="true" />
										<move file="${global.generated.properties.source.path}/backserver.properties" tofile="${global.generated.properties.target.path}/${tscode}-backserver.properties" verbose="true" />
										<move file="${global.generated.properties.source.path}/frontserver.properties" tofile="${global.generated.properties.target.path}/${tscode}-frontserver.properties" verbose="true" />
										<move file="${global.generated.properties.source.path}/shared-backapi.properties" tofile="${global.generated.properties.target.path}/shared-${tscode}backapi.properties" verbose="true" />

										<echo>Renommage des fichiers de [inventory]</echo>
										<move file="${global.generated.inventory.source.path}/modules" tofile="${global.generated.inventory.target.path}/${tscode}-modules" verbose="true" />

										<echo>Supression du repertoire
											[${global.generated.source.dir}]
										</echo>
										<!-- <delete dir="${global.generated.source.dir}" /> -->
									</target>

								</configuration>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>

		<profile>
			<id>gents-rec</id>
			<!-- <activation> <file> <exists>src/main/resources/vars/${tscode}/rec.properties</exists> 
				</file> </activation> -->
			<properties>
				<env>rec</env>
				<env.id>3</env.id>

				<global.generated.source.dir>${basedir}/target/generated-run/${tscode}/${env}</global.generated.source.dir>
				<global.generated.target.dir>${basedir}/target/generated-run/${env.id}-${env}/${tscode}</global.generated.target.dir>

				<global.mc.modules.dir.name>mc_modules</global.mc.modules.dir.name>
				<global.generated.mc.modules.source.path>${global.generated.source.dir}/${global.mc.modules.dir.name}</global.generated.mc.modules.source.path>
				<global.generated.mc.modules.target.path>${global.generated.target.dir}/${global.mc.modules.dir.name}</global.generated.mc.modules.target.path>

				<global.inventory.dir.name>inventory</global.inventory.dir.name>
				<global.inventory.group_vars.dir.name>group_vars</global.inventory.group_vars.dir.name>
				<global.inventory.host_vars.dir.name>host_vars</global.inventory.host_vars.dir.name>

				<global.generated.inventory.source.path>${global.generated.source.dir}/${global.inventory.dir.name}</global.generated.inventory.source.path>
				<global.generated.inventory.group_vars.source.path>${global.generated.source.dir}/${global.inventory.dir.name}/${global.inventory.group_vars.dir.name}</global.generated.inventory.group_vars.source.path>
				<global.generated.inventory.host_vars.source.path>${global.generated.source.dir}/${global.inventory.dir.name}/${global.inventory.host_vars.dir.name}</global.generated.inventory.host_vars.source.path>

				<global.generated.inventory.target.path>${global.generated.target.dir}/${global.inventory.dir.name}</global.generated.inventory.target.path>
				<global.generated.inventory.group_vars.target.path>${global.generated.target.dir}/${global.inventory.dir.name}/${global.inventory.group_vars.dir.name}</global.generated.inventory.group_vars.target.path>
				<global.generated.inventory.host_vars.target.path>${global.generated.target.dir}/${global.inventory.dir.name}/${global.inventory.host_vars.dir.name}</global.generated.inventory.host_vars.target.path>

				<global.properties.dir.name>properties</global.properties.dir.name>
				<global.generated.properties.source.path>${global.generated.source.dir}/${global.properties.dir.name}</global.generated.properties.source.path>
				<global.generated.properties.target.path>${global.generated.target.dir}/${global.properties.dir.name}</global.generated.properties.target.path>
			</properties>
			<build>
				<filters>
					<filter>${vars-path}</filter>
				</filters>
				<plugins>
					<plugin>
						<artifactId>maven-resources-plugin</artifactId>
						<version>3.1.0</version>

						<configuration>
							<encoding>UTF-8</encoding>
							<resources>
								<resource>
									<directory>src/main/resources/templates/gents/${env}</directory>
									<directory>src/main/resources/templates/redmine/rec</directory>
									<filtering>true</filtering>
									<includes>
										<include>**/*.yml</include>
										<include>**/*.properties</include>
										<include>**/*</include>
										<include>**/*.html</include>
									</includes>
									<excludes>
										<exclude>**/*.MD</exclude>
									</excludes>
								</resource>
								<resource>
									<directory>src/main/resources/templates/${env}/generic</directory>
									<filtering>false</filtering>
								</resource>
								<resource>
									<directory>src/test/resources</directory>
									<filtering>false</filtering>
								</resource>
							</resources>
						</configuration>

						<executions>
							<execution>
								<id>copy-resources</id>
								<!-- here the phase you need -->
								<phase>validate</phase>
								<goals>
									<goal>copy-resources</goal>
								</goals>
								<configuration>
									<outputDirectory>${basedir}/target/generated-run/${tscode}/${env}</outputDirectory>
									<resources>
										<resource>
											<directory>src/main/resources/templates/gents/${env}</directory>
											<filtering>true</filtering>
										</resource>
									</resources>
								</configuration>
							</execution>
						</executions>
					</plugin>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-antrun-plugin</artifactId>
						<version>1.8</version>
						<executions>
							<execution>
								<phase>package</phase>
								<goals>
									<goal>run</goal>
								</goals>
								<configuration>
									<target name="Renomage des fichiers pour le Teleservice [${tscode}] pour l'envrionnement [${env}]">
										<echo>Renommage du fichier [README.MD]</echo>
										<!-- <move file="${global.generated.source.dir}/README.MD" tofile="${global.generated.target.dir}/README.MD" verbose="true" /> -->

										<echo>Renommage des fichiers de [mc_modules]</echo>
										<move file="${global.generated.mc.modules.source.path}/apiserver.yml" tofile="${global.generated.mc.modules.target.path}/${tscode}-apiserver.yml" verbose="true" />
										<move file="${global.generated.mc.modules.source.path}/backserver.yml" tofile="${global.generated.mc.modules.target.path}/${tscode}-backserver.yml" verbose="true" />
										<move file="${global.generated.mc.modules.source.path}/frontserver.yml" tofile="${global.generated.mc.modules.target.path}/${tscode}-frontserver.yml" verbose="true" />

										<echo>Renommage des fichiers de [properties]</echo>
										<move file="${global.generated.properties.source.path}/apiserver.properties" tofile="${global.generated.properties.target.path}/${tscode}-apiserver.properties" verbose="true" />
										<move file="${global.generated.properties.source.path}/backserver.properties" tofile="${global.generated.properties.target.path}/${tscode}-backserver.properties" verbose="true" />
										<move file="${global.generated.properties.source.path}/frontserver.properties" tofile="${global.generated.properties.target.path}/${tscode}-frontserver.properties" verbose="true" />
										<move file="${global.generated.properties.source.path}/shared-backapi.properties" tofile="${global.generated.properties.target.path}/shared-${tscode}backapi.properties" verbose="true" />

										<echo>Renommage des fichiers de [inventory]</echo>
										<move file="${global.generated.inventory.source.path}/modules" tofile="${global.generated.inventory.target.path}/${tscode}-modules" verbose="true" />
										<move file="${global.generated.inventory.source.path}/tscode" tofile="${global.generated.inventory.target.path}/${tscode}" verbose="true" />

										<move file="${global.generated.inventory.group_vars.source.path}/all.yml" tofile="${global.generated.inventory.group_vars.target.path}/all.yml" verbose="true" />
										<move file="${global.generated.inventory.group_vars.source.path}/as-server.yml" tofile="${global.generated.inventory.group_vars.target.path}/as-server.yml" verbose="true" />
										<move file="${global.generated.inventory.group_vars.source.path}/as.yml" tofile="${global.generated.inventory.group_vars.target.path}/as.yml" verbose="true" />

										<move file="${global.generated.inventory.host_vars.source.path}/appl1-${env.id}.yml" tofile="${global.generated.inventory.host_vars.target.path}/${tscode}-appl1-${env.id}.yml" verbose="true" />
										<move file="${global.generated.inventory.host_vars.source.path}/eose1-${env.id}.yml" tofile="${global.generated.inventory.host_vars.target.path}/${tscode}-eose1-${env.id}.yml" verbose="true" />
										<move file="${global.generated.inventory.host_vars.source.path}/frnt1-${env.id}.yml" tofile="${global.generated.inventory.host_vars.target.path}/${tscode}-frnt1-${env.id}.yml" verbose="true" />

										<move file="${global.generated.inventory.host_vars.source.path}/linux-zabbix-proxyr1.yml" tofile="${global.generated.inventory.host_vars.target.path}/linux-zabbix-proxyr1.yml" verbose="true" />
										<move file="${global.generated.inventory.host_vars.source.path}/zabbix3.yml" tofile="${global.generated.inventory.host_vars.target.path}/zabbix3.yml" verbose="true" />

										<echo>Supression du repertoire
											[${global.generated.source.dir}]
										</echo>
										<!-- <delete dir="${global.generated.source.dir}" /> -->
									</target>

								</configuration>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
		<profile>
			<id>gents-prod</id>
			<!-- <activation> <file> <exists>src/main/resources/vars/${tscode}/prod.properties</exists> 
				</file> </activation> -->
			<properties>
				<env>prod</env>
				<env.id>0</env.id>

				<global.generated.source.dir>${basedir}/target/generated-run/${tscode}/${env}</global.generated.source.dir>
				<global.generated.target.dir>${basedir}/target/generated-run/${env.id}-${env}/${tscode}</global.generated.target.dir>

				<global.mc.modules.dir.name>mc_modules</global.mc.modules.dir.name>
				<global.generated.mc.modules.source.path>${global.generated.source.dir}/${global.mc.modules.dir.name}</global.generated.mc.modules.source.path>
				<global.generated.mc.modules.target.path>${global.generated.target.dir}/${global.mc.modules.dir.name}</global.generated.mc.modules.target.path>

				<global.inventory.dir.name>inventory</global.inventory.dir.name>
				<global.inventory.group_vars.dir.name>group_vars</global.inventory.group_vars.dir.name>
				<global.inventory.host_vars.dir.name>host_vars</global.inventory.host_vars.dir.name>

				<global.generated.inventory.source.path>${global.generated.source.dir}/${global.inventory.dir.name}</global.generated.inventory.source.path>
				<global.generated.inventory.group_vars.source.path>${global.generated.source.dir}/${global.inventory.dir.name}/${global.inventory.group_vars.dir.name}</global.generated.inventory.group_vars.source.path>
				<global.generated.inventory.host_vars.source.path>${global.generated.source.dir}/${global.inventory.dir.name}/${global.inventory.host_vars.dir.name}</global.generated.inventory.host_vars.source.path>

				<global.generated.inventory.target.path>${global.generated.target.dir}/${global.inventory.dir.name}</global.generated.inventory.target.path>
				<global.generated.inventory.group_vars.target.path>${global.generated.target.dir}/${global.inventory.dir.name}/${global.inventory.group_vars.dir.name}</global.generated.inventory.group_vars.target.path>
				<global.generated.inventory.host_vars.target.path>${global.generated.target.dir}/${global.inventory.dir.name}/${global.inventory.host_vars.dir.name}</global.generated.inventory.host_vars.target.path>

				<global.properties.dir.name>properties</global.properties.dir.name>
				<global.generated.properties.source.path>${global.generated.source.dir}/${global.properties.dir.name}</global.generated.properties.source.path>
				<global.generated.properties.target.path>${global.generated.target.dir}/${global.properties.dir.name}</global.generated.properties.target.path>
			</properties>
			<build>
				<filters>
					<filter>${vars-path}</filter>
				</filters>
				<plugins>
					<plugin>
						<artifactId>maven-resources-plugin</artifactId>
						<version>3.1.0</version>

						<configuration>
							<encoding>UTF-8</encoding>
							<resources>
								<resource>
									<directory>src/main/resources/templates/gents/prod</directory>
									<filtering>true</filtering>
									<includes>
										<include>**/*.yml</include>
										<include>**/*.properties</include>
										<include>**/*</include>
										<include>**/*.html</include>
									</includes>
									<excludes>
										<exclude>**/*.MD</exclude>
									</excludes>
								</resource>
								<resource>
									<directory>src/main/resources/templates/${env}/generic</directory>
									<filtering>false</filtering>
								</resource>
								<resource>
									<directory>src/test/resources</directory>
									<filtering>false</filtering>
								</resource>
							</resources>
						</configuration>

						<executions>
							<execution>
								<id>copy-resources</id>
								<!-- here the phase you need -->
								<phase>validate</phase>
								<goals>
									<goal>copy-resources</goal>
								</goals>
								<configuration>
									<outputDirectory>${basedir}/target/generated-run/${tscode}/${env}</outputDirectory>
									<resources>
										<resource>
											<directory>src/main/resources/templates/gents/${env}</directory>
											<filtering>true</filtering>
										</resource>
									</resources>
								</configuration>
							</execution>
						</executions>
					</plugin>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-antrun-plugin</artifactId>
						<version>1.8</version>
						<executions>
							<execution>
								<phase>package</phase>
								<goals>
									<goal>run</goal>
								</goals>
								<configuration>
									<target name="Renomage des fichiers pour le Teleservice [${tscode}] pour l'envrionnement [${env}]">
										<echo>Renommage du fichier [README.MD]</echo>
										<!-- <move file="${global.generated.source.dir}/README.MD" tofile="${global.generated.target.dir}/README.MD" verbose="true" /> -->
										<echo>Renommage des fichiers de [mc_modules]</echo>
										<move file="${global.generated.mc.modules.source.path}/apiserver.yml" tofile="${global.generated.mc.modules.target.path}/${tscode}-apiserver.yml" verbose="true" />
										<move file="${global.generated.mc.modules.source.path}/backserver.yml" tofile="${global.generated.mc.modules.target.path}/${tscode}-backserver.yml" verbose="true" />
										<move file="${global.generated.mc.modules.source.path}/frontserver.yml" tofile="${global.generated.mc.modules.target.path}/${tscode}-frontserver.yml" verbose="true" />

										<echo>Renommage des fichiers de [properties]</echo>
										<move file="${global.generated.properties.source.path}/apiserver.properties" tofile="${global.generated.properties.target.path}/${tscode}-apiserver.properties" verbose="true" />
										<move file="${global.generated.properties.source.path}/backserver.properties" tofile="${global.generated.properties.target.path}/${tscode}-backserver.properties" verbose="true" />
										<move file="${global.generated.properties.source.path}/frontserver.properties" tofile="${global.generated.properties.target.path}/${tscode}-frontserver.properties" verbose="true" />
										<move file="${global.generated.properties.source.path}/shared-backapi.properties" tofile="${global.generated.properties.target.path}/shared-${tscode}backapi.properties" verbose="true" />

										<echo>Renommage des fichiers de [inventory]</echo>
										<move file="${global.generated.inventory.source.path}/modules" tofile="${global.generated.inventory.target.path}/${tscode}-modules" verbose="true" />
										<move file="${global.generated.inventory.source.path}/tscode" tofile="${global.generated.inventory.target.path}/${tscode}" verbose="true" />
										<move file="${global.generated.inventory.group_vars.source.path}/all.yml" tofile="${global.generated.inventory.group_vars.target.path}/all.yml" verbose="true" />
										<!-- <move file="${global.generated.inventory.group_vars.source.path}/as-server.yml" tofile="${global.generated.inventory.group_vars.target.path}/as-server.yml" verbose="true" /> -->
										<move file="${global.generated.inventory.group_vars.source.path}/as.yml" tofile="${global.generated.inventory.group_vars.target.path}/as.yml" verbose="true" />

										<move file="${global.generated.inventory.host_vars.source.path}/appl1-${env.id}.yml" tofile="${global.generated.inventory.host_vars.target.path}/${tscode}-appl1-${env.id}.yml" verbose="true" />
										<move file="${global.generated.inventory.host_vars.source.path}/eose1-${env.id}.yml" tofile="${global.generated.inventory.host_vars.target.path}/${tscode}-eose1-${env.id}.yml" verbose="true" />
										<move file="${global.generated.inventory.host_vars.source.path}/frnt1-${env.id}.yml" tofile="${global.generated.inventory.host_vars.target.path}/${tscode}-frnt1-${env.id}.yml" verbose="true" />
										<move file="${global.generated.inventory.host_vars.source.path}/zabbix3.yml" tofile="${global.generated.inventory.host_vars.target.path}/zabbix3.yml" verbose="true" />
										<move file="${global.generated.inventory.host_vars.source.path}/zabbix3-dmz.yml" tofile="${global.generated.inventory.host_vars.target.path}/zabbix3-dmz.yml" verbose="true" />

										<echo>Supression du repertoire
											[${global.generated.source.dir}]
										</echo>
										<!-- <delete dir="${global.generated.source.dir}" /> -->
									</target>

								</configuration>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>

		<profile>
			<id>gentsa-dev</id>
			<!-- <activation> <file> <exists>src/main/resources/vars/${tscode}/dev.properties</exists> 
				</file> </activation> -->
			<properties>
				<env>dev</env>
				<env.id>1</env.id>

				<global.mc.modules.dir.name>mc_modules</global.mc.modules.dir.name>
				<global.inventory.dir.name>inventory</global.inventory.dir.name>
				<global.properties.dir.name>properties</global.properties.dir.name>
				<global.host.vars.dir.name>host_vars</global.host.vars.dir.name>

				<global.generated.source.dir>${basedir}/target/generated-run/${tscode}/${env}</global.generated.source.dir>
				<global.generated.target.dir>${basedir}/target/generated-run/${env.id}-${env}/${tscode}</global.generated.target.dir>

				<global.generated.mc.modules.source.path>${global.generated.source.dir}/${global.mc.modules.dir.name}</global.generated.mc.modules.source.path>
				<global.generated.mc.modules.target.path>${global.generated.target.dir}/${global.mc.modules.dir.name}</global.generated.mc.modules.target.path>

				<global.generated.inventory.source.path>${global.generated.source.dir}/${global.inventory.dir.name}</global.generated.inventory.source.path>
				<global.generated.inventory.target.path>${global.generated.target.dir}/${global.inventory.dir.name}</global.generated.inventory.target.path>

				<global.generated.properties.source.path>${global.generated.source.dir}/${global.properties.dir.name}</global.generated.properties.source.path>
				<global.generated.properties.target.path>${global.generated.target.dir}/${global.properties.dir.name}</global.generated.properties.target.path>
			</properties>
			<build>
				<filters>
					<!-- <filter>src/main/resources/vars/${tscode}/dev.properties</filter> -->
					<filter>${vars-path}</filter>
				</filters>
				<plugins>
					<plugin>
						<artifactId>maven-resources-plugin</artifactId>
						<version>3.1.0</version>

						<configuration>
							<encoding>UTF-8</encoding>
							<resources>
								<resource>
									<directory>src/main/resources/templates/gentsa/${env}</directory>
									<filtering>true</filtering>
									<includes>
										<include>**/*.yml</include>
										<include>**/*.properties</include>
										<include>**/*modules</include>
									</includes>
									<excludes>
										<exclude>**/*.MD</exclude>
									</excludes>
								</resource>
							</resources>
						</configuration>

						<executions>
							<execution>
								<id>copy-resources</id>
								<!-- here the phase you need -->
								<phase>validate</phase>
								<goals>
									<goal>copy-resources</goal>
								</goals>
								<configuration>
									<outputDirectory>${basedir}/target/generated-run/${tscode}/${env}</outputDirectory>
									<resources>
										<resource>
											<directory>src/main/resources/templates/gentsa/${env}</directory>
											<filtering>true</filtering>
										</resource>
									</resources>
								</configuration>
							</execution>
						</executions>
					</plugin>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-antrun-plugin</artifactId>
						<version>1.8</version>
						<executions>
							<execution>
								<phase>package</phase>
								<goals>
									<goal>run</goal>
								</goals>
								<configuration>

									<target name="Renomage des fichiers pour le Teleservice [${tscode}] pour l'envrionnement [${env}]">
										<echo>Renommage du fichier [README.MD]</echo>
										<!-- <move file="${global.generated.source.dir}/README.MD" tofile="${global.generated.target.dir}/README.MD" verbose="true" /> -->
										<echo>Renommage des fichiers de [mc_modules]</echo>
										<move file="${global.generated.mc.modules.source.path}/apiserver.yml" tofile="${global.generated.mc.modules.target.path}/${tscode}-apiserver.yml" verbose="true" />
										<move file="${global.generated.mc.modules.source.path}/backserver.yml" tofile="${global.generated.mc.modules.target.path}/${tscode}-backserver.yml" verbose="true" />
										<move file="${global.generated.mc.modules.source.path}/frontserver.yml" tofile="${global.generated.mc.modules.target.path}/${tscode}-frontserver.yml" verbose="true" />

										<echo>Renommage des fichiers de [properties]</echo>
										<move file="${global.generated.properties.source.path}/apiserver.properties" tofile="${global.generated.properties.target.path}/${tscode}-apiserver.properties" verbose="true" />
										<move file="${global.generated.properties.source.path}/backserver.properties" tofile="${global.generated.properties.target.path}/${tscode}-backserver.properties" verbose="true" />
										<move file="${global.generated.properties.source.path}/frontserver.properties" tofile="${global.generated.properties.target.path}/${tscode}-frontserver.properties" verbose="true" />
										<move file="${global.generated.properties.source.path}/shared-backapi.properties" tofile="${global.generated.properties.target.path}/shared-${tscode}backapi.properties" verbose="true" />

										<echo>Renommage des fichiers de [inventory]</echo>
										<move file="${global.generated.inventory.source.path}/modules" tofile="${global.generated.inventory.target.path}/${tscode}-modules" verbose="true" />

										<echo>Renommage des fichiers de [host_vars]</echo>
										<move file="${global.generated.inventory.source.path}/host_vars/gentsa-frnt1-${env.id}.yml" tofile="${global.generated.inventory.target.path}/host_vars/gentsa-frnt1-${env.id}.yml" verbose="true" />
										<move file="${global.generated.inventory.source.path}/host_vars/gentsa-frnt2-${env.id}.yml" tofile="${global.generated.inventory.target.path}/host_vars/gentsa-frnt2-${env.id}.yml" verbose="true" />
										<move file="${global.generated.inventory.source.path}/host_vars/linux-zabbix-proxyd1.yml" tofile="${global.generated.inventory.target.path}/host_vars/linux-zabbix-proxyd1.yml" verbose="true" />

										<echo>Supression du repertoire
											[${global.generated.source.dir}]
										</echo>
										<!-- <delete dir="${global.generated.source.dir}" /> -->
									</target>

								</configuration>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
		<profile>
			<id>gentsa-rec</id>
			<!-- <activation> <file> <exists>src/main/resources/vars/${tscode}/dev.properties</exists> 
				</file> </activation> -->
			<properties>
				<env>rec</env>
				<env.id>3</env.id>

				<global.mc.modules.dir.name>mc_modules</global.mc.modules.dir.name>
				<global.inventory.dir.name>inventory</global.inventory.dir.name>
				<global.properties.dir.name>properties</global.properties.dir.name>
				<global.host.vars.dir.name>host_vars</global.host.vars.dir.name>

				<global.generated.source.dir>${basedir}/target/generated-run/${tscode}/${env}</global.generated.source.dir>
				<global.generated.target.dir>${basedir}/target/generated-run/${env.id}-${env}/${tscode}</global.generated.target.dir>

				<global.generated.mc.modules.source.path>${global.generated.source.dir}/${global.mc.modules.dir.name}</global.generated.mc.modules.source.path>
				<global.generated.mc.modules.target.path>${global.generated.target.dir}/${global.mc.modules.dir.name}</global.generated.mc.modules.target.path>

				<global.generated.inventory.source.path>${global.generated.source.dir}/${global.inventory.dir.name}</global.generated.inventory.source.path>
				<global.generated.inventory.target.path>${global.generated.target.dir}/${global.inventory.dir.name}</global.generated.inventory.target.path>

				<global.generated.properties.source.path>${global.generated.source.dir}/${global.properties.dir.name}</global.generated.properties.source.path>
				<global.generated.properties.target.path>${global.generated.target.dir}/${global.properties.dir.name}</global.generated.properties.target.path>
			</properties>
			<build>
				<filters>
					<!-- <filter>src/main/resources/vars/${tscode}/dev.properties</filter> -->
					<filter>${vars-path}</filter>
				</filters>
				<plugins>
					<plugin>
						<artifactId>maven-resources-plugin</artifactId>
						<version>3.1.0</version>

						<configuration>
							<encoding>UTF-8</encoding>
							<resources>
								<resource>
									<directory>src/main/resources/templates/gentsa/${env}</directory>
									<filtering>true</filtering>
									<includes>
										<include>**/*.yml</include>
										<include>**/*.properties</include>
										<include>**/*modules</include>
									</includes>
									<excludes>
										<exclude>**/*.MD</exclude>
									</excludes>
								</resource>
							</resources>
						</configuration>

						<executions>
							<execution>
								<id>copy-resources</id>
								<!-- here the phase you need -->
								<phase>validate</phase>
								<goals>
									<goal>copy-resources</goal>
								</goals>
								<configuration>
									<outputDirectory>${basedir}/target/generated-run/${tscode}/${env}</outputDirectory>
									<resources>
										<resource>
											<directory>src/main/resources/templates/gentsa/${env}</directory>
											<filtering>true</filtering>
										</resource>
									</resources>
								</configuration>
							</execution>
						</executions>
					</plugin>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-antrun-plugin</artifactId>
						<version>1.8</version>
						<executions>
							<execution>
								<phase>package</phase>
								<goals>
									<goal>run</goal>
								</goals>
								<configuration>

									<target name="Renomage des fichiers pour le Teleservice [${tscode}] pour l'envrionnement [${env}]">
										<echo>Renommage du fichier [README.MD]</echo>
										<!-- <move file="${global.generated.source.dir}/README.MD" tofile="${global.generated.target.dir}/README.MD" verbose="true" /> -->
										<echo>Renommage des fichiers de [mc_modules]</echo>
										<move file="${global.generated.mc.modules.source.path}/apiserver.yml" tofile="${global.generated.mc.modules.target.path}/${tscode}-apiserver.yml" verbose="true" />
										<move file="${global.generated.mc.modules.source.path}/backserver.yml" tofile="${global.generated.mc.modules.target.path}/${tscode}-backserver.yml" verbose="true" />
										<move file="${global.generated.mc.modules.source.path}/frontserver.yml" tofile="${global.generated.mc.modules.target.path}/${tscode}-frontserver.yml" verbose="true" />

										<echo>Renommage des fichiers de [properties]</echo>
										<move file="${global.generated.properties.source.path}/apiserver.properties" tofile="${global.generated.properties.target.path}/${tscode}-apiserver.properties" verbose="true" />
										<move file="${global.generated.properties.source.path}/backserver.properties" tofile="${global.generated.properties.target.path}/${tscode}-backserver.properties" verbose="true" />
										<move file="${global.generated.properties.source.path}/frontserver.properties" tofile="${global.generated.properties.target.path}/${tscode}-frontserver.properties" verbose="true" />
										<move file="${global.generated.properties.source.path}/shared-backapi.properties" tofile="${global.generated.properties.target.path}/shared-${tscode}backapi.properties" verbose="true" />

										<echo>Renommage des fichiers de [inventory]</echo>
										<move file="${global.generated.inventory.source.path}/modules" tofile="${global.generated.inventory.target.path}/${tscode}-modules" verbose="true" />


										<echo>Renommage des fichiers de [host_vars]</echo>
										<move file="${global.generated.inventory.source.path}/host_vars/gentsa-frnt1-${env.id}.yml" tofile="${global.generated.inventory.target.path}/host_vars/gentsa-frnt1-${env.id}.yml" verbose="true" />
										<move file="${global.generated.inventory.source.path}/host_vars/gentsa-frnt2-${env.id}.yml" tofile="${global.generated.inventory.target.path}/host_vars/gentsa-frnt2-${env.id}.yml" verbose="true" />
										<move file="${global.generated.inventory.source.path}/host_vars/linux-zabbix-proxyd1.yml" tofile="${global.generated.inventory.target.path}/host_vars/linux-zabbix-proxyd1.yml" verbose="true" />

										<echo>Supression du repertoire
											[${global.generated.source.dir}]
										</echo>
										<!-- <delete dir="${global.generated.source.dir}" /> -->
									</target>

								</configuration>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
		<profile>
			<id>gentsa-prod</id>
			<!-- <activation> <file> <exists>src/main/resources/vars/${tscode}/dev.properties</exists> 
				</file> </activation> -->
			<properties>
				<env>prod</env>
				<env.id>0</env.id>

				<global.mc.modules.dir.name>mc_modules</global.mc.modules.dir.name>
				<global.inventory.dir.name>inventory</global.inventory.dir.name>
				<global.properties.dir.name>properties</global.properties.dir.name>
				<global.host.vars.dir.name>host_vars</global.host.vars.dir.name>

				<global.generated.source.dir>${basedir}/target/generated-run/${tscode}/${env}</global.generated.source.dir>
				<global.generated.target.dir>${basedir}/target/generated-run/${env.id}-${env}/${tscode}</global.generated.target.dir>

				<global.generated.mc.modules.source.path>${global.generated.source.dir}/${global.mc.modules.dir.name}</global.generated.mc.modules.source.path>
				<global.generated.mc.modules.target.path>${global.generated.target.dir}/${global.mc.modules.dir.name}</global.generated.mc.modules.target.path>

				<global.generated.inventory.source.path>${global.generated.source.dir}/${global.inventory.dir.name}</global.generated.inventory.source.path>
				<global.generated.inventory.target.path>${global.generated.target.dir}/${global.inventory.dir.name}</global.generated.inventory.target.path>

				<global.generated.properties.source.path>${global.generated.source.dir}/${global.properties.dir.name}</global.generated.properties.source.path>
				<global.generated.properties.target.path>${global.generated.target.dir}/${global.properties.dir.name}</global.generated.properties.target.path>
			</properties>
			<build>
				<filters>
					<!-- <filter>src/main/resources/vars/${tscode}/dev.properties</filter> -->
					<filter>${vars-path}</filter>
				</filters>
				<plugins>
					<plugin>
						<artifactId>maven-resources-plugin</artifactId>
						<version>3.1.0</version>

						<configuration>
							<encoding>UTF-8</encoding>
							<resources>
								<resource>
									<directory>src/main/resources/templates/gentsa/${env}</directory>
									<filtering>true</filtering>
									<includes>
										<include>**/*.yml</include>
										<include>**/*.properties</include>
										<include>**/*modules</include>
									</includes>
									<excludes>
										<exclude>**/*.MD</exclude>
									</excludes>
								</resource>
							</resources>
						</configuration>

						<executions>
							<execution>
								<id>copy-resources</id>
								<!-- here the phase you need -->
								<phase>validate</phase>
								<goals>
									<goal>copy-resources</goal>
								</goals>
								<configuration>
									<outputDirectory>${basedir}/target/generated-run/${tscode}/${env}</outputDirectory>
									<resources>
										<resource>
											<directory>src/main/resources/templates/gentsa/${env}</directory>
											<filtering>true</filtering>
										</resource>
									</resources>
								</configuration>
							</execution>
						</executions>
					</plugin>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-antrun-plugin</artifactId>
						<version>1.8</version>
						<executions>
							<execution>
								<phase>package</phase>
								<goals>
									<goal>run</goal>
								</goals>
								<configuration>

									<target name="Renomage des fichiers pour le Teleservice [${tscode}] pour l'envrionnement [${env}]">
										<echo>Renommage du fichier [README.MD]</echo>
										<!-- <move file="${global.generated.source.dir}/README.MD" tofile="${global.generated.target.dir}/README.MD" verbose="true" /> -->

										<echo>Renommage des fichiers de [mc_modules]</echo>
										<move file="${global.generated.mc.modules.source.path}/apiserver.yml" tofile="${global.generated.mc.modules.target.path}/${tscode}-apiserver.yml" verbose="true" />
										<move file="${global.generated.mc.modules.source.path}/backserver.yml" tofile="${global.generated.mc.modules.target.path}/${tscode}-backserver.yml" verbose="true" />
										<move file="${global.generated.mc.modules.source.path}/frontserver.yml" tofile="${global.generated.mc.modules.target.path}/${tscode}-frontserver.yml" verbose="true" />

										<echo>Renommage des fichiers de [properties]</echo>
										<move file="${global.generated.properties.source.path}/apiserver.properties" tofile="${global.generated.properties.target.path}/${tscode}-apiserver.properties" verbose="true" />
										<move file="${global.generated.properties.source.path}/backserver.properties" tofile="${global.generated.properties.target.path}/${tscode}-backserver.properties" verbose="true" />
										<move file="${global.generated.properties.source.path}/frontserver.properties" tofile="${global.generated.properties.target.path}/${tscode}-frontserver.properties" verbose="true" />
										<move file="${global.generated.properties.source.path}/shared-backapi.properties" tofile="${global.generated.properties.target.path}/shared-${tscode}backapi.properties" verbose="true" />

										<echo>Renommage des fichiers de [inventory]</echo>
										<move file="${global.generated.inventory.source.path}/modules" tofile="${global.generated.inventory.target.path}/${tscode}-modules" verbose="true" />


										<echo>Renommage des fichiers de [host_vars]</echo>
										<move file="${global.generated.inventory.source.path}/host_vars/gentsa-frnt1-${env.id}.yml" tofile="${global.generated.inventory.target.path}/host_vars/gentsa-frnt1-${env.id}.yml" verbose="true" />
										<move file="${global.generated.inventory.source.path}/host_vars/gentsa-frnt2-${env.id}.yml" tofile="${global.generated.inventory.target.path}/host_vars/gentsa-frnt2-${env.id}.yml" verbose="true" />
										<move file="${global.generated.inventory.source.path}/host_vars/zabbix3.yml" tofile="${global.generated.inventory.target.path}/host_vars/zabbix3.yml" verbose="true" />
										<move file="${global.generated.inventory.source.path}/host_vars/zabbix3-dmz.yml" tofile="${global.generated.inventory.target.path}/host_vars/zabbix3-dmz.yml" verbose="true" />

										<echo>Supression du repertoire
											[${global.generated.source.dir}]
										</echo>
										<!-- <delete dir="${global.generated.source.dir}" /> -->
									</target>

								</configuration>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>

		<!-- Profile pour générer les contenus des tickets Redmine -->
		<profile>
			<id>redmine</id>
			<!-- <activation> <file> <exists>src/main/resources/vars/${tscode}/rec.properties</exists> 
				</file> </activation> -->
			<properties>
				<env>rec</env>
				<env.id>3</env.id>
			</properties>
			<build>
				<filters>
					<filter>${vars-path}</filter>
				</filters>
				<plugins>
					<plugin>
						<artifactId>maven-resources-plugin</artifactId>
						<version>3.1.0</version>

						<configuration>
							<encoding>UTF-8</encoding>
							<resources>
								<resource>
									<directory>src/main/resources/templates/redmine/${env}</directory>
									<filtering>true</filtering>
									<includes>
										<include>**/*.html</include>
										<include>**/*.txt</include>
									</includes>
								</resource>
								<resource>
									<directory>src/main/resources/templates/${env}/generic</directory>
									<filtering>false</filtering>
								</resource>
								<resource>
									<directory>src/test/resources</directory>
									<filtering>false</filtering>
								</resource>
							</resources>
						</configuration>

						<executions>
							<execution>
								<id>copy-resources</id>
								<!-- here the phase you need -->
								<phase>validate</phase>
								<goals>
									<goal>copy-resources</goal>
								</goals>
								<configuration>
									<outputDirectory>${basedir}/target/generated-redmine/${tscode}/${env}</outputDirectory>
									<resources>
										<resource>
											<directory>src/main/resources/templates/redmine/${env}</directory>
											<filtering>true</filtering>
										</resource>
									</resources>
								</configuration>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>

	</profiles>
</project>