---
tcp_checks:
  - name: ${tscode}-backserver1-1-http
    host: gentsa-back1-1
    port: 10${tsport}0
  - name: ${tscode}-backserver2-1-http
    host: gentsa-back2-1
    port: 10${tsport}0
  - name: ${tscode}-backserver1-1-jmx
    host: gentsa-back1-1
    port: 10${tsport}1
  - name: ${tscode}-backserver2-1-jmx
    host: gentsa-back2-1
    port: 10${tsport}1
  - name: ${tscode}-backserver1-1-rmi
    host: gentsa-back1-1
    port: 10${tsport}2
  - name: ${tscode}-backserver2-1-rmi
    host: gentsa-back2-1
    port: 10${tsport}2
  - name: ${tscode}-apiserver1-1-http
    host: gentsa-apis1-1
    port: 30${tsport}0
  - name: ${tscode}-apiserver2-1-http
    host: gentsa-apis2-1
    port: 30${tsport}0
  - name: ${tscode}-apiserver1-1-jmx
    host: gentsa-apis1-1
    port: 30${tsport}1
  - name: ${tscode}-apiserver2-1-jmx
    host: gentsa-apis2-1
    port: 30${tsport}1
  - name: ${tscode}-apiserver1-1-rmi
    host: gentsa-apis1-1
    port: 30${tsport}2
  - name: ${tscode}-apiserver2-1-rmi
    host: gentsa-apis2-1
    port: 30${tsport}2
  - name: ${tscode}-frontserver1-1-http
    host: gentsa-frnt1-1
    port: 20${tsport}0
  - name: ${tscode}-frontserver2-1-http
    host: gentsa-frnt2-1
    port: 20${tsport}0
  - name: ${tscode}-frontserver1-1-jmx
    host: gentsa-frnt1-1
    port: 20${tsport}1
  - name: ${tscode}-frontserver2-1-jmx
    host: gentsa-frnt2-1
    port: 20${tsport}1
  - name: ${tscode}-frontserver1-1-rmi
    host: gentsa-frnt1-1
    port: 20${tsport}2
  - name: ${tscode}-frontserver2-1-rmi
    host: gentsa-frnt2-1
    port: 20${tsport}2
 