FORMAT: 1A
HOST: http://<serveur>
REFERENCE: **SRV_APPFACTORYSERVLET**

# AppFactoryServlet
Le JAR *AppFactoryServlet* constitue une interface entre la partie front-end de l'AppFactory et sa partie back-end générique.
Il est situé entre l'interface graphique générée par le builder, et les services REST métier du back-end générique.

Cette interface est référencée sous l'identifiant **SRV_APPFACTORYSERVLET**.

## Authentification
Le SessionID du Logon sera utilisé pour créer une session dans AppFactoryServlet, qui contiendra diverses informations concernant l'usager, et notamment son ID.
Le but de cette session est que le front-end puisse appeler les services sans rappeler à chaque fois à AppFactoryServlet qui est l'usager connecté.
Pour cela, le client doit mentionner le JSESSIONID de la session en tant que Cookie dans la requête.

## User-Agent
Afin d'auditer l'usage de l'*API AppFactoryServlet* il est demandé de renseigner dans le header HTTP User-Agent les information suivantes:

    User-Agent: NomDuLogiciel/Version
    
## Dates
Toutes les dates sont formatées selon la norme [RFC 3339](http://tools.ietf.org/html/rfc3339#section-5.6).

L'*API CGD* utilise les trois formats suivants:
- date-fullyear: **2014**
- full-date:  **2014-01-01**
- date-time: **2014-01-01T09:00:00+01:00**

## Content-Type
L'API utilise le format [JSON](http://www.json.org/) avec un charset **UTF-8** pour représenter l'état des ressources.


## Codes HTTP
Les codes de réponses HTTP standards sont utilisés. On utilise particulièrement les codes suivants:
- `200` **OK** code de succès sur les GET et les PUT.
- `201` **Created** code de succès sur les POST.
- `204` **No Content** code de succès sur un DELETE et ne retourne aucun contenu.
- `304` **Not Modified** Document non modifié depuis la dernière requête. Certaines Ressources/méthodes de l'API permettent la gestion de cache via les HTTP-Headers standards 'Request:If-None-Match' et 'Response:ETag' (cf. http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html).
- `400` **Bad Request** la requête n'est pas valide. Consulter l'attribut message du body de la requête pour plus de détails.
- `401` **Unauthorized** la requête n'est pas authentifiée avec HTTP Basic Auth.
- `403` **Forbidden** l'utilisateur n'est pas autorisé à faire cette action.
- `404` **Not Found** la ressource n'existe pas.

## Erreurs
Dans l'éventualité d'une erreur, en plus du status HTTP, l'API retourne un ou plusieurs messages d'erreurs `errors` au format JSON avec l'attribut suivant :
- `libelle` (obligatoire) - décrivant le problème.

Exemple :

        {
            "errors": [
                {
                    "libelle": "Le container spécifié n'existe pas"
                }
            ]
        }

# Group Login et Session AppFactoryServlet
*AppFactoryServlet* permet de créer une session interne à partir du SessionID retourné par l'étape de login auprès de l'application Logon.
Cette session stockera les informations de l'usager, retournées par le service externe /login/rest/loggedUsagers/ au format JSON.

## Login [/appfactoryservlet/login?id={id}]

Appelle le service externe /login/rest/loggedUsagers/ et enregistre dans une nouvelle session le JSON retourné.

Voici le JSON qui sera stocké dans la session :

- `adresse1`: 15 allée des palmiers (string, required) - Adresse de l'usager
- `adresse2`: Adresse 2 (string, not required) - Adresse 2 de l'usager
- `complementAdresse`: Complément d'adresse (string, not required) - Complément d'adresse
- `raisonSociale`: Raison sociale (string, not required) - Raison sociale
- `codePostal`: 06000 (string, required) - Code postal de l'usager
- `dateActivation`: 2016-01-25T09:29:08.329+01:00 (string, required) - Date d'activation du compte de l'usager
- `dateCreation`: 2016-01-25T09:29:08.329+01:00 (string, required) - Date de création du compte de l'usager
- `dateDerConnexion`: 2016-01-25T09:29:08.329+01:00 (string, required) - Date de dernière connexion de l'usager
- `email`: qdeme.ext@gouv.mc (string, required) - Adresse email de l'usager
- `etat`: 10 (string, required) - Entier représentant l'état du compte de l'usager
- `id`: 3071 (string, required) - Identifiant de l'usager
- `login`: qdeme (string, required) - Login de l'usager
- `nom`: Demé (string, required) - Nom de l'usager
- `nomPays`: France (string, required) - Pays de l'usager
- `prenom`: Quentin (string, required) - Prénom de l'usager
- `titre`: 0 (string, required) - Titre de l'usager
- `ville`: Nice (string, required) - Ville de l'usager

+ Parameters
    + id (required, string, `ojss26rcr910yq3f6an6ot2u`) ... L'id de la session retournée après l'authentification sur Logon


### Login [POST]

+ Request
    + Headers

            User-Agent: NomDuLogiciel/Version
            Cookie: JSESSIONID=1jyzh76rqbx66q2cxa0j0zvaf


+ Response 200


+ Response 404 (application/json)

### Logout [DELETE]

Effectue un logout

+ Request
    + Headers

            User-Agent: NomDuLogiciel/Version
            Cookie: JSESSIONID=1jyzh76rqbx66q2cxa0j0zvaf


+ Response 204


+ Response 404 (application/json)

## Sessions [/appfactoryservlet/sessions]

Retourne le contenu de la session stockée dans AppFactoryServlet.

Voici le JSON qui est stocké dans la session :

- `adresse1`: 15 allée des palmiers (string, required) - Adresse de l'usager
- `codePostal`: 06000 (string, required) - Code postal de l'usager
- `dateActivation`: 2016-01-25T09:29:08.329+01:00 (string, required) - Date d'activation du compte de l'usager
- `dateCreation`: 2016-01-25T09:15:25.057+01:00 (string, required) - Date de création du compte de l'usager
- `dateDerConnexion`: 2016-02-03T14:40:03.751+01:00 (string, required) - Date de dernière connexion de l'usager
- `email`: qdeme.ext@gouv.mc (string, required) - Adresse email de l'usager
- `etat`: 10 (string, required) - Entier représentant l'état du compte de l'usager
- `id`: 3071 (string, required) - Identifiant de l'usager
- `login`: qdeme (string, required) - Login de l'usager
- `nom`: Demé (string, required) - Nom de l'usager
- `nomPays`: France (string, required) - Pays de l'usager
- `prenom`: Quentin (string, required) - Prénom de l'usager
- `titre`: 0 (string, required) - Titre de l'usager
- `ville`: Nice (string, required) - Ville de l'usager


### Récupérer [GET]

+ Request
    + Headers

            User-Agent: NomDuLogiciel/Version
            Cookie: JSESSIONID=1jyzh76rqbx66q2cxa0j0zvaf


+ Response 200 (application/json)

        {
          "adresse1": "15 allée des palmiers",
          "codePostal": "06000",
          "dateActivation": "2016-01-25T09:29:08.329+01:00",
          "dateCreation": "2016-01-25T09:15:25.057+01:00",
          "dateDerConnexion": "2016-02-03T14:40:03.751+01:00",
          "email": "qdeme.ext@gouv.mc",
          "etat": "10",
          "id": "3071",
          "login": "qdeme",
          "nom": "Demé",
          "nomPays": "France",
          "prenom": "Quentin",
          "titre": "0",
          "ville": "Nice"
        }

+ Response 404

# Group Accès à la démarche et désinscription
*AppFactoryServlet* permet de créer un accès d'un usager à une démarche et de le désinscrire d'une démarche.

## Accès [/appfactoryservlet/accesses]

Permet l'accès au back-end générique qui enregistre en base de données l'accès d'un usager à une démarche particulière.
Le JSON custom inséré en base est retourné dans l'attribut "contenu" de la réponse.
Les DemarcheID et UsagerID (récupérés de la session) sont envoyés par AppFactoryServlet au back-end générique de manière transparente.
Il n'y a donc aucun paramètre à donner à ce service, si ce n'est le JSON.

### Créer ou mettre à jour [POST]

+ Request
    + Headers

            User-Agent: NomDuLogiciel/Version
            Cookie: JSESSIONID=1jyzh76rqbx66q2cxa0j0zvaf

    + Body

            {
                "contenu" : {
                    "donnee1" : "Donnée custom 1",
                    "donnee2" : "Donnée custom 2"
                }
            }

+ Response 201 (application/json)

        {
          "pkAccess": 14,
          "demarcheId": "embauchage-personnel-maison",
          "usagerId": 3071,
          "dateCreation": "2016-01-25T09:29:08.329+01:00",
          "dateDerModif": "2016-01-25T09:29:08.329+01:00",
          "contenu": {
                "donnee1" : "Donnée custom 1",
                "donnee2" : "Donnée custom 2"
          }
        }

+ Response 400 (application/json)

+ Response 401 

### Récupérer [GET]

+ Request
    + Headers

            User-Agent: NomDuLogiciel/Version
            Cookie: JSESSIONID=1jyzh76rqbx66q2cxa0j0zvaf


+ Response 200 (application/json)

        {
          "pkAccess": 14,
          "demarcheId": "embauchage-personnel-maison",
          "usagerId": 3071,
          "dateCreation": "2016-01-25T09:29:08.329+01:00",
          "dateDerModif": "2016-01-25T09:29:08.329+01:00",
          "contenu": {
                "donnee1" : "Donnée custom 1",
                "donnee2" : "Donnée custom 2"
          }
        }

+ Response 404 (application/json)

        {
          "errors": [
            {
              "libelle": "Accès introuvable"
            }
          ]
        }

+ Response 401 

## Supprimer un accès [/appfactoryservlet/accesses?hashedPassword={hashedPassword}]

+ Parameters
    + hashedPassword (required, string, `bccc46ab40cc6b2f0454623bb7623ed58984345a`) ... Le mot de passe haché

### Supprimer [DELETE]

Afin de supprimer un accès, il est nécessaire de fournir le mot de passe encrypté en SHA1.

+ Request
    + Headers

            User-Agent: NomDuLogiciel/Version
            Cookie: JSESSIONID=1jyzh76rqbx66q2cxa0j0zvaf

+ Response 200 (application/json)

+ Response 401 

        {
          "errors": [
            {
              "libelle": "Mot de passe invalide"
            }
          ]
        }

+ Response 404 (application/json)

        {
          "errors": [
            {
              "libelle": "Accès introuvable"
            }
          ]
        }

# Group Gestion des demandes
*AppFactoryServlet* permet de créer des demandes pour un usager et une démarche particulière.

## Créer et récupérer [/appfactoryservlet/demandes]

Permet l'accès au back-end générique qui enregistre en base de données une demande d'un usager sur une démarche particulière.
Le JSON custom inséré en base est retourné dans l'attribut "contenu" de la réponse.
Les DemarcheID et UsagerID (récupérés de la session) sont envoyés par AppFactoryServlet au back-end générique de manière transparente.

Note : si l'on a uploadé des pièces jointes avant création de la demande, alors il faut spécifier lors de la création de la demande le ou les fichiers qui ont été précédemment uploadés en utilisant ce qui suit dans le bloc "fichiers".
Sachant que le format de l'URL est à construire comme suit : /{uuid}/{filename}.
{uuid}/{filename} étant généré et retourné par le service d'upload de fichiers.

            {
                "contenu" : {
                	"donneeCustom1" : "valeurCustom1",
                	"donneeCustom2" : [
                	    {
                		"donneeCustom3" : "valeurCustom3",
                		"donneeCustom4" : "valeurCustom4"
                	    }
                	]
                },
            	"fichiers" : [
            		{
	                    "name" : "CV.pdf",
	                    "url" : "/ece7a75e-e5f9-11e5-a7a3-08002700c066/CV.pdf",
	                    "meta" : "meta1"
	                },
	                {
	                    "name" : "lettremotivation.doc",
	                    "url" : "/ada9b78b-a43f-11e5-a7a3-08002700c066/lettremotivation.doc",
	                    "meta" : "meta2"
	                }
	            ],
	            "langue" : "IT",
	            "canal" : "GUICHET"
            }

### Créer [POST]

+ Request
    + Headers

            User-Agent: NomDuLogiciel/Version
            Cookie: JSESSIONID=1jyzh76rqbx66q2cxa0j0zvaf

    + Body

			{
				"contenu" : {
					"donneeCustom1" : "valeurCustom1",
					"donneeCustom2" : [
					    {
						"donneeCustom3" : "valeurCustom3",
						"donneeCustom4" : "valeurCustom4"
					    }
					]
				},
				"fichiers" : [
					{
				        "name" : "CV.pdf",
				        "url" : "/ece7a75e-e5f9-11e5-a7a3-08002700c066/CV.pdf",
				        "meta" : "meta1"
				    },
				    {
				        "name" : "lettremotivation.doc",
				        "url" : "/ada9b78b-a43f-11e5-a7a3-08002700c066/lettremotivation.doc",
				        "meta" : "meta2"
				    }
				],
	            "langue" : "IT",
	            "canal" : "GUICHET"
			}

+ Response 201 (application/json)

			{
			  "pkDemandes": 50,
			  "dateCreation": "2016-10-17T08:58:14.417+01:00",
			  "dateDerModif": "2016-10-17T08:58:14.417+01:00",
			  "contenu": {
			    "donneeCustom1": "valeurCustom1",
			    "donneeCustom2": [
			      {
			        "donneeCustom3": "valeurCustom3",
			        "donneeCustom4": "valeurCustom4"
			      }
			    ]
			  },
			  "demarcheId": "HAB",
			  "usagerId": 3071,
			  "complements": null,
			  "fichiers": [
			    {
			      "name": "lettremotivation.doc",
			      "url": "/ada9b78b-a43f-11e5-a7a3-08002700c066/lettremotivation.doc",
			      "meta": "meta2"
			    },
			    {
			      "name": "CV.pdf",
			      "url": "/ece7a75e-e5f9-11e5-a7a3-08002700c066/CV.pdf",
			      "meta": "meta1"
			    }
			  ],
			  "statuts": [
			    {
			      "pkStatut": 131,
			      "libelle": "EN_ATTENTE_TRAIT",
			      "date": "2016-10-17T08:58:14.494+01:00",
			      "agentId": null,
			      "usagerId": 3071,
			      "codeMotif": null,
			      "commentaire": null
			    }
			  ],
			  "langue": "IT",
			  "canal": "GUICHET",
			  "observations": null,
			  "agentAffecteId": null,
			  "dernierStatut": {
			    "pkStatut": 131,
			    "libelle": "EN_ATTENTE_TRAIT",
			    "date": "2016-10-17T08:58:14.494+01:00",
			    "agentId": null,
			    "usagerId": 3071,
			    "codeMotif": null,
			    "commentaire": null
			  },
			  "identifiant": "HAB-20161017-s33l"
			}

+ Response 404 (application/json)

        {
          "errors": [
            {
              "libelle": "Erreur: Accès correspondant introuvable"
            }
          ]
        }

+ Response 401

### Récupérer [GET]

Récupérer toutes les demandes de l'usager connecté pour cette démarche.

+ Request
        
    + Headers

            User-Agent: NomDuLogiciel/Version
            Cookie: JSESSIONID=1jyzh76rqbx66q2cxa0j0zvaf


+ Response 200 (application/json)

		[
		  {
		    "pkDemandes": 13,
		    "dateCreation": "2016-05-17T08:05:04.654+01:00",
		    "dateDerModif": "2016-05-17T08:05:04.654+01:00",
		    "contenu": {
		      "donneeCustom1": "valeurCustom1",
		      "donneeCustom2": [
		        {
		          "donneeCustom3": "valeurCustom3",
		          "donneeCustom4": "valeurCustom4"
		        }
		      ]
		    },
		    "demarcheId": "embauchage-personnel-maison",
		    "usagerId": 3071,
		    "complements": null,
		    "fichiers": [
		      {
		        "name": "lettremotivation.doc",
		        "url": "/ada9b78b-a43f-11e5-a7a3-08002700c066/lettremotivation.doc",
		        "meta": "meta2"
		      },
		      {
		        "name": "CV.pdf",
		        "url": "/ece7a75e-e5f9-11e5-a7a3-08002700c066/CV.pdf",
		        "meta": "meta1"
		      }
		    ],
		    "statuts": [
		      {
		        "pkStatut": 8,
		        "libelle": "EN_ATTENTE",
		        "date": "2016-05-17T08:05:04.662+01:00",
		        "agentId": null,
		        "usagerId": 3071
		      }
		    ]
		  }
		]

+ Response 404 (application/json)

        {
          "errors": [
            {
              "libelle": "Erreur: Accès correspondant introuvable"
            }
          ]
        }

+ Response 401

## Récupérer, mettre à jour, et supprimer [/appfactoryservlet/demandes/{demandeId}]

+ Parameters
    + demandeId (optional, integer, `15`) ... L'id de la demande à mettre à jour, récupérer ou supprimer.

### Récupérer [GET]

Permet de récupérer une demande spécifique.

+ Request
        
    + Headers

            User-Agent: NomDuLogiciel/Version
            Cookie: JSESSIONID=1jyzh76rqbx66q2cxa0j0zvaf


+ Response 200 (application/json)

		{
		  "pkDemandes": 13,
		  "dateCreation": "2016-05-17T08:05:04.654+01:00",
		  "dateDerModif": "2016-05-17T08:05:04.654+01:00",
		  "contenu": {
		    "donneeCustom1": "valeurCustom1",
		    "donneeCustom2": [
		      {
		        "donneeCustom3": "valeurCustom3",
		        "donneeCustom4": "valeurCustom4"
		      }
		    ]
		  },
		  "demarcheId": "embauchage-personnel-maison",
		  "usagerId": 3071,
		  "complements": null,
		  "fichiers": [
		    {
		      "name": "lettremotivation.doc",
		      "url": "/ada9b78b-a43f-11e5-a7a3-08002700c066/lettremotivation.doc",
		      "meta": "meta2"
		    },
		    {
		      "name": "CV.pdf",
		      "url": "/ece7a75e-e5f9-11e5-a7a3-08002700c066/CV.pdf",
		      "meta": "meta1"
		    }
		  ],
		  "statuts": [
		    {
		      "pkStatut": 8,
		      "libelle": "EN_ATTENTE",
		      "date": "2016-05-17T08:05:04.662+01:00",
		      "agentId": null,
		      "usagerId": 3071
		    }
		  ]
		}

+ Response 404 (application/json)

        {
          "errors": [
            {
              "libelle": "Erreur: Accès correspondant introuvable"
            }
          ]
        }

+ Response 401 

### Mettre à jour [POST]

Met à jour une demande particulière (contenu et fichiers).

+ Request
    
    + Headers

            User-Agent: NomDuLogiciel/Version
            Cookie: JSESSIONID=1jyzh76rqbx66q2cxa0j0zvaf

    + Body

			{
				"contenu" : {
					"donneeCustom5" : "valeurCustom5"
				},
				"fichiers" : [
					{
				        "name" : "CV2.pdf",
				        "url" : "/ece7a75e-e5f9-11e5-a7a3-08002700c066/CV2.pdf",
				        "meta" : "meta2"
				    }
				]
			}

+ Response 200 (application/json)

		{
		  "pkDemandes": 13,
		  "dateCreation": "2016-05-17T08:05:04.654+01:00",
		  "dateDerModif": "2016-05-17T08:08:25.382+01:00",
		  "contenu": {
		    "donneeCustom5": "valeurCustom5"
		  },
		  "demarcheId": "embauchage-personnel-maison",
		  "usagerId": 3071,
		  "complements": null,
		  "fichiers": [
		    {
		      "name": "CV2.pdf",
		      "url": "/ece7a75e-e5f9-11e5-a7a3-08002700c066/CV2.pdf",
		      "meta": "meta2"
		    }
		  ],
		  "statuts": [
		    {
		      "pkStatut": 8,
		      "libelle": "EN_ATTENTE",
		      "date": "2016-05-17T08:05:04.662+01:00",
		      "agentId": null,
		      "usagerId": 3071
		    }
		  ]
		}

+ Response 404 (application/json)

        {
          "errors": [
            {
              "libelle": "Erreur: Demande introuvable"
            }
          ]
        }

+ Response 401 

### Supprimer [DELETE]

Supprime une demande.

+ Request
        
    + Headers

            User-Agent: NomDuLogiciel/Version
            Cookie: JSESSIONID=1jyzh76rqbx66q2cxa0j0zvaf


+ Response 200 (application/json)

+ Response 404 (application/json)

        {
          "errors": [
            {
              "libelle": "Erreur: Demande introuvable"
            }
          ]
        }
 
+ Response 401

# Group Gestion des demandes d'informations complémentaires
*AppFactoryServlet* permet de récupérer des demandes d'informations complémentaires par rapport à des demandes préexistantes, et d'y répondre.

## Récupérer demandes d'informations complémentaires [/appfactoryservlet/demandes/{demandeId}/complements]

+ Parameters
    + demandeId (required, integer, `13`) ... L'identifiant de la demande concernée.
        
### Récupérer les demandes d'informations complémentaires d'une demande [GET]

Permet de récupérer toutes les demandes d'informations complémentaires concernant une demande.

+ Request
        
    + Headers
    
            User-Agent: NomDuLogiciel/Version
            Cookie: JSESSIONID=1jyzh76rqbx66q2cxa0j0zvaf


+ Response 200 (application/json)

			[
			  {
			    "pkDemandeComplements": 13,
			    "demandeId": 13,
			    "statut": "EN_ATTENTE",
			    "question": {
			      "motif": "Motif de test",
			      "date": "2016-05-17T13:02:37.535+01:00",
			      "agentId": "agentid0"
			    },
			    "reponse": null
			  }
			]

+ Response 404 (application/json)

        {
          "errors": [
            {
              "libelle": "Erreur: Demande associée introuvable"
            }
          ]
        }

+ Response 401

## Récupérer ou répondre [/appfactoryservlet/demandes/{demandeId}/complements/{demandeIcId}]

+ Parameters
    + demandeId (required, integer, `15`) ... L'id de la demande concernée.
	+ demandeIcId (required, integer, `15`) ... L'id de la demande d'informations complémentaires à mettre à jour ou supprimer.

### Récupérer une demande d'informations complémentaires [GET]

Récupérer une demande d'informations complémentaires précise.

+ Request
        
    + Headers
    
            User-Agent: NomDuLogiciel/Version
            Cookie: JSESSIONID=1jyzh76rqbx66q2cxa0j0zvaf


+ Response 200 (application/json)

		{
		  "pkDemandeComplements": 13,
		  "demandeId": 13,
		  "statut": "EN_ATTENTE",
		  "question": {
		    "motif": "Motif de test 3",
		    "date": "2016-05-17T13:02:37.535+01:00",
		    "agentId": "agentid0"
		  },
		  "reponse": null
		}

+ Response 404 (application/json)

        {
          "errors": [
            {
              "libelle": "Erreur: Demande d'informations complémentaires introuvable"
            }
          ]
        }

+ Response 401

### Répondre [PUT]

Permet de répondre à une demande d'informations complémentaires.
Une réponse comporte éventuellement des liens vers des fichiers précédemment uploadés dans FILE.

+ Request
    
    + Headers
    
            User-Agent: NomDuLogiciel/Version
            Cookie: JSESSIONID=1jyzh76rqbx66q2cxa0j0zvaf

    + Body

			{
			    "texte" : "La réponse",
			    "fichiers" : [
			            {
			                "name" : "nom1",
			                "url" : "url1",
			                "meta" : "meta1"
			            },
			            {
			                "name" : "nom2",
			                "url" : "url2",
			                "meta" : "meta2"
			            }
			        ],
			    "usagerId" : 3071
			}

+ Response 200 (application/json)

			{
			  "pkDemandeComplements": 13,
			  "demandeId": 13,
			  "statut": "REPONDUE",
			  "question": {
			    "motif": "Motif de test 2",
			    "date": "2016-05-17T13:02:37.535+01:00",
			    "agentId": "agentId2"
			  },
			  "reponse": {
			    "texte": "La réponse",
			    "date": "2016-05-17T13:15:04.872+01:00",
			    "usagerId": 3071,
			    "fichiers": [
			      {
			        "name": "nom2",
			        "url": "url2",
			        "meta": "meta2"
			      },
			      {
			        "name": "nom1",
			        "url": "url1",
			        "meta": "meta1"
			      }
			    ]
			  }
			}

+ Response 404 (application/json)

        {
          "errors": [
            {
              "libelle": "Erreur: Demande d'informations complémentaires introuvable"
            }
          ]
        }

+ Response 401 

# Group Référentiel pays et nationalité

## Référentiel pays et nationalité [/appfactoryservlet/pays]

AppFactoryServlet met à disposition en tant que proxy le service de référentiel pays et nationalité.

Se référer à la documentation de l'API référencée sous l'identifiant **REF_PAYS**.

# Group Contact
*AppFactoryServlet* expose un service faisant permettant d'envoyer un email de contact et de vérifier le Captcha via appel à l'API reCAPTCHA.

## Contact [/appfactoryservlet/contact]

Appelle l'API reCAPTCHA pour vérifier le Captcha.

Les 4 champs suivants doivent être fournis au service en x-www-form-urlencoded:

    - captcha (recaptcha_127.0.0.1_challenge_response)  Le token comprenant l'IP du client, le challenge (ID du test à vérifier, généré par Google), et la réponse de l'utilisateur au challenge
    - email (utilisateur@google.com) L'adresse email entrée dans le formulaire
    - titre (Question sur la démarche) Le titre entré dans le formulaire
    - message (Bonjour, j'aurais une question à vous poser) Le message entré dans le formulaire


### Contact [POST]

+ Request (application/x-www-form-urlencoded)
    + Headers

            User-Agent: NomDuLogiciel/Version
            
	+ Body
			
			captcha=recaptcha_127.0.0.1_challenge_response&email=utilisateur%40google.com&titre=Question+sur+la+d%C3%A9marche&message=Bonjour%2C%20j%27aurais%20une%20question%20%C3%A0%20vous%20poser


+ Response 200

+ Response 403

+ Response 401 

# Group Pièces jointes
*AppFactoryServlet* expose des services de stockage et de récupération de pièces jointes

## Stockage de pièce jointe [/appfactoryservlet/fileupload/{filename}]

Appelle l'API FILE afin de stocker une pièce jointe. Le fichier est à envoyer dans un appel multipart/form-data.
La réponse contient l'identifiant du fichier au format uuid/filename.

+ Parameters
    + filename (required, string, `CV.pdf`) ... Le nom du fichier à envoyer


### Stocker [POST]

Il est possible d'indiquer le demandeId (si on le connait déjà) de la demande liée à ces fichiers en utilisant le header X-MC-DEMANDEID.

+ Request
    + Headers

            User-Agent: NomDuLogiciel/Version
            Cookie: JSESSIONID=1jyzh76rqbx66q2cxa0j0zvaf
            Content-Type: multipart/form-data; boundary=---011000010111000001101001
            X-MC-DEMANDEID: 68


+ Response 201 (application/json)

        {
          "fileId" : "c6152835-e539-11e5-9d2a-08002700c066/CV.pdf"
        }

+ Response 404

+ Response 401 

## Récupération de pièce jointe [/appfactoryservlet/filedownload/{uuid}/{filename}]

Appelle l'API FILE afin de stocker une pièce jointe. Le fichier est à envoyer dans un appel multipart/form-data.
La réponse contient l'identifiant du fichier au format uuid/filename.

+ Parameters
	+ uuid (required, string, `cb14459c-e53c-11e5-8a2a-08002700c066`) ... L'UUID du fichier, retourné par le service **fileupload**
    + filename (required, string, `CV.pdf`) ... Le nom du fichier à envoyer


### Récupérer [GET]

+ Request
    + Headers

            User-Agent: NomDuLogiciel/Version
            Cookie: JSESSIONID=1jyzh76rqbx66q2cxa0j0zvaf
            Content-Disposition: attachment;filename=fichier.pdf
            Content-Type: application/pdf

+ Response 200 (application/json)

+ Response 404

+ Response 401 


# Group Motifs liés à une démarche
*AppFactoryServlet* permet de récupérer tous les motifs liés à une démarche, dans toutes les langues.

## Motifs [/appfactoryservlet/motifs]

### Récupérer [GET]

+ Request
    + Headers

            User-Agent: NomDuLogiciel/Version
            Cookie: JSESSIONID=1jyzh76rqbx66q2cxa0j0zvaf


+ Response 200 (application/json)

        [
          {
            "pkMotifs": 1,
            "demarcheId": "HAB",
            "code": "PAS_MONEGASQUE",
            "libelle": "Il faut être de nationalité monégasque",
            "statut": "REFUSEE",
            "langue": "FR"
          },
          {
            "pkMotifs": 2,
            "demarcheId": "HAB",
            "code": "PAS_MONEGASQUE",
            "libelle": "You have to be Monegasque",
            "statut": "REFUSEE",
            "langue": "EN"
          }
        ]

+ Response 404 (application/json)

        {
          "errors": [
            {
              "libelle": "Erreur: La démarche spécifiée est introuvable"
            }
          ]
        }
+ Response 401 