---
ansible_user: ansible
ansible_become: True
ansible_become_method: sudo
proxy_env:
#  http_proxy: http://proxy-infra:3129
#  https_proxy: http://proxy-infra:3129
#  no_proxy: linuxic,localhost,127.0.0.1

elasticsearch_cluster_name: ${tscode}

mc_env: prod
mc_env_color: "#EF5350"

mc_fs_installed: false

batch_user: batch
batch_group: batch

mc_batch_host: linuxbatch
mc_batch_private_key: /www/mc_lib/id_dsa

nfsshared_group: nfsshared 
nfsnobody_user: nfsnobody


mc_http_proxy_host: proxy-infra
mc_http_proxy_port: 3129
mc_http_non_proxy_hosts: linuxas-1

mc_mail_host: 127.0.0.1
mc_mail_port: 25

mc_module_maven_repositort_url: http://linuxic/nexus/content/groups/public/

mc_module_types:
  - backserver
  - frontserver
  - apiserver
