application.module=frontserver
server.port=${front.port}
# Server
server.servlet.context-path=${front.context}

mc.gouv.appli.frontserver.url=http://localhost:${front.port}${server.servlet.context-path}
mc.gouv.appli.frontserver.api.url=http://localhost:${api.port}/${application.name}/api/v1
mc.gouv.appli.frontserver.back.url=http://localhost:${back.port}/${application.name}
# Proprietes utilisees par le FO
mc.gouv.appfactory.servicepublic.particulier.url.fr=https://monservicepublic.gouv.mc
mc.gouv.appfactory.servicepublic.particulier.url.en=https://monservicepublic.gouv.mc/en
mc.gouv.appfactory.servicepublic.entreprise.url.fr=https://monentreprise.gouv.mc
mc.gouv.appfactory.servicepublic.entreprise.url.en=https://monentreprise.gouv.mc/en
mc.gouv.appfactory.cookies.particulier.url.fr=https://monservicepublic.gouv.mc/cookies-teleservices
mc.gouv.appfactory.cookies.particulier.url.en=https://monservicepublic.gouv.mc/en/cookies-teleservices
mc.gouv.appfactory.cookies.entreprise.url.fr=https://monentreprise.gouv.mc/cookies-teleservices
mc.gouv.appfactory.cookies.entreprise.url.en=https://monentreprise.gouv.mc/en/cookies-teleservices
mc.gouv.appfactory.mconnect.help.url.fr=https://mconnect.gouv.mc/aide
mc.gouv.appfactory.mconnect.help.url.en=https://mconnect.gouv.mc/en/help2
mc.gouv.appfactory.support.url.fr=https://contacts.gouv.mc/contactez-un-service-de-l-administration?localisation=251223&contact=251222
mc.gouv.appfactory.support.url.en=https://contacts.gouv.mc/en/contactez-un-service-de-l-administration?localisation=251223&contact=251222
mc.gouv.appfactory.compte.particulier.url.fr=https://monservicepublic.gouv.mc/thematiques/relations-avec-l-administration/monguichet.mc/se-connecter-a-un-teleservice-particulier-avec-monguichet.mc
mc.gouv.appfactory.compte.particulier.url.en=https://monservicepublic.gouv.mc/en/themes/you-and-the-government-services/monguichet.mc/how-to-log-in-to-an-online-service-using-monguichet.mc
mc.gouv.appfactory.compte.entreprise.url.fr=https://monentreprise.gouv.mc/thematiques/numerique/monguichet.mc/se-connecter-a-un-teleservice-entreprises-avec-monguichet.mc
mc.gouv.appfactory.compte.entreprise.url.en=https://monentreprise.gouv.mc/en/themes/digital/monguichet.mc/how-to-log-in-to-an-online-service-for-businesses-using-monguichet.mc
mc.gouv.appfactory.monguichet.cgu.url.fr=https://monguichet.mc/conditions-generales-d-utilisation
mc.gouv.appfactory.monguichet.cgu.url.en=https://monguichet.mc/en/terms-of-use
mc.gouv.gichuni.pub.mconnect.url.fr=${mc.gouv.gichuni.front.url}/utiliser-mconnect?dest=${mc.gouv.appli.frontserver.url}/menu.html
mc.gouv.gichuni.pub.mconnect.url.en=${mc.gouv.gichuni.front.url}/en/use-mconnect?dest=${mc.gouv.appli.frontserver.url}/menu.html
mc.gouv.gichuni.demarche.particulier.url.fr=${mc.gouv.gichuni.front.url}/particuliers/mes-demarches
mc.gouv.gichuni.demarche.particulier.url.en=${mc.gouv.gichuni.front.url}/en/particuliers/my-services
mc.gouv.gichuni.demarche.entreprise.url.fr=${mc.gouv.gichuni.front.url}/entreprises/mes-demarches
mc.gouv.gichuni.demarche.entreprise.url.en=${mc.gouv.gichuni.front.url}/en/entreprises/my-services
mc.gouv.gichuni.profil.particulier.url.fr=${mc.gouv.gichuni.front.url}/particuliers/profil
mc.gouv.gichuni.profil.particulier.url.en=${mc.gouv.gichuni.front.url}/en/particuliers/profil
mc.gouv.gichuni.profil.entreprise.url.fr=${mc.gouv.gichuni.front.url}/entreprises/profil
mc.gouv.gichuni.profil.entreprise.url.en=${mc.gouv.gichuni.front.url}/en/entreprises/profil
mc.gouv.appli.frontserver.matomo.site_id=0
mc.gouv.appli.frontserver.copyright.years=0000

# Demandes courrier
mc.gouv.appli.frontserver.redirectToBo.url=${mc.gouv.appli.frontserver.back.url}/demandes/<id>?origin=fo

# MonGuichet
mc.gouv.appli.frontserver.gichkey.keycloak.redirect.uri=${mc.gouv.appli.frontserver.url}/acces_teleservice.html
mc.gouv.appli.frontserver.gichkey.redirect.url=${mc.gouv.gichuni.front.url}/auth/realms/gichuni/protocol/openid-connect/auth?client_id=${mc.gouv.appli.frontserver.gichkey.client_id}&response_type=code&redirect_uri=${mc.gouv.appli.frontserver.gichkey.keycloak.redirect.uri}

# File
# Pour la prod/rec, 200 fichiers max / 24h. En dev/local 10 fichiers / seconde
mc.gouv.frontserver.max.upload.intervalle=10
mc.gouv.frontserver.temps.upload.intervalle=1000

# Front
mc.gouv.appli.frontserver.jwt=${APPLI_FRONT_JWT}
# File
mc.gouv.appli.frontserver.file.jwt=${APPLI_FRONT_FILE_JWT}
# Vscan
mc.gouv.appli.frontserver.vscan.jwt=${APPLI_FRONT_VSCAN_JWT}
# Tgf
mc.gouv.appli.frontserver.tgf.jwt=${APPLI_FRONT_TGF_JWT}
# MonGuichet
mc.gouv.appli.frontserver.gichkey.client_secret=${APPLI_FRONT_GICHUNI_CLIENT_SECRET}
# Security
mc.gouv.appli.frontserver.key=${APPLI_FRONT_KEY}
