---
tcp_checks:
  - name: zabbix-agent
    host: ${tscode}-appl1-0
    port: 10050
  - name: ${tscode}-backserver-jmx
    host: ${tscode}-appl1-0
    port: 10${TSPORT}1
  - name: ${tscode}-backserver-rmi
    host: ${tscode}-appl1-0
    port: 10${TSPORT}2
  - name: ${tscode}-apiserver-jmx
    host: ${tscode}-appl1-0
    port: 30${TSPORT}1
  - name: ${tscode}-apiserver-rmi
    host: ${tscode}-appl1-0
    port: 30${TSPORT}2
    