<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>mc.gouv.xboot</groupId>
		<artifactId>xboot-spring-starter-parent</artifactId>
		<version>3.1.0</version>
	</parent>

	<properties>
		<servicerest_client.version>2.2.15</servicerest_client.version>
		<tika.version>1.18</tika.version>
		<itext.pdf.version>2.1.4</itext.pdf.version>
	</properties>

	<groupId>mc.gouv.xaf</groupId>
	<artifactId>xaf</artifactId>
	<version>7.0.0-SNAPSHOT</version>
	<packaging>pom</packaging>

	<scm>
        <url>https://git.monaco-gouvernement.mc/libs/xaf.git</url>
        <connection>scm:git:git@git.monaco-gouvernement.mc:libs/xaf.git</connection>
        <developerConnection>scm:git:git@git.monaco-gouvernement.mc:libs/xaf.git</developerConnection>
        <tag>HEAD</tag>
    </scm>


	<modules>
		<module>xaf-servlet</module>
		<module>xaf-back</module>
		<module>xaf-apiclient</module>
		<module>xaf-backweb</module>
		<module>xaf-archetype</module>
        <module>xaf-shared</module>
    </modules>

	<!-- All add-ons and iText 7 core -->
	<repositories>
		<repository>
			<id>itext</id>
			<name>iText Repository - releases</name>
			<url>https://repo.itextsupport.com/releases</url>
		</repository>
	</repositories>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-elasticsearch</artifactId>
		</dependency>

		<dependency>
			<groupId>org.elasticsearch.client</groupId>
			<artifactId>transport</artifactId>
		</dependency>

		<dependency>
			<groupId>org.elasticsearch.plugin</groupId>
			<artifactId>transport-netty4-client</artifactId>
		</dependency>
		<dependency>
			<groupId>net.java.dev.jna</groupId>
			<artifactId>jna</artifactId>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-compress</artifactId>
			<version>1.18</version>
		</dependency>

		<!-- itext -->
		<dependency>
			<groupId>com.itextpdf</groupId>
			<artifactId>html2pdf</artifactId>
			<version>${itext.pdf.version}</version>
		</dependency>
	</dependencies>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.apache.tika</groupId>
				<artifactId>tika-app</artifactId>
				<version>${tika.version}</version>
				<exclusions>
					<exclusion>
						<groupId>org.apache.cxf</groupId>
						<artifactId>cxf-rt-rs-client</artifactId>
					</exclusion>
				</exclusions>
			</dependency>
		</dependencies>
	</dependencyManagement>
</project>