package mc.gouv.xaf.back.paiement.enums;

public enum PaiementDemandeDataKeysEnum {
    STATUT_PAIEMENT,
    DATE_PAIEMENT,
    DATE_EXPIRATION_EMPREINTE,
    NUMERO_FACTURE,
    NUMERO_PERMIS,
    MOYEN_PAIEMENT,
    MOYEN_PAIEMENT_REFERENCE,
    NOMBRE_FICHIERS_ERREUR_ARCHIVAGE
}
