#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
package ${groupId}.shared.enums;

/**
 * Identifie les code motifs utilisés dans l'application en "dur" pour des raisons métier
 * @author fgaujous
 *
 */
public enum ${artifactIdCamelCase}CodeMotifEnum {

    ANNULATION_PAR_ENTREPRISE("ANNULATION_PAR_ENTREPRISE"),
    ANNULATION_PAR_AGENT("ANNULATION_PAR_USAGER"),
    ANNULATION_DESINSCRIPTION("ANNULATION_DESINSCRIPTION"),
    VALIDATION_TOT_CHANTIER("VALIDATION_TOT_CHANTIER"),
    VALIDATION_TOT_HORS_CHANTIER("VALIDATION_TOT_HORS_CHANTIER"),
    VALIDATION_PARTIELLE_CHANTIER("VALIDATION_PARTIELLE_CHANTIER"),
    VALIDATION_PARTIELLE_HORS_CHANTIER("VALIDATION_PARTIELLE_HORS_CHANTIER"),
    PIECES_ILLISIBLES("PIECES_ILLISIBLES"),
    PIECES_MANQUANTE("PIECES_MANQUANTE"),
    ATTENTE_COMPL_AUTRE("ATTENTE_COMPL_AUTRE"),
    DEMANDE_SUP_3_MOIS_FR_HC("DEMANDE_SUP_3_MOIS_FR_HC"),
    DEMANDE_SUP_3_FR_MOIS("DEMANDE_SUP_3_FR_MOIS"),
    DEMANDE_SUP_3_IT_MOIS("DEMANDE_SUP_3_IT_MOIS"),
    DEMANDE_SUP_3_MOIS_IT_HC("DEMANDE_SUP_3_MOIS_IT_HC"),
    NATIONALITE_IT_REQUISE("NATIONALITE_IT_REQUISE"),
    DEMANDE_DOUBLE("DEMANDE_DOUBLE"),
    ${tsIdentifiantDemande}_NON_AUTORISE("${tsIdentifiantDemande}_NON_AUTORISE"),
    REFUSEE_AUTRE("REFUSEE_AUTRE");

    public String value;

    ${artifactIdCamelCase}CodeMotifEnum(String value) {
        this.value = value;
    }

}
