#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
package mc.gouv.${artifactIdLower}.shared.dto;

public enum ${artifactIdCamelCase}TemplateEnum {

	MAIL_CREATION_DEMANDE_USAGER_OBJET,
    MAIL_CREATION_DEMANDE_USAGER_CORPS,
    MAIL_CREATION_DEMANDE_AGENT_OBJET,
    MAIL_CREATION_DEMANDE_AGENT_CORPS,
    MAIL_ACTION_REFUSER_OBJET,
    MAIL_ACTION_REFUSER_CORPS,
    MAIL_ACTION_VALIDEE_EN_ATTENTE_PAIEMENT_OBJET,
    MAIL_ACTION_VALIDEE_EN_ATTENTE_PAIEMENT_CORPS,
    MAIL_ACTION_VALIDEE_ET_PAYEE_OBJET,
    MAIL_ACTION_VALIDEE_ET_PAYEE_CORPS,
    MAIL_ACTION_DEMANDEIC_OBJET,
    MAIL_ACTION_DEMANDEIC_CORPS,
    MAIL_CONFIRMATION_ACTION_ANNULER_OBJET,
    MAIL_CONFIRMATION_ACTION_ANNULER_CORPS,
    MAIL_NOTIFICATION_REPONSE_IC_PAR_USAGER_CORPS,
    MAIL_NOTIFICATION_REPONSE_IC_PAR_USAGER_OBJET,
    MAIL_NOTIFICATION_REPONSE_IC_PAR_AGENT_OBJET,
    MAIL_NOTIFICATION_REPONSE_IC_PAR_AGENT_CORPS,
    MAIL_NOTIFICATION_ATTENTE_VALIDATION_COMPTABLE_OBJET,
    MAIL_NOTIFICATION_ATTENTE_VALIDATION_COMPTABLE_CORPS,
    MAIL_DESINSCRIPTION_USAGER_OBJET,
    MAIL_DESINSCRIPTION_USAGER_CORPS,
    MAIL_DESINSCRIPTION_USAGER_POUR_USAGER_OBJET,
    MAIL_DESINSCRIPTION_USAGER_POUR_USAGER_CORPS
}
