#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
${symbol_pound} String jwt = createJWTToken("secret", "${artifactIdUpper}", new String[] { "USER" }, "FILE", null, null);
${groupId}.frontserver.file.jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJERVJKRkVSIiwiYXVkIjoiRklMRSIsImlhdCI6IjIwMTktMDgtMTNUMTY6NDE6NDkrMDIwMCIsImp0aSI6IjZhMDY4ZmY3LWM5ZDAtNGVkYi1iYjYxLTExNjVhNzVlMmE5MiIsImdvdXYiOnsic2hhcmVkIjp7InJvbGVzIjpbIlVTRVIiXX19fQ.xvtHZO7cGJUN5SFRPj8RZnwkL4ERrPKheBeu62eCF0w

${symbol_pound} TODO que faire ? cf. email à Rodolphe HEIGEL
mc.gouv.appfactory.${artifactIdLower}.front.copyright.years=2020

mc.gouv.appfactory.${artifactIdLower}.front.quitterTsUrl.fr=http://service-public-particuliers.gouv.mc/
mc.gouv.appfactory.${artifactIdLower}.front.ficheDemarcheUrl.fr=https://service-public-particuliers.gouv.mc/${tsFrontUrl}
mc.gouv.appfactory.${artifactIdLower}.front.sondageUrl.fr=https://service-public-particuliers.gouv.mc/Enquetes/???Votre-avis-apres-abandon
mc.gouv.appfactory.${artifactIdLower}.front.sondageAbandonUrl.fr=https://service-public-particuliers.gouv.mc/Enquetes/???Votre-avis

mc.gouv.appfactory.${artifactIdLower}.front.joCcinUrl.fr=https://journaldemonaco.gouv.mc/en/suiteUrl
mc.gouv.appfactory.${artifactIdLower}.front.joDemarcheUrl.fr=https://journaldemonaco.gouv.mc/en/suiteUrl
mc.gouv.appfactory.${artifactIdLower}.front.cgu.url.fr="https://journaldemonaco.gouv.mc/en/suiteUrl"

mc.gouv.appfactory.${artifactIdLower}.front.quitterTsUrl.en=http://service-public-particuliers.gouv.mc/
mc.gouv.appfactory.${artifactIdLower}.front.ficheDemarcheUrl.en=https://service-public-particuliers.gouv.mc/${tsFrontUrl}
mc.gouv.appfactory.${artifactIdLower}.front.sondageUrl.en=https://service-public-particuliers.gouv.mc/Enquetes/???Votre-avis-apres-abandon
mc.gouv.appfactory.${artifactIdLower}.front.sondageAbandonUrl.en=https://service-public-particuliers.gouv.mc/Enquetes/???Votre-avis

mc.gouv.appfactory.${artifactIdLower}.front.joCcinUrl.en=https://journaldemonaco.gouv.mc/en/suiteUrl
mc.gouv.appfactory.${artifactIdLower}.front.joDemarcheUrl.en=https://journaldemonaco.gouv.mc/en/suiteUrl
mc.gouv.appfactory.${artifactIdLower}.front.cgu.url.en="https://journaldemonaco.gouv.mc/en/suiteUrl"

mc.gouv.piwik.external.${artifactIdUpper}.piwikSiteId=14

${symbol_pound} URL de l'API
mc.gouv.appfactory.${artifactIdLower}.api.url=http://localhost:${tsApiPort}/${artifactIdLower}/api/v1

${symbol_pound} String jwt = createJWTToken("secret", "${artifactIdUpper}", new String[] { "USER" }, "${artifactIdUpper}", null, null);
${groupId}.frontserver.jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJERVJKRkVSIiwiYXVkIjoiREVSSkZFUiIsImlhdCI6IjIwMTktMDgtMTNUMTY6NDI6MTMrMDIwMCIsImp0aSI6ImI5NmRlNGYzLTEyMTUtNGIxZS1hMWM0LWM4MDI0Njg3NGRkYSIsImdvdXYiOnsic2hhcmVkIjp7InJvbGVzIjpbIlVTRVIiXX19fQ.UT2deXmJNRQOreQyF2HtlUoIl7ryz7fUslghjHolL-8

${symbol_pound} URL de redirection de l'utilisateur du front vers le back après création d'une demande d'un usager courrier
mc.gouv.appfactory.${artifactIdLower}.url=http://localhost:9081/${artifactIdLower}/

${symbol_pound} URL de redirection de l'utilisateur du front vers le back sur la demande qui vient d'être créée
${symbol_pound} <id> est remplacé par l'id de la demande
mc.gouv.appfactory.${artifactIdLower}.demande.url=http://localhost:${tsBackPort}/${artifactIdLower}/demandes/<id>?origin=fo

${groupId}.frontserver.key=pass
${symbol_pound} Clé partagée avec le back pour le calcul du sig

mc.gouv.appfactory.${artifactIdLower}.front.login.contact.url=http://localhost:20120/login/public/contact_email.xhtml?dest=%2Fdeclaration-${artifactIdLower}-887%2F&popabout=%2Fdeclaration-${artifactIdLower}-887%2F&international=fr

mc.gouv.${artifactIdLower}.frontserver.vscan.jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJERVJSRE9NIiwiYXVkIjoiVlNDQU4iLCJpYXQiOiIyMDIwLTAzLTEyVDEwOjQ3OjUyKzAxMDAiLCJqdGkiOiJiMGMyYTU3Ni04ZjdhLTQ2ZjMtYWY3MS05MTEyMDg0Njc2ZGEiLCJnb3V2Ijp7InNoYXJlZCI6eyJyb2xlcyI6WyJVU0VSIl19fX0.aq1evnbUx8S5Ls9Ax42nmkWCCw6nDe1q4g5oKpwaKgQ