#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
${symbol_pound} appli ${artifactIdUpper}
load-file-${artifactIdLower}-backserver=C:/java_dev_env/propertiesJETTY/${artifactIdLower}-backserver.properties
load-file-${artifactIdLower}-frontserver=C:/java_dev_env/propertiesJETTY/${artifactIdLower}-frontserver.properties
load-file-${artifactIdLower}-apiserver=C:/java_dev_env/propertiesJETTY/${artifactIdLower}-apiserver.properties
load-file-shared-${artifactIdLower}-backapi=C:/java_dev_env/propertiesJETTY/shared-${artifactIdLower}-backapi.properties



