application.name=stage

# utile pour charger le fichier application-local.properties en local
spring.profiles.active=local

# PostgreSQL properties
spring.datasource.url=jdbc:postgresql://localhost:5432/${application.name}
spring.datasource.username=${application.name}
spring.datasource.password=${application.name}
spring.datasource.driver-class-name=org.postgresql.Driver

# Spring Batch properties
spring.batch.jdbc.initialize-schema=never

# TS properties
file.url=http://linuxas-dev:30490/file/api/v1/file
file.jwt=${FILE_JWT}
pays.url=http://linuxas-dev:20110/servicerest/rest/pays
logon.api.url=http://linuxas-dev.monaco-gouvernement.mc/logon/rest
gichuni.api.url=https://gichuni-api-dev.monaco-gouvernement.mc
gichkey.url=https://gichuni-front-dev.monaco-gouvernement.mc/auth/realms/gichuni
gichkey.back.client_id=${application.name}-local
gichkey.back.client_secret=${BACK_GICHKEY_CLIENT_SECRET}

# Hikari
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000
