# PostgreSQL properties
spring.datasource.url=jdbc:postgresql://localhost:5432/stage
spring.datasource.username=stage
spring.datasource.password=stage
spring.datasource.driver-class-name=org.postgresql.Driver

# Spring Batch properties
spring.batch.jdbc.initialize-schema=never

# TS properties
application.name=stage
file.url=http://linuxas-dev:30490/file/api/v1/file
file.jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJTVEFHRSIsImF1ZCI6IkZJTEUiLCJpYXQiOiIyMDE4LTAxLTI1VDEwOjM1OjAzKzAxMDAiLCJqdGkiOiJhYWQ3NGJkNi02ZjRhLTRhMDMtYjA4ZS02MmQzZDQyOGI4NzIiLCJnb3V2Ijp7InNoYXJlZCI6eyJyb2xlcyI6WyJVU0VSIl19fX0.Rbuq5Z8AcYR_q7oK-UQmYjg3g3-WvukwMxW957C9u2M
pays.url=http://linuxas-dev:20110/servicerest/rest/pays
logon.api.url=http://linuxas-dev.monaco-gouvernement.mc/logon/rest
gichuni.api.url=https://gichuni-api-dev.monaco-gouvernement.mc
gichkey.url=https://gichuni-front-dev.monaco-gouvernement.mc/auth/realms/gichuni
gichkey.client_id=${application.name}-local
gichkey.client_secret=niz8NMs7Ni4Ie4wvbDceUKOzr6DLxB5o

# Hikari
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000
