spring.application.name=xaf-12-batch
# Elasticsearch properties
spring.elasticsearch.uris=http://localhost:9400
spring.elasticsearch.username=elastic
spring.elasticsearch.password=changeme

# PostgreSQL properties
spring.datasource.url=jdbc:postgresql://localhost:5432/stage
spring.datasource.username=stage
spring.datasource.password=stage
spring.datasource.driver-class-name=org.postgresql.Driver

# Spring Batch properties
spring.batch.initialize-schema=always
application.name=stage
