---
ansible_host: ${tscode}-appl1-0-mgmt
zabbix_host_name: ${TSAPPLZABBIX}
mc_fs_installed: false

tcp_checks:
  - name: logon-backserver
    host: linuxprod.monaco-gouvernement.mc
    port: 80
  - name: rest-apiserver
    host: linuxas-2.monaco-gouvernement.mc
    port: 20110
  - name: mail-apiserver
    host: linuxas-1.monaco-gouvernement.mc
    port: 30480
  - name: file-apiserver
    host: linuxas-1.monaco-gouvernement.mc
    port: 30490
  - name: postgresql
    host: gents-eosd1-0.monaco-gouvernement.mc
    port: 5432
  - name: elasticsearch
    host: ${tscode}-eose1-0.monaco-gouvernement.mc
    port: 9300
  - name: nexus
    host: linuxic.monaco-gouvernement.mc
    port: 80
  - name: zabbix-server
    host: zabbix3
    port: 10051
