<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>mc.gouv.xaf</groupId>
		<artifactId>xaf</artifactId>
		<version>10.0.0-SNAPSHOT</version>
	</parent>

	<artifactId>xaf-back</artifactId>

	<properties>
		<activiti.version>5.23.0</activiti.version>
		<logon-apiclient.version>5.2.2</logon-apiclient.version>
		<!-- Librairie pour generer le fichier recap d'une demande (sous license 
			LGPL). -->
		<openhtml.version>1.0.1</openhtml.version>
		<pdfbox.version>2.0.15</pdfbox.version>
		<xdocreport.version>2.0.2</xdocreport.version>
		<poi.version>4.1.0</poi.version>
		<vscan.version>1.0.0</vscan.version>
	</properties>

	<dependencies>
	
		<dependency>
			<groupId>org.springframework.kafka</groupId>
			<artifactId>spring-kafka</artifactId>
		</dependency>
		
		<dependency>
			<groupId>org.activiti</groupId>
			<artifactId>activiti-spring-boot-starter-basic</artifactId>
			<version>${activiti.version}</version>
		</dependency>

		<dependency>
			<groupId>mc.gouv.tools_jar</groupId>
			<artifactId>tools_jar</artifactId>
		</dependency>

		<dependency>
			<groupId>mc.gouv.xaf</groupId>
			<artifactId>xaf-shared</artifactId>
			<version>10.0.0-SNAPSHOT</version>
		</dependency>

		<dependency>
			<groupId>mc.gouv.file</groupId>
			<artifactId>file-apiclient</artifactId>
			<version>1.3.2</version>
		</dependency>

		<dependency>
			<groupId>mc.gouv.mail</groupId>
			<artifactId>mail-apiclient</artifactId>
			<version>1.3.1</version>
		</dependency>

		<dependency>
			<groupId>mc.gouv.vscan</groupId>
			<artifactId>vscan-shared</artifactId>
			<version>${vscan.version}</version>
		</dependency>

		<dependency>
			<groupId>com.fasterxml.uuid</groupId>
			<artifactId>java-uuid-generator</artifactId>
			<version>3.1.4</version>
		</dependency>

		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-web</artifactId>
		</dependency>

		<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
			<groupId>commons-beanutils</groupId>
			<artifactId>commons-beanutils</artifactId>
			<version>1.9.3</version>
		</dependency>

        <dependency>
            <groupId>mc.gouv.xboot</groupId>
            <artifactId>xboot-spring-starter-data-jpa</artifactId>
        </dependency>

        <dependency>
            <groupId>mc.gouv.xboot</groupId>
            <artifactId>xboot-spring-starter-api</artifactId>
        </dependency>

        <dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-core</artifactId>
		</dependency>


		<!-- Apache Velocity -->
		<dependency>
			<groupId>org.apache.velocity</groupId>
			<artifactId>velocity-tools</artifactId>
			<version>2.0</version>
			<exclusions>
				<exclusion>
					<groupId>javax.servlet</groupId>
					<artifactId>servlet-api</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.apache.struts</groupId>
					<artifactId>*</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<!-- Fin Apache Velocity -->

		<dependency>
			<groupId>mc.gouv.xboot</groupId>
			<artifactId>xboot-caching</artifactId>
		</dependency>

		<dependency>
			<groupId>mc.gouv.server</groupId>
			<artifactId>servicerest_client</artifactId>
		</dependency>

		<dependency>
			<groupId>mc.gouv.servicerest</groupId>
			<artifactId>servicerest-caching</artifactId>
			<version>2.2.15</version>
		</dependency>

		<dependency>
			<groupId>mc.gouv.logon</groupId>
			<artifactId>logon-caching</artifactId>
			<version>${logon-apiclient.version}</version>
		</dependency>

		<dependency>
			<groupId>mc.gouv.logon</groupId>
			<artifactId>logon-apiclient</artifactId>
		</dependency>


		<dependency>
			<artifactId>xboot-spring-starter-test</artifactId>
			<groupId>mc.gouv.xboot</groupId>
		</dependency>
		<!-- Pour la génération de PDF : -->

		<dependency>
			<groupId>fr.opensagres.xdocreport</groupId>
			<artifactId>fr.opensagres.xdocreport.document</artifactId>
			<version>${xdocreport.version}</version>
		</dependency>

		<dependency>
			<groupId>fr.opensagres.xdocreport</groupId>
			<artifactId>fr.opensagres.xdocreport.document.docx</artifactId>
			<version>${xdocreport.version}</version>
		</dependency>

		<dependency>
			<groupId>fr.opensagres.xdocreport</groupId>
			<artifactId>fr.opensagres.xdocreport.template.velocity</artifactId>
			<version>${xdocreport.version}</version>
		</dependency>

		<dependency>
			<groupId>fr.opensagres.xdocreport</groupId>
			<artifactId>fr.opensagres.xdocreport.converter</artifactId>
			<version>${xdocreport.version}</version>
		</dependency>

		<dependency>
			<groupId>fr.opensagres.xdocreport</groupId>
			<artifactId>fr.opensagres.xdocreport.converter.docx.xwpf</artifactId>
			<version>${xdocreport.version}</version>
		</dependency>

		<dependency>
			<groupId>fr.opensagres.xdocreport</groupId>
			<artifactId>fr.opensagres.xdocreport.document.odt</artifactId>
			<version>${xdocreport.version}</version>

		</dependency>
		<dependency>
			<groupId>fr.opensagres.xdocreport</groupId>
			<artifactId>fr.opensagres.xdocreport.document.ods</artifactId>
			<version>${xdocreport.version}</version>
		</dependency>

		<dependency>
			<groupId>fr.opensagres.xdocreport</groupId>
			<artifactId>fr.opensagres.poi.xwpf.converter.core</artifactId>
			<version>${xdocreport.version}</version>
			<exclusions>
				<exclusion>
					<groupId>org.apache.poi</groupId>
					<artifactId>poi-ooxml</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		<!-- Fin génération de PDF -->

		<!-- Génération de fichier PDF à partir de HTML -->

		<dependency>
			<groupId>com.openhtmltopdf</groupId>
			<artifactId>openhtmltopdf-core</artifactId>
			<version>${openhtml.version}</version>
		</dependency>

		<dependency>
			<groupId>com.openhtmltopdf</groupId>
			<artifactId>openhtmltopdf-pdfbox</artifactId>
			<version>${openhtml.version}</version>
		</dependency>

		<dependency>
	  	    <!-- logs via slf4j. -->
	  		<groupId>com.openhtmltopdf</groupId>
	  		<artifactId>openhtmltopdf-slf4j</artifactId>
	  		<version>${openhtml.version}</version>
	  	</dependency>

		<!-- Fin HTML to PDF -->

		<!-- Pour export Excel -->

		<dependency>
			<groupId>org.jxls</groupId>
			<artifactId>jxls</artifactId>
			<version>2.7.2</version>
		</dependency>

		<dependency>
			<groupId>org.jxls</groupId>
			<artifactId>jxls-poi</artifactId>
			<version>1.3.1</version>
		</dependency>

		<dependency>
			<groupId>org.apache.tika</groupId>
			<artifactId>tika-parsers</artifactId>
		</dependency>

		<dependency>
			<groupId>org.apache.tika</groupId>
			<artifactId>tika-langdetect</artifactId>
		</dependency>

		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-collections4</artifactId>
			<version>4.1</version>
		</dependency>

		<dependency>
			<groupId>org.apache.pdfbox</groupId>
			<artifactId>jbig2-imageio</artifactId>
			<version>3.0.0</version>
		</dependency>
		<dependency>
			<groupId>org.apache.pdfbox</groupId>
			<artifactId>pdfbox</artifactId>
			<version>${pdfbox.version}</version>
		</dependency>
		<dependency>
			<groupId>org.apache.pdfbox</groupId>
			<artifactId>fontbox</artifactId>
			<version>${pdfbox.version}</version>
		</dependency>

		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-compress</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-elasticsearch</artifactId>
			<exclusions>
				<exclusion>
					<groupId>org.elasticsearch.client</groupId>
					<artifactId>transport</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		<dependency>
			<groupId>org.elasticsearch.client</groupId>
			<artifactId>elasticsearch-rest-high-level-client</artifactId>
			<version>6.8.4</version>
		</dependency>
		
		<!-- Quartz -->
		<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-quartz</artifactId>
        </dependency>

		<!-- Pour appeler l'API GICHUNI en OIDC -->
		<dependency>
			<groupId>org.springframework.security.oauth.boot</groupId>
			<artifactId>spring-security-oauth2-autoconfigure</artifactId>
			<version>2.0.0.RELEASE</version>
		</dependency>
	</dependencies>

	<dependencyManagement>
		<dependencies>
			<!-- CVE-2019-13990 : mettre à jour tika quand celui-ci utilisera cette nouvelle version de quartz-->
			<dependency>
				<groupId>org.quartz-scheduler</groupId>
				<artifactId>quartz</artifactId>
				<version>2.3.2</version>
			</dependency>

			<!-- CVE-2018-10054 -->
			<dependency>
				<groupId>com.h2database</groupId>
				<artifactId>h2</artifactId>
				<version>1.4.200</version>
			</dependency>

			<!-- CVE-2019-16869 -->
			<dependency>
				<groupId>io.netty</groupId>
				<artifactId>netty-transport</artifactId>
				<version>4.1.43.Final</version>
			</dependency>

			<!-- CWE-300 -->
			<dependency>
				<groupId>org.jgroups</groupId>
				<artifactId>jgroups</artifactId>
				<version>4.1.1.Final</version>
			</dependency>
		</dependencies>
	</dependencyManagement>

</project>

