package mc.gouv.xaf.back.dsp.enums;

public enum ResidEntiteDemandantCDREnum {

    AMBASSADE_CONSULAT_MONACO("AMBASSADE_CONSULAT_MONACO"),
    AMBASSADE_CONSULAT_ETRANGER("AMBASSADE_CONSULAT_ETRANGER"),
    AUTORITE_ADMINISTRATIVE_MONACO("AUTORITE_ADMINISTRATIVE_MONACO"),
    AUTORITE_ADMINISTRATIVE_ETRANGER("AUTORITE_ADMINISTRATIVE_ETRANGER"),
    ORGANISME_PRIVE("ORGANISME_PRIVE"),
    CAISSES_SOCIALES_MONACO("CAISSES_SOCIALES_MONACO"),
    CAISSES_SOCIALES_ETRANGER("CAISSES_SOCIALES_ETRANGER"),
    BANQUE_MONACO("BANQUE_MONACO"),
    BANQUE_ETRANGER("BANQUE_ETRANGER");

    public String value;

    ResidEntiteDemandantCDREnum(String value) {
        this.value = value;
    }
}
