package mc.gouv.xaf.back.dsp.enums;

public enum ResidSituationEnum {

    CHEF_D_ENTREPRISE_PDG_ASSOCIE_D_UNE_SARL("CHEF_D_ENTREPRISE_PDG_ASSOCIE_D_UNE_SARL"),
    INDEPENDANT_A_SON_COMPTE_PROFESSION_LIBERALE("INDEPENDANT_A_SON_COMPTE_PROFESSION_LIBERALE"),
    AIDE_UNE_PERSONNE_TRAVAIL_SANS_ETRE_REMUNERE("AIDE_UNE_PERSONNE_TRAVAIL_SANS_ETRE_REMUNERE"),
    SALARIE("SALARIE"),
    ETUDIANT("ETUDIANT"),
    CHOMEUR("CHOMEUR"),
    RETRAITE("RETRAITE"),
    PERSONNE_AU_FOYER("PERSONNE_AU_FOYER"),
    INVALIDITE_HANDICAP_MALADIE("INVALIDITE_HANDICAP_MALADIE"),
    RENTIER("RENTIER");

    public String value;

    ResidSituationEnum(String value) {
        this.value = value;
    }
}
