package mc.gouv.xaf.back.dsp.enums;

public enum ResidPieceJustificativeTypeEnum {
	
	// Valeurs relative à l'ancien modèle 
//	DOCUMENT_BANCAIRE("DOCUMENT_BANCAIRE"),
//    FACTURE_SMEG("FACTURE_SMEG"),
//    ALLOCATION_POLE_EMPLOI("ALLOCATION_POLE_EMPLOI"),
//    NOUVEAU_CONTRAT_ELECTRICITE("NOUVEAU_CONTRAT_ELECTRICITE"),
//    CERTIF_SCOLARITE("CERTIF_SCOLARITE"),
//    CARTE_ETUDIANT("CARTE_ETUDIANT"),
//    AVIS_IMPOTS("AVIS_IMPOTS"),
//    AUTORISATION_EMBAUCHAGE("AUTORISATION_EMBAUCHAGE"),
//    AUTORISATION_MINISTERIELLE("AUTORISATION_MINISTERIELLE"),
//    PENSION_RETRAITE("PENSION_RETRAITE"),

    // Valeurs du nouveau modèle
    CARTE_IDENTITE("CARTE_IDENTITE"),
    PASSEPORT("PASSEPORT"),
    DOCUMENT_DE_VOYAGE_POUR_ETRANGER("DOCUMENT_DE_VOYAGE_POUR_ETRANGER"),
    PASSEPORT_DIPLOMATIQUE("PASSEPORT_DIPLOMATIQUE"),
    ACTE_PROPRIETE("ACTE_PROPRIETE"),
    ATTESTATION_HEBERGEMENT("ATTESTATION_HEBERGEMENT"),
    AVENANT_HEBERGEMENT("AVENANT_HEBERGEMENT"),
    AVENANT_AU_BAIL("AVENANT_AU_BAIL"),
    BAIL_A_LOYER("BAIL_A_LOYER"),
    BAIL_AVENANT("BAIL_AVENANT"),
    BAIL_HEBERGEMENT("BAIL_HEBERGEMENT"),
    CERTIFICAT_HEBERGEMENT("CERTIFICAT_HEBERGEMENT"),
    CERTIFICAT_POSITION_MILITAIRE("CERTIFICAT_POSITION_MILITAIRE"),
    CONTRAT_HABITATION_CAPITALISATION_HEBERGEMENT("CONTRAT_HABITATION_CAPITALISATION_HEBERGEMENT"),
    CONTRAT_OU_COMMODAT("CONTRAT_OU_COMMODAT"),
    CONTRAT_HABITATION_CAPITALISATION("CONTRAT_HABITATION_CAPITALISATION"),
    MISE_A_DISPOSITION("MISE_A_DISPOSITION"),
    PROPRIETE_HEBERGEMENT("PROPRIETE_HEBERGEMENT"),
    BULLETIN_SALAIRE("BULLETIN_SALAIRE"),
    EXTRAIT_RCI("EXTRAIT_RCI"),
    STATUT_SCI("STATUT_SCI"),
    ATTESTATION_BANCAIRE("ATTESTATION_BANCAIRE"),
    ATTESTATION_EXPERT_COMPTABLE("ATTESTATION_EXPERT_COMPTABLE"),
    ALLOCATIONS_PENSIONS("ALLOCATIONS_PENSIONS"),
    ATTESTATION_PRISE_EN_CHARGE("ATTESTATION_PRISE_EN_CHARGE"),
    RELEVES_BANCAIRES("RELEVES_BANCAIRES"),
    ATTESTATION_SUR_HONNEUR("ATTESTATION_SUR_HONNEUR"),
    STATUTS_SOCIETE("STATUTS_SOCIETE"),
    DECLARATION_IMPOTS("DECLARATION_IMPOTS"),
    JUGEMENT_CIVIL("JUGEMENT_CIVIL"),
    JUSTIFICATIF_REVENUS("JUSTIFICATIF_REVENUS"),
    ACTE_MARIAGE_OU_FAMILLE("ACTE_MARIAGE_OU_FAMILLE"),
    ACTE_MARIAGE("ACTE_MARIAGE"),
    LIVRET_FAMILLE("LIVRET_FAMILLE"),
    ACTE_NAISSANCE("ACTE_NAISSANCE"),
    CARTE_PROFESSIONNELLE("CARTE_PROFESSIONNELLE"),
    CONTRAT_TRAVAIL("CONTRAT_TRAVAIL"),
    JUSTIF_PERTE_NATIONALITE("JUSTIF_PERTE_NATIONALITE"),
    PERMIS_TRAVAIL("PERMIS_TRAVAIL"),
    STATUTS_SCI("STATUTS_SCI"),
    NON_APPLICABLE("NON_APPLICABLE"),
    MANDATAIRE("MANDATAIRE"),
    FACTURE_ENERGIE("FACTURE_ENERGIE"),
    PROCES_VERBAL_VOL("PROCES_VERBAL_VOL"),
    ACTE_DECES_CONJOINT("ACTE_DECES_CONJOINT"),
    DOCUMENT_CHANGEMENT_PATRONYME("DOCUMENT_CHANGEMENT_PATRONYME"),
    JUSTIFICATIF_NOUVELLE_ADRESSE("JUSTIFICATIF_NOUVELLE_ADRESSE"),
    JUSTIFICATIF_EMPLOI("JUSTIFICATIF_EMPLOI"),
    JUSTIFICATIF_PERTE_NATIONALITE("JUSTIFICATIF_PERTE_NATIONALITE"),
    PROMESSE_EMBAUCHE("PROMESSE_EMBAUCHE"),
    CONTRAT_EMBAUCHE("CONTRAT_EMBAUCHE"),
    AUTORISATION_EMBAUCHE("AUTORISATION_EMBAUCHE"),
    CONTRAT_TRAVAIL_ETRANGER("CONTRAT_TRAVAIL_ETRANGER"),
    ATTESTATION_INSCRIPTION_RETRAITE("ATTESTATION_INSCRIPTION_RETRAITE"),
    JUSTIFICATIF_SCOLARITE_ETUDES("JUSTIFICATIF_SCOLARITE_ETUDES"),
    ACTE_NATURALISATION("ACTE_NATURALISATION"),
    SAISINE_ORIGINE_DEMANDE_CR("SAISINE_ORIGINE_DEMANDE_CR"),
	AUTRE("AUTRE");


    public String value;

    ResidPieceJustificativeTypeEnum(String value) {
        this.value = value;
    }
}
