package mc.gouv.xaf.back.dsp.enums;

public enum ResidPieceJustificativeTypeEnum {

    CARTE_IDENTITE("CARTE_IDENTITE"),
    PASSEPORT("PASSEPORT"),
    DOCUMENT_DE_VOYAGE_POUR_ETRANGER("DOCUMENT_DE_VOYAGE_POUR_ETRANGER"),
    PASSEPORT_DIPLOMATIQUE("PASSEPORT_DIPLOMATIQUE"),
    ACTE_PROPRIETE("ACTE_PROPRIETE"),
    ATTESTATION_HEBERGEMENT("ATTESTATION_HEBERGEMENT"),
    AVENANT_HEBERGEMENT("AVENANT_HEBERGEMENT"),
    AVENANT_AU_BAIL("AVENANT_AU_BAIL"),
    BAIL_A_LOYER("BAIL_A_LOYER"),
    BAIL_AVENANT("BAIL_AVENANT"),
    BAIL_HEBERGEMENT("BAIL_HEBERGEMENT"),
    CERTIFICAT_HEBERGEMENT("CERTIFICAT_HEBERGEMENT"),
    CERTIFICAT_POSITION_MILITAIRE("CERTIFICAT_POSITION_MILITAIRE"),
    CONTRAT_HABITATION_CAPITALISATION_HEBERGEMENT("CONTRAT_HABITATION_CAPITALISATION_HEBERGEMENT"),
    CONTRAT_OU_COMMODAT("CONTRAT_OU_COMMODAT"),
    CONTRAT_HABITATION_CAPITALISATION("CONTRAT_HABITATION_CAPITALISATION"),
    MISE_A_DISPOSITION("MISE_A_DISPOSITION"),
    PROPRIETE_HEBERGEMENT("PROPRIETE_HEBERGEMENT"),
    FACTURE_ELECTRICITE("FACTURE_ELECTRICITE"),
    BULLETIN_SALAIRE("BULLETIN_SALAIRE"),
    EXTRAIT_RCI("EXTRAIT_RCI"),
    ATTESTATION_BANCAIRE("ATTESTATION_BANCAIRE"),
    ATTESTATION_EXPERT_COMPTABLE("ATTESTATION_EXPERT_COMPTABLE"),
    ALLOCATIONS_PENSIONS("ALLOCATIONS_PENSIONS"),
    ATTESTATION_PRISE_EN_CHARGE("ATTESTATION_PRISE_EN_CHARGE"),
    CARTE_ETUDIANT("CARTE_ETUDIANT"),
    RELEVES_BANCAIRES("RELEVES_BANCAIRES"),
    ATTESTATION_SUR_HONNEUR("ATTESTATION_SUR_HONNEUR"),
    STATUTS_SOCIETE("STATUTS_SOCIETE"),
    DECLARATION_IMPOTS("DECLARATION_IMPOTS"),
    JUGEMENT_CIVIL("JUGEMENT_CIVIL"),
    ACTE_MARIAGE_OU_FAMILLE("ACTE_MARIAGE_OU_FAMILLE"),
    ACTE_NAISSANCE("ACTE_NAISSANCE"),
    ATTESTATION_COMPTABLE("ATTESTATION_COMPTABLE"),
    AUTORISATION_EMBAUCHAGE("AUTORISATION_EMBAUCHAGE"),
    AUTORISATION_MINISTERIELLE("AUTORISATION_MINISTERIELLE"),
    AVIS_IMPOTS("AVIS_IMPOTS"),
    CARTE_PROFESSIONNELLE("CARTE_PROFESSIONNELLE"),
    CERTIF_SCOLARITE("CERTIF_SCOLARITE"),
    CONTRAT_TRAVAIL("CONTRAT_TRAVAIL"),
    DOCUMENT_BANCAIRE("DOCUMENT_BANCAIRE"),
    FACTURE_SMEG("FACTURE_SMEG"),
    JUSTIF_PERTE_NATIONALITE("JUSTIF_PERTE_NATIONALITE"),
    ALLOCATION_POLE_EMPLOI("ALLOCATION_POLE_EMPLOI"),
    NOUVEAU_CONTRAT_ELECTRICITE("NOUVEAU_CONTRAT_ELECTRICITE"),
    PERMIS_TRAVAIL("PERMIS_TRAVAIL"),
    STATUTS_SCI("STATUTS_SCI"),
    PENSION_RETRAITE("PENSION_RETRAITE"),
    NON_APPLICABLE("NON_APPLICABLE"),
	AUTRE("AUTRE");


    public String value;

    ResidPieceJustificativeTypeEnum(String value) {
        this.value = value;
    }
}
