package mc.gouv.xaf.back.dsp.enums;

public enum ResidEntiteDemandantCDREnum {

    ADMINISTRATION_FISCALE_ETRANGER("ADMINISTRATION_FISCALE_ETRANGER"),
    DIRECTION_SERVICES_FISCAUX("DIRECTION_SERVICES_FISCAUX"),
    AGENCE_IMMOBILIERE("AGENCE_IMMOBILIERE"),
    AMBASSADE_ITALIE_MONACO("AMBASSADE_ITALIE_MONACO"),
    AMBASSADE_FRANCE_MONACO("AMBASSADE_FRANCE_MONACO"),
    AUTORITE_ADMINISTRATIVE_ETRANGER("AUTORITE_ADMINISTRATIVE_ETRANGER"),
    ADMINISTRATION_MONACO("ADMINISTRATION_MONACO"),
    AUTORITE_RELIGIEUSE("AUTORITE_RELIGIEUSE"),
    AVOCAT("AVOCAT"),
    BANQUE_ETRANGER("BANQUE_ETRANGER"),
    BANQUE_MONACO("BANQUE_MONACO"),
    CAISSE_RETRAITE_ETRANGER("CAISSE_RETRAITE_ETRANGER"),
    CAISSE_SOCIALE_ETRANGER("CAISSE_SOCIALE_ETRANGER"),
    CAISSES_SOCIALES_MONACO("CAISSES_SOCIALES_MONACO"),
    CHPG("CHPG"),
    ASSURANCE_ETRANGER("ASSURANCE_ETRANGER"),
    ASSURANCE_MONACO("ASSURANCE_MONACO"),
    FEDERATION_ASSOCIATION_SPORTIVE("FEDERATION_ASSOCIATION_SPORTIVE"),
    DIRECTION_ACTION_SANITAIRE("DIRECTION_ACTION_SANITAIRE"),
    DIRECTION_ACTION_AIDE_SOCIALES("DIRECTION_ACTION_AIDE_SOCIALES"),
    DENJS("DENJS"),
    CAISSE_AUTONOME_RETRAITES("CAISSE_AUTONOME_RETRAITES"),
    UNIVERSITE_ETRANGER("UNIVERSITE_ETRANGER"),
    MAISON_RETRAITE("MAISON_RETRAITE"),
    NOTAIRE("NOTAIRE"),
    POSTE("POSTE"),
    POSTE_CONSULAIRE_ETRANGER("POSTE_CONSULAIRE_ETRANGER"),
    POSTE_CONSULAIRE_MONACO("POSTE_CONSULAIRE_MONACO"),
    TRIBUNAL_ETRANGER("TRIBUNAL_ETRANGER");

    public String value;

    ResidEntiteDemandantCDREnum(String value) {
        this.value = value;
    }
}
