#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
${symbol_pound}Maven properties
maven.name=@project.name@
maven.version=@project.version@
${symbol_pound}maven.build.date aura ce format : 2017-04-28T13:08:51Z
maven.build.date=@buildDate@

${symbol_pound}spring.jpa.show-sql = true
spring.jpa.hibernate.ddl-auto = none
${symbol_pound} Pour afficher les valeurs des paramètres des requètes SQL
${symbol_pound}logging.level.org.hibernate.SQL=DEBUG
${symbol_pound}logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

${symbol_pound} Pour afficher les logs debug de Spring (autowiring troubleshooting etc.)
${symbol_pound}logging.level.org.springframework = DEBUG

server.port=${tsApiPort}
server.servlet.context-path=/${artifactIdLower}

spring.security.xboot.jwt=true

${symbol_pound} Pour empécher que Velocity fasse sa config Java et s'interface dans la gestion des pages
${symbol_pound} Sinon on obtient: org.apache.velocity : ResourceManager : unable to find resource 'blablabla.vm' in any resource loader.
spring.velocity.enabled=false

${symbol_pound} Utilisation de ehCache
spring.cache.jcache.config=classpath:ehcache.xml

${symbol_pound} Pour l'internationalisation
spring.messages.basename=messages/messages
spring.messages.cache-seconds=-1
spring.messages.encoding=UTF-8

spring.profiles.active=gouv

spring.datasource.initialize=false
spring.datasource.platform=postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.thymeleaf.cache=false

display.name=${artifactIdUpper}
db.name=${artifactIdUpper}
application.name=${artifactIdLower}

spring.http.multipart.maxFileSize: 5MB
spring.http.multipart.maxRequestSize: 5MB

${symbol_pound} Sert � pouvoir r�cup�rer le BPMN depuis le JAR ${artifactIdLower}-service (par d�faut c'est classpath:, pas classpath*:)
spring.activiti.processDefinitionLocationPrefix=classpath*:/processes/

${symbol_pound}Mode embarqu� pour art�mis
spring.artemis.mode=embedded
${symbol_pound}Pour d�sactiver la configuration embedded par d�faut qui ne g�re pas un acc�s s�curis� par user / password
spring.artemis.embedded.enabled=false
${symbol_pound}Pour activer la nouvelle configuration securis�e
spring.artemis.embedded.secure.enabled=true
${symbol_pound}Pour configurer via  mc.gouv.xaf.apiserver.ArtemisConfig le fait de pouvoir s'y connecter depuis une application tierce
spring.artemis.embedded.remoteAccess=true
${symbol_pound}Le topic est persistent
spring.artemis.embedded.persistent=true
${symbol_pound}Pour cr�er automatiquement le topic demandes
spring.artemis.embedded.topics=demandes,demandes.dlq

${groupId}.jms.topic.create=true
${groupId}.indexing.enabled=true

