<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>mc.gouv.xaf</groupId>
        <artifactId>xaf</artifactId>
        <version>9.1.4.0-SNAPSHOT</version>
    </parent>

    <artifactId>xaf-back-denjs</artifactId>

    <properties>
        <logon-apiclient.version>5.2.2</logon-apiclient.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>mc.gouv.xaf</groupId>
            <artifactId>xaf-back</artifactId>
            <version>9.1.4.0-SNAPSHOT</version>
        </dependency>
    </dependencies>

</project>

