-- #12951 - Stocker en base le buildId et le recapType
ALTER TABLE ${artifactIdUpper}.DEM_DEMANDES ADD COLUMN BUILD_ID CHARACTER VARYING(32);
ALTER TABLE ${artifactIdUpper}.DEM_DEMANDES ADD COLUMN RECAP_TYPE CHARACTER VARYING(256);
