application.module=apiserver
server.port=${api.port}

# Security secret
mc.gouv.appli.apiserver.security.jwt.secret=${APPLI_API_SECURITY_JWT_SECRET}
# MonGuichet
mc.gouv.appli.apiserver.gichkey.client_secret=${APPLI_API_GICHKEY_CLIENT_SECRET}
mc.gouv.appli.apiserver.gichkey.client_id=${gichkey.client_id}
