#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )

-- Début scripts de "Data" : Insert, Update, Delete

--Requête générées depuis la moulinette à partir des données du front
INSERT INTO ${artifactIdLower}.dem_recherche_cat_config (libelle, editable) VALUES ('Le demandeur', 'false');
INSERT INTO ${artifactIdLower}.dem_recherche_cat_config (libelle, editable) VALUES ('Informations de l''entreprise', 'false');
INSERT INTO ${artifactIdLower}.dem_recherche_cat_config (libelle, editable) VALUES ('La dérogation', 'false');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('true', 'contenu.donnee.demandeur.titre', 'Titre', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Le demandeur'), 'false');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('true', 'contenu.donnee.demandeur.prenom', 'Prénom du demandeur', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Le demandeur'), 'false');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('true', 'contenu.donnee.demandeur.nom', 'Nom du demandeur', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Le demandeur'), 'false');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('true', 'contenu.donnee.demandeur.mail', 'Email de contact', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Le demandeur'), 'false');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('true', 'contenu.donnee.entreprise.numerocar', 'N° CAR', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Informations de l''entreprise'), 'false');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('true', 'contenu.donnee.entreprise.raisonsociale', 'Raison Sociale', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Informations de l''entreprise'), 'false');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('true', 'contenu.donnee.entreprise.nom', 'Nom de l''entreprise', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Informations de l''entreprise'), 'false');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('true', 'contenu.donnee.entreprise.adresse.ligne1', 'Adresse ligne 1', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Informations de l''entreprise'), 'false');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('true', 'contenu.donnee.entreprise.adresse.ligne2', 'Adresse ligne 2', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Informations de l''entreprise'), 'false');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('true', 'contenu.donnee.entreprise.adresse.ligne3', 'Adresse ligne 3', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Informations de l''entreprise'), 'false');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('true', 'contenu.donnee.entreprise.adresse.codePostal', 'Code postal', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Informations de l''entreprise'), 'false');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('true', 'contenu.donnee.entreprise.adresse.ville', 'Ville', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Informations de l''entreprise'), 'false');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('true', 'contenu.donnee.entreprise.adresse.pays', 'Pays', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Informations de l''entreprise'), 'false');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('true', 'contenu.donnee.entreprise.telephone', 'Téléphone de l''entreprise', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Informations de l''entreprise'), 'false');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('true', 'contenu.donnee.derogation.joursferies', 'Jours fériés légaux', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'La dérogation'), 'false');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('true', 'contenu.donnee.derogation.employe.concerne', 'Personnel concerné par la dérogation', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'La dérogation'), 'false');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('true', 'contenu.donnee.derogation.motivationdemande', 'Motivation de la demande', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'La dérogation'), 'false');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('true', 'contenu.donnee.derogation.presencedeleguespersonnel', 'Avez-vous des délégués du personnel?', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'La dérogation'), 'false');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('true', 'contenu.donnee.derogation.nombresalarie', 'Nombre de salariés dans l''entreprise', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'La dérogation'), 'false');
--Configuration par défaut
INSERT INTO ${artifactIdLower}.dem_recherche_cat_config (libelle, editable) VALUES ('Demande', 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_cat_config (libelle, editable) VALUES ('Canal', 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_cat_config (libelle, editable) VALUES ('Informations réservées à l''administration', 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_cat_config (libelle, editable) VALUES ('Dernier statut', 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_cat_config (libelle, editable) VALUES ('Usager', 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_cat_config (libelle, editable) VALUES ('Pièce(s) jointe(s)', 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_cat_config (libelle, editable) VALUES ('Complément de demande', 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_cat_config (libelle, editable) VALUES ('Fichiers internes', 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_cat_config (libelle, editable) VALUES ('Historique des statuts', 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_cat_config (libelle, editable) VALUES ('Données', 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_cat_config (libelle, editable) VALUES ('Agent', 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_cat_config (libelle, editable) VALUES ('Courrier', 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('false', 'access.demarcheId', 'Identifiant de la démarche', null, 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('false', 'access.usagerId', 'Identifiant de l''usager', null, 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('false', 'access.fkAccess', '', null, 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('false', 'agentAffecteNomAffichage', 'Nom d''afichage de l''agent responsable', null, 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('false', 'usager.paysCode', 'Code du pays', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Usager'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('false', 'usager.etat', 'Etat', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Usager'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('false', 'usager.dateDerConnexion', 'Date de la dernière connexion', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Usager'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('false', 'usager.dateActivation', 'Date d''activation', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Usager'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('false', 'usager.dateCreation', 'Date de création', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Usager'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('false', 'usager.paysId', 'Id du pays', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Usager'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('false', 'usager.id', 'Identifiant de l''usager', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Usager'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('false', 'canal.code', 'Code du canal', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Canal'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('false', 'agentAffecteId', 'Identifiant de l''agent', null, 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('false', 'dernierStatut.codeMotif', 'Code du motif', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Dernier statut'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('false', 'dernierStatut.pkStatut', 'Id du statut', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Dernier statut'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('false', 'dernierStatut.code', 'Code du statut de la demande', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Dernier statut'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('false', 'pkDemandes', 'Identifiant de la demande', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Demande'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('false', 'creeParAgentId', 'Identifiant de l''agent qui a crée la demande', null, 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('false', 'statuts.code', 'Code du statut de la demande', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Historique des statuts'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('false', 'statuts.codeMotif', 'Code du motif', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Historique des statuts'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('false', 'dateCreation', 'Date de création', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Demande'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('false', 'dateDerModif', 'Date de dernière modification', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Demande'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('false', 'courrierDateReception', 'Date de réception', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Détail des informations personnelles de l’usager'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('false', 'data.demandeId', 'Id de la demande', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Données'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('false', 'data.pkDemandesData', 'Id de la donnée', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Données'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('false', 'statuts.pkStatut', 'Id du statut', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Historique des statuts'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('false', 'dernierStatut.agentId', 'Id agent', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Dernier statut'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('false', 'dernierStatut.usagerId', 'Id usager', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Dernier statut'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('false', 'access.active', 'Actif', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Usager'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('false', 'statuts.agentId', 'Id agent', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Historique des statuts'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('false', 'statuts.usagerId', 'Id usager', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Historique des statuts'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('false', 'fichiers.demandeId', 'Id demande', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Pièce(s) jointe(s)'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('false', 'fichiers.url', 'Url', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Pièce(s) jointe(s)'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('false', 'fichiers.language', 'Langue', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Pièce(s) jointe(s)'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('false', 'fichiers.id', 'Identifiant', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Pièce(s) jointe(s)'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('false', 'fichiers.type', 'Type de fichier', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Pièce(s) jointe(s)'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('false', 'complement.fichiers.demandeId', 'Id demande', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Complément de demande'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('false', 'complement.fichiers.url', 'Url', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Complément de demande'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('false', 'complement.fichiers.language', 'Langue', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Complément de demande'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('false', 'complement.fichiers.id', 'Identifiant', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Complément de demande'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('false', 'complement.fichiers.type', 'Type de fichier', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Complément de demande'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('false', 'fichierinterne.fichiers.demandeId', 'Id demande', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Fichiers internes'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('false', 'fichierinterne.fichiers.url', 'Url', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Fichiers internes'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('false', 'fichierinterne.fichiers.language', 'Langue', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Fichiers internes'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('false', 'fichierinterne.fichiers.id', 'Identifiant', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Fichiers internes'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('false', 'fichierinterne.fichiers.type', 'Type de fichier', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Fichiers internes'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('true', 'canal.libelle', 'Mode de réception', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Canal'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('true', 'langue', 'Langue', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Demande'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('true', 'observations', 'Observations', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Informations réservées à l''administration'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('true', 'dernierStatut.libelle', 'Libellé', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Dernier statut'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('true', 'dernierStatut.date', 'Date', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Dernier statut'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('true', 'dernierStatut.commentaire', 'Commentaire', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Dernier statut'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('true', 'dernierStatut.libelleMotif', 'Libellé du motif', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Dernier statut'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('true', 'statuts.date', 'Date du statut', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Historique des statuts'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('true', 'statuts.commentaire', 'Commentaire', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Historique des statuts'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('true', 'statuts.libelleMotif', 'Libellé du motif', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Historique des statuts'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('true', 'statuts.libelle', 'Libellé du statut', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Historique des statuts'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('true', 'identifiant', 'Identifiant', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Demande'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('true', 'fichiers.content', 'Contenu', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Pièce(s) jointe(s)'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('true', 'fichiers.name', 'Nom', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Pièce(s) jointe(s)'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('true', 'complement.fichiers.content', 'Contenu', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Complément de demande'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('true', 'complement.fichiers.name', 'Nom de la pièce jointe', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Complément de demande'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('true', 'complements.statut', 'Statut', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Complément de demande'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('true', 'complements.question.codeMotif', 'Code du motif', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Complément de demande'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('true', 'data.key', 'Clé', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Données'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('true', 'data.value', 'Valeur', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Données'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('true', 'usager.nom', 'Nom', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Usager'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('true', 'usager.prenom', 'Prénom', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Usager'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('true', 'usager.adresse1', 'Adresse 1', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Usager'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('true', 'usager.adresse2', 'Adresse 2', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Usager'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('true', 'usager.codePostal', 'Code postal', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Usager'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('true', 'usager.ville', 'Ville', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Usager'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('true', 'usager.nomPays', 'Pays', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Usager'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('true', 'usager.complementAdresse', 'Complément d''adresse', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Usager'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('true', 'usager.raisonSociale', 'Raison sociale', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Usager'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('true', 'usager.email', 'Email', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Usager'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('true', 'usager.login', 'Identifiant du compte usager', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Usager'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('true', 'usager.titre', 'Titre', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Usager'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('true', 'agent.matricule', 'Matricule', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Agent'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('true', 'agent.nom', 'Nom', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Agent'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('true', 'agent.nomUsage', 'Nom d''usage', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Agent'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('true', 'agent.nomNaissance', 'Nom de naissance', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Agent'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('true', 'agent.prenom', 'Prénom', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Agent'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('true', 'agent.mail', 'Email', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Agent'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('true', 'courrierRefInterne', 'Référence interne', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Courrier'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('true', 'nomsCourriers', 'Nom', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Courrier'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('true', 'fichierinterne.fichiers.content', 'Contenu', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Fichiers internes'), 'true');
INSERT INTO ${artifactIdLower}.dem_recherche_champ_config (enabled, cle, libelle, fk_categorie, editable) VALUES ('true', 'fichierinterne.fichiers.name', 'Nom du fichier', (select id from ${artifactIdLower}.dem_recherche_cat_config where libelle = 'Fichiers internes'), 'true');

-- /!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!${symbol_escape} ATTENTION REMPLACER L'ADRESSE DU SERVICE PAR UNE ADRESSE DE TEST, SI ENVIRONNEMENT != PROD /!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!${symbol_escape}
-- Penser également à mettre email_from = email_service afin d'éviter que le secrétariat de la DAN (contact@gouv.mc) ne reçoive des e-mails de delivery failure
-- Pour DEVC + REC
INSERT INTO ${artifactIdUpper}.DEM_DEMARCHES VALUES ('${artifactIdUpper}','${tsFullName}','recettedae10@gouv.mc','Le Service de l’Inspection du Travail','noreply@gouv.mc','No-Reply','recettedae10@gouv.mc','Contact Téléservices Principauté de Monaco','DJF');

-- PROD (à dé-commenter lors de la MEP)
-- INSERT INTO ${artifactIdUpper}.DEM_DEMARCHES VALUES ('${artifactIdUpper}','${tsFullName}','inspectiondutravail@gouv.mc','Le Service de l’Inspection du Travail','noreply@gouv.mc','No-Reply','contact@gouv.mc','Contact Téléservices Principauté de Monaco','DJF');

-- MOTIFS - FR
------------------------------------------
-- Motifs - INFOS COMP
insert into ${artifactIdUpper}.DEM_MOTIFS values (default,'${artifactIdUpper}','L’avis des délégués du personnel est manquant','AVIS_DELEGUES_MANQUANT','EN_ATTENTE_COMPL','fr',null,
                                       'Afin de pouvoir traiter votre demande, je vous serais très obligée de bien vouloir me faire parvenir dans les meilleurs délais l’avis des délégués du personnel.');

insert into ${artifactIdUpper}.DEM_MOTIFS values (default,'${artifactIdUpper}','L’avis du personnel concerné est manquant ','AVIS_PERSONNEL_MANQUANT','EN_ATTENTE_COMPL','fr',null,
                                       'Afin de pouvoir traiter votre demande, je vous serais très obligée de bien vouloir me faire parvenir dans les meilleurs délais l’avis du personnel concerné.');

insert into ${artifactIdUpper}.DEM_MOTIFS values (default,'${artifactIdUpper}','Des informations complémentaires sont nécessaires','INFOS_COMP_NECESSAIRES','EN_ATTENTE_COMPL','fr',null,
                                       null);

insert into ${artifactIdUpper}.DEM_MOTIFS values (default,'${artifactIdUpper}','Autre','ATTENTE_COMPL_AUTRE','EN_ATTENTE_COMPL','fr',null,
                                       null);

-- Motifs - REFUSEE
insert into ${artifactIdUpper}.DEM_MOTIFS values (default,'${artifactIdUpper}','Avis défavorable des délégués du personnel','AVIS_DELEGUES_DEFAVORABLE','REFUSEE','fr',null,
                                       'Me référant à votre demande, j’ai le regret de vous informer que votre demande de dérogation relative aux jours fériés légaux ne peut vous être accordée en raison de l’avis défavorable émis par les délégués du personnel.');

insert into ${artifactIdUpper}.DEM_MOTIFS values (default,'${artifactIdUpper}','Avis défavorable des salariés concernés','AVIS_SALARIE_DEFAVORABLE','REFUSEE','fr',null,
                                       'Me référant à votre demande, j’ai le regret de vous informer que votre demande de dérogation relative aux jours fériés légaux ne peut vous être accordée en raison de l’avis défavorable émis par le personnel concerné.');

insert into ${artifactIdUpper}.DEM_MOTIFS values (default,'${artifactIdUpper}','Demande hors délai','DEMANDE_HORS_DELAIS','REFUSEE','fr',null,
                                       E'Me référant à votre communication, je suis au regret de vous informer qu’eu égard à la réception tardive de votre demande, il n’a pas été possible de réserver une suite favorable à votre requête.${symbol_escape}nA l’avenir, vous voudrez bien me faire parvenir vos demandes dans des délais me permettant de les instruire.');

insert into ${artifactIdUpper}.DEM_MOTIFS values (default,'${artifactIdUpper}','Refusée (Jours fériés particuliers) + accordée (Jours fériés)','AVIS_PERSONNEL_DEFAVORABLE','REFUSEE','fr',null,'Me référant à votre demande, j’ai l’honneur de vous informer que, sous réserve du respect des dispositions de l’article 7 de la Loi n. 800 du 18 février 1966 concernant la récupération ou la rémunération de cette/ces journée(s) de travail, la dérogation sollicitée vous est accordée afin de pouvoir occuper le personnel de votre établissement, le(s) : ${symbol_dollar}{joursFeriesList} En ce qui concerne le(s) jour(s) suivant(s) ${symbol_dollar}{joursFeriesExceptionnels}, j’ai le regret de vous informer qu’il n’est pas d’usage d’accorder de dérogation pour ce(s) jour(s), eu égard à leur importance et à leur caractère symbolique.');
insert into ${artifactIdUpper}.DEM_MOTIFS values (default,'${artifactIdUpper}','Autre','REFUSEE_AUTRE','REFUSEE','fr',null,'Me référant à votre demande, j’ai le regret de vous informer que votre demande de dérogation relative aux jours fériés légaux ne peut vous être accordée en raison « commentaire libre ».');

-- Motifs - ACCORDEE
insert into ${artifactIdUpper}.DEM_MOTIFS values (default,'${artifactIdUpper}','Accordée (Jours fériés)','ACCORDEE','ACCORDEE','fr',null,
                                       'Me référant à votre demande, j’ai l’honneur de vous informer que, sous réserve du respect des dispositions de l’article 7 de la Loi n. 800 du 18 février 1966 concernant la récupération ou la rémunération de cette/ces journée(s) de travail, la dérogation sollicitée vous est accordée afin de pouvoir occuper le personnel de votre établissement, le(s) : ${symbol_dollar}{joursFeriesList}');

insert into ${artifactIdUpper}.DEM_MOTIFS values (default,'${artifactIdUpper}','Accordée (Jours fériés + jours fériés particuliers)','ACCORDEE_ET_ACCORDEE_EXCEPTIONNEL','ACCORDEE','fr',null,
                                       'Me référant à votre demande, j’ai l’honneur de vous informer que, sous réserve du respect des dispositions de l’article 7 de la Loi n. 800 du 18 février 1966 concernant la récupération ou la rémunération de cette/ces journée(s) de travail, la dérogation sollicitée vous est accordée afin de pouvoir occuper le personnel de votre établissement, le(s) : ${symbol_dollar}{joursFeriesList}De même, j’ai l’honneur de vous informer que s’agissant du/des jours suivant(s) ${symbol_dollar}{joursFeriesExceptionnels}, une dérogation vous est accordée à titre exceptionnel, au regard de la nature de votre activité.');

insert into ${artifactIdUpper}.DEM_MOTIFS values (default,'${artifactIdUpper}','Accordée (Jours fériés particuliers)','ACCORDEE_EXCEPTIONNEL','ACCORDEE','fr',null,
                                       'Me référant à votre demande, j’ai l’honneur de vous informer que, sous réserve du respect des dispositions de l’article 7 de la Loi n. 800 du 18 février 1966 concernant la récupération ou la rémunération de cette/ces journée(s) de travail et à titre exceptionnel au regard de la nature de votre activité, la dérogation demandée vous est accordée afin de pouvoir occuper le personnel de votre établissement, le(s) : ${symbol_dollar}{joursFeriesExceptionnelsList}');

insert into ${artifactIdUpper}.DEM_MOTIFS values (default,'${artifactIdUpper}','Accordée (Jours fériés + chantier)','ACCORDEE_CHANTIER','ACCORDEE','fr',null,
                                       'Me référant à votre demande, j’ai l’honneur de vous informer que, sous réserve du respect des dispositions de l’article 7 de la Loi n. 800 du 18 février 1966 concernant la récupération ou la rémunération de cette/ces journée(s) de travail et des dispositions de l''Arrêté ministériel n. 2018-1116 du 3 décembre 2018 relatif à l''encadrement des chantiers, la dérogation sollicitée vous est accordée pour le personnel visé le(s): ${symbol_dollar}{joursFeriesList}');

insert into ${artifactIdUpper}.DEM_MOTIFS values (default,'${artifactIdUpper}','Accordée aux seules personnes ayant données leur accord','ACCORDEE_PERSONNES_ACCORD','ACCORDEE','fr',null,
                                       'Me référant à votre demande, j’ai l’honneur de vous informer que, sous réserve du respect des dispositions de l’article 7 de la Loi n. 800 du 18 février 1966 concernant la récupération ou la rémunération de cette/ces journée(s) de travail, la dérogation demandée vous est accordée afin de pouvoir occuper les salariés qui ont émis un avis favorable, le(s) : ${symbol_dollar}{joursFeriesList}');

insert into ${artifactIdUpper}.DEM_MOTIFS values (default,'${artifactIdUpper}','Accordée nonobstant l''avis défavorable des délégués du personnel','ACCORDEE_AVIS_DELEGUE_DEFAVORABLE','ACCORDEE','fr',null,
                                       'Me référant à votre demande, j’ai l’honneur de vous informer que, sous réserve du respect des dispositions de l’article 7 de la Loi n. 800 du 18 février 1966 concernant la récupération ou la rémunération de cette/ces journée(s) de travail et nonobstant l’avis défavorable des délégués du personnel, la dérogation demandée vous est accordée afin de pouvoir occuper le personnel de votre établissement, le(s) : ${symbol_dollar}{joursFeriesList}');

-- Motifs - ANNULEE
insert into ${artifactIdUpper}.DEM_MOTIFS values (default,'${artifactIdUpper}','Annulation par l''entreprise','ANNULATION_PAR_ENTREPRISE','ANNULEE','fr',null,null);
insert into ${artifactIdUpper}.DEM_MOTIFS values (default,'${artifactIdUpper}','Annulation par l''agent','ANNULATION_PAR_AGENT','ANNULEE','fr',null,null);
insert into ${artifactIdUpper}.DEM_MOTIFS values (default,'${artifactIdUpper}','Désinscription','ANNULATION_DESINSCRIPTION','ANNULEE','fr',null,null);


-- MOTIFS - EN
------------------------------------------
-- Motifs - INFOS COMP
insert into ${artifactIdUpper}.DEM_MOTIFS values (default,'${artifactIdUpper}','L’avis des délégués du personnel est manquant','AVIS_DELEGUES_MANQUANT','EN_ATTENTE_COMPL','en',null,
                                       'Afin de pouvoir traiter votre demande, je vous serais très obligée de bien vouloir me faire parvenir dans les meilleurs délais l’avis des délégués du personnel.');

insert into ${artifactIdUpper}.DEM_MOTIFS values (default,'${artifactIdUpper}','L’avis du personnel concerné est manquant ','AVIS_PERSONNEL_MANQUANT','EN_ATTENTE_COMPL','en',null,
                                       'Afin de pouvoir traiter votre demande, je vous serais très obligée de bien vouloir me faire parvenir dans les meilleurs délais l’avis du personnel concerné.');

insert into ${artifactIdUpper}.DEM_MOTIFS values (default,'${artifactIdUpper}','Des informations complémentaires sont nécessaires','INFOS_COMP_NECESSAIRES','EN_ATTENTE_COMPL','en',null,
                                       null);

insert into ${artifactIdUpper}.DEM_MOTIFS values (default,'${artifactIdUpper}','Autre','ATTENTE_COMPL_AUTRE','EN_ATTENTE_COMPL','en',null,
                                       null);

-- Motifs - REFUSEE
insert into ${artifactIdUpper}.DEM_MOTIFS values (default,'${artifactIdUpper}','Avis défavorable des délégués du personnel','AVIS_DELEGUES_DEFAVORABLE','REFUSEE','en',null,
                                       'Me référant à votre demande, j’ai le regret de vous informer que votre demande de dérogation relative aux jours fériés légaux ne peut vous être accordée en raison de l’avis défavorable émis par les délégués du personnel.');

insert into ${artifactIdUpper}.DEM_MOTIFS values (default,'${artifactIdUpper}','Avis défavorable des salariés concernés','AVIS_SALARIE_DEFAVORABLE','REFUSEE','en',null,
                                       'Me référant à votre demande, j’ai le regret de vous informer que votre demande de dérogation relative aux jours fériés légaux ne peut vous être accordée en raison de l’avis défavorable émis par le personnel concerné.');

insert into ${artifactIdUpper}.DEM_MOTIFS values (default,'${artifactIdUpper}','Demande hors délai','DEMANDE_HORS_DELAIS','REFUSEE','en',null,
                                       E'Me référant à votre communication, je suis au regret de vous informer qu’eu égard à la réception tardive de votre demande, il n’a pas été possible de réserver une suite favorable à votre requête.${symbol_escape}nA l’avenir, vous voudrez bien me faire parvenir vos demandes dans des délais me permettant de les instruire.');

insert into ${artifactIdUpper}.DEM_MOTIFS values (default,'${artifactIdUpper}','Refusée (Jours fériés particuliers) + accordée (Jours fériés)','AVIS_PERSONNEL_DEFAVORABLE','REFUSEE','en',null,
                                       'Me référant à votre demande, j’ai l’honneur de vous informer que, sous réserve du respect des dispositions de l’article 7 de la Loi n. 800 du 18 février 1966 concernant la récupération ou la rémunération de cette/ces journée(s) de travail, la dérogation sollicitée vous est accordée afin de pouvoir occuper le personnel de votre établissement, le(s) : ${symbol_dollar}{joursFeriesList} En ce qui concerne le(s) jour(s) suivant(s) ${symbol_dollar}{joursFeriesExceptionnels}, j’ai le regret de vous informer qu’il n’est pas d’usage d’accorder de dérogation pour ce(s) jour(s), eu égard à leur importance et à leur caractère symbolique.');

insert into ${artifactIdUpper}.DEM_MOTIFS values (default,'${artifactIdUpper}','Autre','REFUSEE_AUTRE','REFUSEE','en',null,
                                       'Me référant à votre demande, j’ai le regret de vous informer que votre demande de dérogation relative aux jours fériés légaux ne peut vous être accordée en raison « commentaire libre ».');

-- Motifs - ACCORDEE
insert into ${artifactIdUpper}.DEM_MOTIFS values (default,'${artifactIdUpper}','Accordée (Jours fériés)','ACCORDEE','ACCORDEE','en',null,
                                       'Me référant à votre demande, j’ai l’honneur de vous informer que, sous réserve du respect des dispositions de l’article 7 de la Loi n. 800 du 18 février 1966 concernant la récupération ou la rémunération de cette/ces journée(s) de travail, la dérogation sollicitée vous est accordée afin de pouvoir occuper le personnel de votre établissement, le(s) : ${symbol_dollar}{joursFeriesList}');

insert into ${artifactIdUpper}.DEM_MOTIFS values (default,'${artifactIdUpper}','Accordée (Jours fériés + jours fériés particuliers)','ACCORDEE_ET_ACCORDEE_EXCEPTIONNEL','ACCORDEE','en',null,
                                       'Me référant à votre demande, j’ai l’honneur de vous informer que, sous réserve du respect des dispositions de l’article 7 de la Loi n. 800 du 18 février 1966 concernant la récupération ou la rémunération de cette/ces journée(s) de travail, la dérogation sollicitée vous est accordée afin de pouvoir occuper le personnel de votre établissement, le(s) : ${symbol_dollar}{joursFeriesList}De même, j’ai l’honneur de vous informer que s’agissant du/des jours suivant(s) ${symbol_dollar}{joursFeriesExceptionnels}, une dérogation vous est accordée à titre exceptionnel, au regard de la nature de votre activité.');

insert into ${artifactIdUpper}.DEM_MOTIFS values (default,'${artifactIdUpper}','Accordée (Jours fériés particuliers)','ACCORDEE_EXCEPTIONNEL','ACCORDEE','en',null,
                                       'Me référant à votre demande, j’ai l’honneur de vous informer que, sous réserve du respect des dispositions de l’article 7 de la Loi n. 800 du 18 février 1966 concernant la récupération ou la rémunération de cette/ces journée(s) de travail et à titre exceptionnel au regard de la nature de votre activité, la dérogation demandée vous est accordée afin de pouvoir occuper le personnel de votre établissement, le(s) : ${symbol_dollar}{joursFeriesExceptionnelsList}');

insert into ${artifactIdUpper}.DEM_MOTIFS values (default,'${artifactIdUpper}','Accordée (Jours fériés + chantier)','ACCORDEE_CHANTIER','ACCORDEE','en',null,
                                       'Me référant à votre demande, j’ai l’honneur de vous informer que, sous réserve du respect des dispositions de l’article 7 de la Loi n. 800 du 18 février 1966 concernant la récupération ou la rémunération de cette/ces journée(s) de travail et des dispositions de l''Arrêté ministériel n. 2018-1116 du 3 décembre 2018 relatif à l''encadrement des chantiers, la dérogation sollicitée vous est accordée pour le personnel visé le(s): ${symbol_dollar}{joursFeriesList}');

insert into ${artifactIdUpper}.DEM_MOTIFS values (default,'${artifactIdUpper}','Accordée aux seules personnes ayant données leur accord','ACCORDEE_PERSONNES_ACCORD','ACCORDEE','en',null,
                                       'Me référant à votre demande, j’ai l’honneur de vous informer que, sous réserve du respect des dispositions de l’article 7 de la Loi n. 800 du 18 février 1966 concernant la récupération ou la rémunération de cette/ces journée(s) de travail, la dérogation demandée vous est accordée afin de pouvoir occuper les salariés qui ont émis un avis favorable, le(s) : ${symbol_dollar}{joursFeriesList}');

insert into ${artifactIdUpper}.DEM_MOTIFS values (default,'${artifactIdUpper}','Accordée nonobstant l''avis défavorable des délégués du personnel','ACCORDEE_AVIS_DELEGUE_DEFAVORABLE','ACCORDEE','en',null,
                                       'Me référant à votre demande, j’ai l’honneur de vous informer que, sous réserve du respect des dispositions de l’article 7 de la Loi n. 800 du 18 février 1966 concernant la récupération ou la rémunération de cette/ces journée(s) de travail et nonobstant l’avis défavorable des délégués du personnel, la dérogation demandée vous est accordée afin de pouvoir occuper le personnel de votre établissement, le(s) : ${symbol_dollar}{joursFeriesList}');

-- Motifs - ANNULEE
insert into ${artifactIdUpper}.DEM_MOTIFS values (default,'${artifactIdUpper}','Annulation par l''entreprise','ANNULATION_PAR_ENTREPRISE','ANNULEE','en',null,null);
insert into ${artifactIdUpper}.DEM_MOTIFS values (default,'${artifactIdUpper}','Annulation par l''agent','ANNULATION_PAR_AGENT','ANNULEE','en',null,null);
insert into ${artifactIdUpper}.DEM_MOTIFS values (default,'${artifactIdUpper}','Désinscription','ANNULATION_DESINSCRIPTION','ANNULEE','en',null,null);


-- MAILS - FR
------------------------------------------

-- Mails Usagers
insert into ${artifactIdUpper}.DEM_TEMPLATES values (default, '${artifactIdUpper}', 'MAIL_CREATION_DEMANDE_USAGER_OBJET', 'Accusé de réception de votre demande ${symbol_dollar}{identifiant}', 'fr');
insert into ${artifactIdUpper}.DEM_TEMPLATES values (default, '${artifactIdUpper}', 'MAIL_CREATION_DEMANDE_USAGER_CORPS', 'Madame, Monsieur,<br/><br/>Nous avons bien reçu votre demande de dérogation relative aux jours fériés légaux n°<a href="${symbol_dollar}{urlFront}demande_view.html?id=${symbol_dollar}{pkDemande}">${symbol_dollar}{identifiant}</a>.<br/><br/>Vous pouvez consulter votre demande en cliquant sur <a href="${symbol_dollar}{urlFront}">ce lien</a>.<br/><br/>Nous allons traiter votre demande.<br/><br/>Cordialement.<br/><br/>Service de l’Inspection du Travail<br/>La Frégate<br/>2, rue Princesse Antoinette<br/>98000 Monaco<br/>(+377) 98 98 87 26<br/>inspectiondutravail@gouv.mc<br/><br/>Ce message a été envoyé automatiquement. Nous vous remercions de ne pas y répondre.<br/>Si vous n''êtes pas à l''origine de cette demande, veuillez simplement ignorer ce message.', 'fr');

insert into ${artifactIdUpper}.DEM_TEMPLATES values (default, '${artifactIdUpper}', 'MAIL_ACTION_DEMANDEIC_OBJET', 'Compléter votre demande ${symbol_dollar}{identifiant}', 'fr');
insert into ${artifactIdUpper}.DEM_TEMPLATES values (default, '${artifactIdUpper}', 'MAIL_ACTION_DEMANDEIC_CORPS', 'Madame, Monsieur,<br/><br/>Afin de pouvoir traiter votre demande n° ${symbol_dollar}{identifiant}, nous vous serions très obligés de bien vouloir nous faire parvenir dans les meilleurs délais la/les pièce(s) justificative(s) manquante(s).<br/><br/>Pour compléter votre demande par la démarche en ligne, veuillez-vous connecter au téléservice « Demander une dérogation relative aux jours fériés légaux ».<br/><br/>Pour vous connecter au téléservice cliquer sur <a href="${symbol_dollar}{urlFront}">ce lien</a>.<br/><br/>Cordialement.<br/><br/>Service de l’Inspection du Travail<br/>La Frégate<br/>2, rue Princesse Antoinette<br/>98000 Monaco<br/>(+377) 98 98 87 26<br/>inspectiondutravail@gouv.mc<br/><br/>Ce message a été envoyé automatiquement. Nous vous remercions de ne pas y répondre.<br/>Si vous n''êtes pas à l''origine de cette demande, veuillez simplement ignorer ce message.', 'fr');

insert into ${artifactIdUpper}.DEM_TEMPLATES values (default, '${artifactIdUpper}', 'MAIL_ACTION_ACCORDEE_OBJET', 'Votre demande ${symbol_dollar}{identifiant}', 'fr');
insert into ${artifactIdUpper}.DEM_TEMPLATES values (default, '${artifactIdUpper}', 'MAIL_ACTION_ACCORDEE_CORPS', 'Madame, Monsieur,<br/><br/>Le Service de l’Inspection du Travail a le plaisir de vous informer que votre demande de dérogation relative aux jours fériés légaux n° ${symbol_dollar}{identifiant} est accordée.<br/><br/>Vous pouvez consulter votre demande et télécharger votre justificatif de dérogation relative aux jours fériés légaux, en ligne, sur le téléservice « Demander une dérogation relative aux jours fériés légaux ».<br/><br/>Pour vous connecter au téléservice cliquer sur <a href="${symbol_dollar}{urlFront}">ce lien</a>.<br/><br/>Cordialement.<br/><br/>Service de l’Inspection du Travail<br/>La Frégate<br/>2, rue Princesse Antoinette<br/>98000 Monaco<br/>(+377) 98 98 87 26<br/>inspectiondutravail@gouv.mc<br/><br/>Ce message a été envoyé automatiquement. Nous vous remercions de ne pas y répondre.<br/>Si vous n''êtes pas à l''origine de cette demande, veuillez simplement ignorer ce message.', 'fr');

insert into ${artifactIdUpper}.DEM_TEMPLATES values (default, '${artifactIdUpper}', 'MAIL_CONFIRMATION_ACTION_ANNULER_OBJET', 'Votre demande ${symbol_dollar}{identifiant}', 'fr');
insert into ${artifactIdUpper}.DEM_TEMPLATES values (default, '${artifactIdUpper}', 'MAIL_CONFIRMATION_ACTION_ANNULER_CORPS', 'Madame, Monsieur,<br/><br/>Le Service de l’Inspection du Travail a bien pris en compte l’annulation de votre demande de dérogation relative aux jours fériés légaux n° ${symbol_dollar}{identifiant}.<br/><br/>Vous pouvez consulter votre demande, en ligne, sur le téléservice « Demander une dérogation relative aux jours fériés légaux ».<br/><br/>Pour vous connecter au téléservice cliquer sur <a href="${symbol_dollar}{urlFront}">ce lien</a>.<br/><br/>Cordialement.<br/><br/>Service de l’Inspection du Travail<br/>La Frégate<br/>2, rue Princesse Antoinette<br/>98000 Monaco<br/>(+377) 98 98 87 26<br/>inspectiondutravail@gouv.mc<br/><br/>Ce message a été envoyé automatiquement. Nous vous remercions de ne pas y répondre.<br/>Si vous n''êtes pas à l''origine de cette demande, veuillez simplement ignorer ce message.', 'fr');

insert into ${artifactIdUpper}.DEM_TEMPLATES values (default, '${artifactIdUpper}', 'MAIL_ACTION_REFUSER_OBJET', 'Votre demande ${symbol_dollar}{identifiant}', 'fr');
insert into ${artifactIdUpper}.DEM_TEMPLATES values (default, '${artifactIdUpper}', 'MAIL_ACTION_REFUSER_CORPS', 'Madame, Monsieur,<br/><br/>Le Service de l’Inspection du Travail a le regret de vous informer que votre demande de dérogation relative aux jours fériés légaux n° ${symbol_dollar}{identifiant} est refusée.<br/><br/>Vous pouvez consulter votre demande et télécharger votre justificatif de refus, en ligne, sur le téléservice « Demander une dérogation relative aux jours fériés légaux ».<br/><br/>Pour vous connecter au téléservice cliquer sur <a href="${symbol_dollar}{urlFront}">ce lien</a>.<br/><br/>Cordialement.<br/><br/>Service de l’Inspection du Travail<br/>La Frégate<br/>2, rue Princesse Antoinette<br/>98000 Monaco<br/>(+377) 98 98 87 26<br/>inspectiondutravail@gouv.mc<br/><br/>Ce message a été envoyé automatiquement. Nous vous remercions de ne pas y répondre.<br/>Si vous n''êtes pas à l''origine de cette demande, veuillez simplement ignorer ce message.', 'fr');

insert into ${artifactIdUpper}.DEM_TEMPLATES values (default, '${artifactIdUpper}', 'MAIL_DESINSCRIPTION_USAGER_POUR_USAGER_OBJET', 'Désinscription du téléservice "Demander une dérogation relative aux jours fériés légaux"', 'fr');
insert into ${artifactIdUpper}.DEM_TEMPLATES values (default, '${artifactIdUpper}', 'MAIL_DESINSCRIPTION_USAGER_POUR_USAGER_CORPS', 'Madame, Monsieur,<br/><br/>Nous vous confirmons votre désinscription du téléservice "Demander une dérogation relative aux jours fériés légaux" sur votre compte Téléservices Principauté de Monaco pour l''identifiant ${symbol_dollar}{identifiant_usager} (voir les <a href="https://teleservice.gouv.mc/${tsFrontUrl}/legalterms.html">Conditions Générales d''Utilisation</a>).<br/><br/>Cordialement.<br/><br/>Service de l’Inspection du Travail<br/>La Frégate<br/>2, rue Princesse Antoinette<br/>98000 Monaco<br/>(+377) 98 98 87 26<br/>inspectiondutravail@gouv.mc<br/><br/>Ce message a été envoyé automatiquement. Nous vous remercions de ne pas y répondre.<br/>Si vous n''êtes pas à l''origine de cette demande, veuillez simplement ignorer ce message.', 'fr');

-- Mails Agents
insert into ${artifactIdUpper}.DEM_TEMPLATES values (default, '${artifactIdUpper}', 'MAIL_NOTIFICATION_REPONSE_IC_PAR_USAGER_OBJET', 'La demande ${symbol_dollar}{identifiant} a été complétée', 'fr');
insert into ${artifactIdUpper}.DEM_TEMPLATES values (default, '${artifactIdUpper}', 'MAIL_NOTIFICATION_REPONSE_IC_PAR_USAGER_CORPS', 'Bonjour,<br/><br/>La demande ${symbol_dollar}{identifiant} a été complétée. Vous pouvez la consulter <a href="${symbol_dollar}{urlBack}">à cette adresse</a> dans le tableau des demandes en cours de traitement.<br/><br/>Notification automatique', 'fr');

insert into ${artifactIdUpper}.DEM_TEMPLATES values (default, '${artifactIdUpper}', 'MAIL_NOTIFICATION_REPONSE_IC_PAR_AGENT_OBJET', 'La demande ${symbol_dollar}{identifiant} a été complétée', 'fr');
insert into ${artifactIdUpper}.DEM_TEMPLATES values (default, '${artifactIdUpper}', 'MAIL_NOTIFICATION_REPONSE_IC_PAR_AGENT_CORPS', 'Bonjour,<br/><br/>La demande ${symbol_dollar}{identifiant} a été complétée par ${symbol_dollar}{utilisateur}. Vous pouvez la consulter <a href="${symbol_dollar}{urlBack}">à cette adresse</a> dans le tableau des demandes en cours de traitement.<br/><br/>Notification automatique', 'fr');

insert into ${artifactIdUpper}.DEM_TEMPLATES values (default, '${artifactIdUpper}', 'MAIL_NOTIFICATION_ATTENTE_VALIDATION_OBJET', 'La demande ${symbol_dollar}{identifiant} est en attente de validation hiérarchique', 'fr');
insert into ${artifactIdUpper}.DEM_TEMPLATES values (default, '${artifactIdUpper}', 'MAIL_NOTIFICATION_ATTENTE_VALIDATION_CORPS', 'Bonjour,<br/><br/>La demande ${symbol_dollar}{identifiant} vient d’être refusée et nécessite votre validation hiérarchique. Vous pouvez la consulter <a href="${symbol_dollar}{urlBack}">à cette adresse</a>.<br/><br/>Notification automatique', 'fr');

insert into ${artifactIdUpper}.DEM_TEMPLATES values (default, '${artifactIdUpper}', 'MAIL_NOTIFICATION_ANNULATION_DEMANDE_PAR_USAGER_OBJET', 'La demande ${symbol_dollar}{identifiant} a été annulée', 'fr');
insert into ${artifactIdUpper}.DEM_TEMPLATES values (default, '${artifactIdUpper}', 'MAIL_NOTIFICATION_ANNULATION_DEMANDE_PAR_USAGER_CORPS', 'Bonjour,<br/><br/>L''usager ${symbol_dollar}{usager} vient d''annuler sa demande ${symbol_dollar}{identifiant}.<br/><br/>Vous pouvez la consulter à cette <a href="${symbol_dollar}{urlBack}/demandes/${symbol_dollar}{pkDemande}">adresse</a>.<br/><br/>Notification automatique', 'fr');

insert into ${artifactIdUpper}.DEM_TEMPLATES values (default, '${artifactIdUpper}', 'MAIL_DESINSCRIPTION_USAGER_OBJET', 'Désinscription de l''usager ${symbol_dollar}{usager}', 'fr');
insert into ${artifactIdUpper}.DEM_TEMPLATES values (default, '${artifactIdUpper}', 'MAIL_DESINSCRIPTION_USAGER_CORPS', 'Bonjour,<br/><br/>L''usager ${symbol_dollar}{usager} vient de se désinscrire de la démarche.<br/><br/>Par conséquent, les demandes suivantes sont passées à l''état "Annulée" :<br/>${symbol_dollar}{demandes}<br/><br/>Notification automatique', 'fr');

-- MAILS - EN
------------------------------------------

-- Mails Usagers
insert into ${artifactIdUpper}.DEM_TEMPLATES values (default, '${artifactIdUpper}', 'MAIL_CREATION_DEMANDE_USAGER_OBJET', 'Acknowledgement of receipt of your application  ${symbol_dollar}{identifiant}', 'en');
insert into ${artifactIdUpper}.DEM_TEMPLATES values (default, '${artifactIdUpper}', 'MAIL_CREATION_DEMANDE_USAGER_CORPS', 'Madam, Sir,<br/><br/>We have received your application for an exemption to statutory public holidays no. <a href="${symbol_dollar}{urlFront}demande_view.html?id=${symbol_dollar}{pkDemande}">${symbol_dollar}{identifiant}</a>.<br/><br/>You can consult your request by clicking <a href="${symbol_dollar}{urlFront}">on this link</a><br/><br/>We will now process your application.<br/><br/>Kind regards.<br/><br/>Service de l’Inspection du Travail<br/>La Frégate<br/>2, rue Princesse Antoinette<br/>98000 Monaco<br/>(+377) 98 98 87 26<br/>inspectiondutravail@gouv.mc<br/><br/>This message has been sent automatically. Please do not reply to it.<br/>If you did not send this request, please simply ignore this message.', 'en');

insert into ${artifactIdUpper}.DEM_TEMPLATES values (default, '${artifactIdUpper}', 'MAIL_ACTION_DEMANDEIC_OBJET', 'Complete your application ${symbol_dollar}{identifiant}', 'en');
insert into ${artifactIdUpper}.DEM_TEMPLATES values (default, '${artifactIdUpper}', 'MAIL_ACTION_DEMANDEIC_CORPS', 'Madam, Sir,<br/><br/>To enable us to process your application no. ${symbol_dollar}{identifiant}, we would be grateful if you could send us the missing supporting document(s) as soon as possible.<br/><br/>Please log in to the online service: “Requesting an exemption to statutory public holidays” in order to complete your application online.<br/><br/>To connect to the online service, click <a href="${symbol_dollar}{urlFront}">on this link</a>.<br/><br/>Kind regards.<br/><br/>Service de l’Inspection du Travail<br/>La Frégate<br/>2, rue Princesse Antoinette<br/>98000 Monaco<br/>(+377) 98 98 87 26<br/>inspectiondutravail@gouv.mc<br/><br/>This message has been sent automatically. Please do not reply to it.<br/>If you did not send this request, please simply ignore this message.', 'en');

insert into ${artifactIdUpper}.DEM_TEMPLATES values (default, '${artifactIdUpper}', 'MAIL_ACTION_ACCORDEE_OBJET', 'Your application ${symbol_dollar}{identifiant}', 'en');
insert into ${artifactIdUpper}.DEM_TEMPLATES values (default, '${artifactIdUpper}', 'MAIL_ACTION_ACCORDEE_CORPS', 'Madam, Sir,<br/><br/>The Labour Inspectorate is pleased to inform you that your application for an exemption to statutory public holidays no. ${symbol_dollar}{identifiant} has been successful.<br/><br/>You can view your application and download your exemption confirmation online using the online service: “Requesting an exemption to statutory public holidays”.<br/><br/>To connect to the online service, click <a href="${symbol_dollar}{urlFront}">on this link</a>.<br/><br/>Kind regards.<br/><br/>Service de l’Inspection du Travail<br/>La Frégate<br/>2, rue Princesse Antoinette<br/>98000 Monaco<br/>(+377) 98 98 87 26<br/>inspectiondutravail@gouv.mc<br/><br/>This message has been sent automatically. Please do not reply to it.<br/>If you did not send this request, please simply ignore this message.', 'en');

insert into ${artifactIdUpper}.DEM_TEMPLATES values (default, '${artifactIdUpper}', 'MAIL_ACTION_REFUSER_OBJET', 'Your application ${symbol_dollar}{identifiant}', 'en');
insert into ${artifactIdUpper}.DEM_TEMPLATES values (default, '${artifactIdUpper}', 'MAIL_ACTION_REFUSER_CORPS', 'Madam, Sir,<br/><br/>The Labour Inspectorate regrets to inform you that your application for an exemption to statutory public holidays no. ${symbol_dollar}{identifiant} has been rejected.<br/><br/>You can view your application and download your rejection notice online using the online service: “Requesting an exemption to statutory public holidays”.<br/><br/>To connect to the online service, click <a href="${symbol_dollar}{urlFront}">on this link</a>.<br/><br/>Kind regards.<br/><br/>Service de l’Inspection du Travail<br/>La Frégate<br/>2, rue Princesse Antoinette<br/>98000 Monaco<br/>(+377) 98 98 87 26<br/>inspectiondutravail@gouv.mc<br/><br/>This message has been sent automatically. Please do not reply to it.<br/>If you did not send this request, please simply ignore this message.', 'en');

insert into ${artifactIdUpper}.DEM_TEMPLATES values (default, '${artifactIdUpper}', 'MAIL_CONFIRMATION_ACTION_ANNULER_OBJET', 'Your application ${symbol_dollar}{identifiant}', 'en');
insert into ${artifactIdUpper}.DEM_TEMPLATES values (default, '${artifactIdUpper}', 'MAIL_CONFIRMATION_ACTION_ANNULER_CORPS', 'Madam, Sir,<br/><br/>The Labour Inspectorate has noted the cancellation of your application for an exemption to statutory public holidays no. ${symbol_dollar}{identifiant}.<br/><br/>You can view your application online using the online service: “Requesting an exemption to statutory public holidays”.<br/><br/>To connect to the online service, click <a href="${symbol_dollar}{urlFront}">on this link</a>.<br/><br/>Kind regards.<br/><br/>Service de l’Inspection du Travail<br/>La Frégate<br/>2, rue Princesse Antoinette<br/>98000 Monaco<br/>(+377) 98 98 87 26<br/>inspectiondutravail@gouv.mc<br/><br/>This message has been sent automatically. Please do not reply to it.<br/>If you did not send this request, please simply ignore this message.', 'en');

insert into ${artifactIdUpper}.DEM_TEMPLATES values (default, '${artifactIdUpper}', 'MAIL_DESINSCRIPTION_USAGER_POUR_USAGER_OBJET', 'Unsubscribe from online service: “Requesting an exemption to statutory public holidays”', 'en');
insert into ${artifactIdUpper}.DEM_TEMPLATES values (default, '${artifactIdUpper}', 'MAIL_DESINSCRIPTION_USAGER_POUR_USAGER_CORPS', 'Madam, Sir,<br/><br/>We confirm that you have unsubscribed from the online service: “Requesting an exemption to statutory public holidays” on your account with the Principality of Monaco''s online services for the identifier ${symbol_dollar}{identifiant_usager} (see the General Terms of Use, which are available on <a href="https://teleservice.gouv.mc/${tsFrontUrl}/legalterms.html">this page </a>).<br/><br/>Kind regards.<br/><br/>Service de l’Inspection du Travail<br/>La Frégate<br/>2, rue Princesse Antoinette<br/>98000 Monaco<br/>(+377) 98 98 87 26<br/>inspectiondutravail@gouv.mc<br/><br/>This message has been sent automatically. Please do not reply to it.<br/>If you did not send this request, please simply ignore this message.', 'en');

-- Fin scripts "Data"