# Voir la description dans les fichiers templates "src\main\resources\templates\generic\${tscode}-rec"

# code du téléservice en lowercase
tscode=[tscode à renseigner]

# code du téléservice en uppercase
TSCODE=[TSCODE à renseigner]

# Deux premiers chiffre du port du téléservice (ex. 79 pour 790)
TSPORT=[TSPORT à renseigner]

# Contexte du téléservice sans le slash (ex. subvention-vehicule-ecologique)
TSCONTEXTE=[TSCONTEXTE à renseigner]

# Code du tracking piwik back
TSPWKB=[TSPWKB à renseigner]

# Code du tracking piwik front
TSPWKF=[TSPWKF à renseigner]

# Token JWT File
TSFILEJWT=[TSFILEJWT à renseigner]

#  Token JWT Mail
TSMAILJWT=[TSMAILJWT à renseigner]

# Secret pour les Token JWT Api
TSAPISECRET=[TSAPISECRET à renseigner]

# Token JWT Api pour le front
TSAPIJWT=[TSAPIJWT à renseigner]

# Password postgres
TSPGPWD=[TSPGPWD à renseigner]

# Clef partagé entre le front et le back
TSFRONTKEY=[TSFRONTKEY à renseigner]

# nom du serveur appl dans zabbix
TSAPPLZABBIX=[TSAPPLZABBIX à renseigner]

# nom du serveur frnt dans zabbix
TSFRNTZABBIX=[TSAPPLZABBIX à renseigner]
