<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>mc.gouv.xaf</groupId>
        <artifactId>xaf</artifactId>
        <version>10.2.0</version>
    </parent>

    <artifactId>xaf-backweb</artifactId>

    <dependencies>
        <dependency>
            <groupId>mc.gouv.xaf</groupId>
            <artifactId>xaf-back</artifactId>
            <version>10.2.0</version>
        </dependency>

        <dependency>
            <groupId>mc.gouv.xboot</groupId>
            <artifactId>xboot-spring-starter-web</artifactId>
        </dependency>

        <!-- Web JS and CSS dependencies -->
        <dependency>
            <groupId>org.webjars</groupId>
            <artifactId>Eonasdan-bootstrap-datetimepicker</artifactId>
            <version>4.17.47</version>
        </dependency>
        <dependency>
    		<groupId>org.webjars</groupId>
    		<artifactId>Magnific-Popup</artifactId>
    		<version>1.1.0</version>
		</dependency>
		<dependency>
			<groupId>org.apache.pdfbox</groupId>
			<artifactId>pdfbox-tools</artifactId>
			<version>2.0.25</version>
		</dependency>
		<dependency>
			<groupId>org.apache.pdfbox</groupId>
			<artifactId>jbig2-imageio</artifactId>
			<version>3.0.2</version>
		</dependency>


	</dependencies>

</project>

