## Maven properties
maven.name=${project.name}
maven.version=${project.version}
maven.build.date=${buildTimestamp}

#spring.jpa.show-sql = true

# Pour afficher les valeurs des paramètres des requêtes SQL
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Pour afficher les logs debug de Spring (autowiring troubleshooting etc.)
#logging.level.org.springframework = DEBUG


