# Voir la description dans les fichiers templates "src\main\resources\templates\generic\${tscode}-dev"

# code du téléservice en lowercase
tscode=[tscode à renseigner]

# code du téléservice en uppercase
TSCODE=[TSCODE à renseigner]

#Deux premiers chiffre du port du téléservice (ex. 79 pour 790)
TSPORT=[TSPORT à renseigner]

# Contexte du téléservice sans le slash (ex. derogation-pause-femme)
TSCONTEXTE=[TSCONTEXTE à renseigner]

# Code du tracking piwik back
TSPWKB=[TSPWKB à renseigner]

# Code du tracking piwik front
TSPWKF=[TSPWKF à renseigner]

# Token JWT File
TSFILEJWT=[TSFILEJWT à renseigner]

# Token JWT Mail
TSMAILJWT=[TSMAILJWT à renseigner]

# Secret pour les Token JWT Api (35 cars.)
TSAPISECRET=[TSAPISECRET à renseigner]

# Token JWT Api pour le front
TSAPIJWT=[TSAPIJWT à renseigner]

# Password postgres
TSPGPWD=[TSPGPWD sera fourni par le DBA]

# Clef partagà entre le front et le back (35 cars.)
TSFRONTKEY=[TSFRONTKEY à renseigner]

# nom du serveur appl dans zabbix
TSAPPLZABBIX=[TSAPPLZABBIX à renseigner]

# nom du serveur frnt dans zabbix
TSFRNTZABBIX=[TSFRNTZABBIX à renseigner]

#URL du service de vérification des IBAN pour l'accès à TGF
TGFAPIURL=NULL

#Token JWT pour l'accès à TGF
TGFAPIJWTKEY=NULL

# valeur 'xms' par defaut
XMS=128m

# valeur 'xmx' par defaut
XMX=256m

# URL Lien vers la fiche demarche (FR)
URLFICHEDEMFR=

# URL Lien sondage (FR)
URLSONDAGEFR=

# URL Lien sondage (FR)
URLABDSONDAGEFR=

# URL lien Journal Officiel pour la demarche (FR)
URLJODEMFR=

#URL lien Journal Officiel CCIN (FR)
URLJOCCINFR=

# URL Lien vers la fiche demarche (EN)
URLFICHEDEMEN=

# URL Lien sondage (EN)
URLSONDAGEEN=

# URL Lien sondage (EN)
URLABDSONDAGEEN=

# URL lien Journal Officiel pour la demarche (EN)
URLJODEMEN=

#URL lien Journal Officiel CCIN (EN)
URLJOCCINEN=

#URL redirection après création de demande coté BO. Valeurs possible etape_usager.html (pour les TS destinés aux particuliers), etape_entreprise.html (pour les TS destinés aux entreprise)
BACKSRVFRNTFORMSTPAGE=

# URL CGU en Français
CGUURLFR=

# URL CGU en Anglais
CGUURLEN=

# JWT VSCAN
VSCANAPIJWT=
