
--engine
GRANT SELECT, INSERT, DELETE, UPDATE ON TABLE "${SCHEMA}"."ACT_GE_PROPERTY" TO USER ${USER};
GRANT SELECT, INSERT, DELETE, UPDATE ON TABLE "${SCHEMA}"."ACT_GE_BYTEARRAY" TO USER ${USER};
GRANT SELECT, INSERT, DELETE, UPDATE ON TABLE "${SCHEMA}"."ACT_RE_DEPLOYMENT" TO USER ${USER};
GRANT SELECT, INSERT, DELETE, UPDATE ON TABLE "${SCHEMA}"."ACT_RE_MODEL" TO USER ${USER};
GRANT SELECT, INSERT, DELETE, UPDATE ON TABLE "${SCHEMA}"."ACT_RU_EXECUTION" TO USER ${USER};
GRANT SELECT, INSERT, DELETE, UPDATE ON TABLE "${SCHEMA}"."ACT_RU_JOB" TO USER ${USER};
GRANT SELECT, INSERT, DELETE, UPDATE ON TABLE "${SCHEMA}"."ACT_RE_PROCDEF" TO USER ${USER};
GRANT SELECT, INSERT, DELETE, UPDATE ON TABLE "${SCHEMA}"."ACT_RU_TASK" TO USER ${USER};
GRANT SELECT, INSERT, DELETE, UPDATE ON TABLE "${SCHEMA}"."ACT_RU_IDENTITYLINK" TO USER ${USER};
GRANT SELECT, INSERT, DELETE, UPDATE ON TABLE "${SCHEMA}"."ACT_RU_VARIABLE" TO USER ${USER};
GRANT SELECT, INSERT, DELETE, UPDATE ON TABLE "${SCHEMA}"."ACT_RU_EVENT_SUBSCR" TO USER ${USER};
GRANT SELECT, INSERT, DELETE, UPDATE ON TABLE "${SCHEMA}"."ACT_EVT_LOG" TO USER ${USER};
GRANT SELECT, INSERT, DELETE, UPDATE ON TABLE "${SCHEMA}"."ACT_PROCDEF_INFO" TO USER ${USER};

--history

GRANT SELECT, INSERT, DELETE, UPDATE ON TABLE "${SCHEMA}"."ACT_HI_PROCINST" TO USER ${USER};
GRANT SELECT, INSERT, DELETE, UPDATE ON TABLE "${SCHEMA}"."ACT_HI_ACTINST" TO USER ${USER};
GRANT SELECT, INSERT, DELETE, UPDATE ON TABLE "${SCHEMA}"."ACT_HI_TASKINST" TO USER ${USER};
GRANT SELECT, INSERT, DELETE, UPDATE ON TABLE "${SCHEMA}"."ACT_HI_DETAIL" TO USER ${USER};
GRANT SELECT, INSERT, DELETE, UPDATE ON TABLE "${SCHEMA}"."ACT_HI_COMMENT" TO USER ${USER};
GRANT SELECT, INSERT, DELETE, UPDATE ON TABLE "${SCHEMA}"."ACT_HI_ATTACHMENT" TO USER ${USER};
GRANT SELECT, INSERT, DELETE, UPDATE ON TABLE "${SCHEMA}"."ACT_HI_IDENTITYLINK" TO USER ${USER};
GRANT SELECT, INSERT, DELETE, UPDATE ON TABLE "${SCHEMA}"."ACT_HI_VARINST" TO USER ${USER};


--identity
GRANT SELECT, INSERT, DELETE, UPDATE ON TABLE "${SCHEMA}"."ACT_ID_GROUP" TO USER ${USER};
GRANT SELECT, INSERT, DELETE, UPDATE ON TABLE "${SCHEMA}"."ACT_ID_MEMBERSHIP" TO USER ${USER};
GRANT SELECT, INSERT, DELETE, UPDATE ON TABLE "${SCHEMA}"."ACT_ID_USER" TO USER ${USER};
GRANT SELECT, INSERT, DELETE, UPDATE ON TABLE "${SCHEMA}"."ACT_ID_INFO" TO USER ${USER};






