#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
${symbol_pound} URL de redirection vers le front pour la création des demandes en tant qu'usager
${groupId}.backserver.front.url=http://localhost:${tsFrontPort}/${tsFrontUrl}/
${groupId}.backserver.front.formstartpage=etape_entreprise.html

${symbol_pound} URL du back-office
${groupId}.backserver.back.url=http://localhost:${tsBackPort}/${artifactIdLower}/

${symbol_pound} Page d'aide
${groupId}.backserver.help.url = http://intra
${symbol_pound} Clé partagée avec le front pour le calcul du sig
${groupId}.backserver.front.key = pass
