#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
${artifactIdUpper}-CONN=${artifactIdUpper}
${artifactIdUpper}-CLASS=org.postgresql.Driver
${artifactIdUpper}-URL=jdbc:postgresql://localhost:5432/${artifactIdLower}
${artifactIdUpper}-USER=${artifactIdLower}
${artifactIdUpper}-PASS=${artifactIdLower}

${symbol_pound} Container utilisé pour l'appel à FILE
${groupId}.backserver.file.containerId=ROOT

${groupId}.backserver.processDefinitionKey=process

${symbol_pound} String jwt = createJWTToken("secret", "${artifactIdUpper}", new String[] { "USER" }, "MAIL", null, null);
${groupId}.backserver.mail.jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJERVJKRkVSIiwiYXVkIjoiTUFJTCIsImlhdCI6IjIwMTktMDgtMTNUMTY6NDM6MDgrMDIwMCIsImp0aSI6ImMyZDVkZmVmLTJlZWEtNDExOS1iY2Y0LWQzMzkzMTg5NTg1YiIsImdvdXYiOnsic2hhcmVkIjp7InJvbGVzIjpbIlVTRVIiXX19fQ.17MjCdP-q0GFzgvtkVB6qe32AX3sN1o_wQfWjl-RCpo

${symbol_pound} String jwt = createJWTToken("secret", "${artifactIdUpper}", new String[] { "USER" }, "FILE", null, null);
${groupId}.backserver.file.jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJERVJKRkVSIiwiYXVkIjoiRklMRSIsImlhdCI6IjIwMTktMDgtMTNUMTY6NDM6MzMrMDIwMCIsImp0aSI6IjVmMTMzZTE0LTU2ZTctNDQ4YS04ZWEwLTE4NjRkMzM2YjVlNiIsImdvdXYiOnsic2hhcmVkIjp7InJvbGVzIjpbIlVTRVIiXX19fQ.WzoQaYvA6N8DJyuoL0pnjEBNyn8DJed5fIhlwlF8eA8

${groupId}.backserver.usagerscache.duration=60000

${artifactIdLower}.override.spring.jpa.properties.hibernate.default_schema=${artifactIdUpper}

${groupId}.jms.port=6261
${groupId}.jms.host=localhost
${groupId}.jms.topic.sender.user=${artifactIdLower}-user
${groupId}.jms.topic.sender.password=${artifactIdLower}-pass
${groupId}.jms.topic.consumer.user=${artifactIdLower}-user
${groupId}.jms.topic.consumer.password=${artifactIdLower}-pass
${groupId}.jms.topic=demandes
${groupId}.jms.dlq=dlq
${groupId}.jms.data.dir=D:${symbol_escape}jmsdata
${groupId}.jms.redelivery.delay=2000
${groupId}.jms.redelivery.multiplier=1
${groupId}.jms.redelivery.maxAttemps=5000
${groupId}.jms.topic.subscription.key=${artifactIdLower}-subscription
${groupId}.elasticsearch.reindex.bulksize=100
${groupId}.elasticsearch.clustername=cluster
${groupId}.elasticsearch.host=localhost
${groupId}.elasticsearch.port=9300
${groupId}.elasticsearch.nodename=${artifactIdLower}-node
${groupId}.search.highlight.pretags=<strong style="color:red">
${groupId}.search.highlight.posttags=</strong>
