#set( $b = $tsFullName.replace("'", "''") )
-- /!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\ ATTENTION REMPLACER L'ADRESSE DU SERVICE PAR UNE ADRESSE DE TEST, SI ENVIRONNEMENT != PROD /!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\
-- Penser également à mettre email_from = email_service afin d'éviter que le secrétariat de la DAN (contact@gouv.mc) ne reçoive des e-mails de delivery failure 
INSERT INTO ${artifactIdUpper}.DEM_DEMARCHES VALUES ('${artifactIdUpper}','${b}','recettedae10@gouv.mc','Direction de l''Environnement','noreply@gouv.mc','No-Reply','contact@gouv.mc','Contact Téléservices Principauté de Monaco','${tsIdentifiantDemande}');

-- Motifs français

insert into ${artifactIdUpper}.DEM_MOTIFS values (default,'${artifactIdUpper}','Des informations complémentaires sont nécessaires.','INFOS_MANQUANTES','EN_ATTENTE_COMPL','fr',null,null);
insert into ${artifactIdUpper}.DEM_MOTIFS values (default,'${artifactIdUpper}','Certaines pièces sont illisibles.','PIECES_ILLISIBLES','EN_ATTENTE_COMPL','fr',null,null);
insert into ${artifactIdUpper}.DEM_MOTIFS values (default,'${artifactIdUpper}','Des informations semblent erronées.','INFOS_ERRONEES','EN_ATTENTE_COMPL','fr',null,null);
insert into ${artifactIdUpper}.DEM_MOTIFS values (default,'${artifactIdUpper}','Autre.','ATTENTE_COMPL_AUTRE','EN_ATTENTE_COMPL','fr',null,null);

insert into ${artifactIdUpper}.DEM_MOTIFS values (default,'${artifactIdUpper}','Demande en double.','DEMANDE_EN_DOUBLE','REFUSEE','fr',null,'Demande en double. Ce véhicule a déjà fait l''objet d''une demande.');
insert into ${artifactIdUpper}.DEM_MOTIFS values (default,'${artifactIdUpper}','Achat effectué avant l''entrée en vigueur de l''Arrêté Ministériel.','ACHAT_AVANT_ARRETE_MINISTERIEL','REFUSEE','fr',null,'Achat effectué avant l''entrée en vigueur de l’Arrêté Ministériel 2018-1182 du 18 décembre 2018. Cet Arrêté Ministériel est non rétroactif.');
insert into ${artifactIdUpper}.DEM_MOTIFS values (default,'${artifactIdUpper}','Achat effectué il y a plus de 6 mois. ','ACHAT_PLUS_6MOIS','REFUSEE','fr',null,'Votre requête ne répond pas aux critères définis par l’Arrêté Ministériel 2018-1182 du 18 décembre 2018 puisqu’elle a été formulée plus de six mois après la facturation du véhicule');
insert into ${artifactIdUpper}.DEM_MOTIFS values (default,'${artifactIdUpper}','Autre.','REFUSEE_AUTRE','REFUSEE','fr',null,'Votre véhicule ne répond pas aux critères d’attribution définis par l’Arrêté Ministériel 2018-1182 du 18 décembre 2018.');

insert into ${artifactIdUpper}.DEM_MOTIFS values (default,'${artifactIdUpper}','Annulation par l''usager','ANNULATION_PAR_USAGER','ANNULEE','fr',null,null);

-- Motifs anglais

insert into ${artifactIdUpper}.DEM_MOTIFS values (default,'${artifactIdUpper}','The following information is missing.','INFOS_MANQUANTES','EN_ATTENTE_COMPL','en',null,null);
insert into ${artifactIdUpper}.DEM_MOTIFS values (default,'${artifactIdUpper}','Some parts are illegible.','PIECES_ILLISIBLES','EN_ATTENTE_COMPL','en',null,null);
insert into ${artifactIdUpper}.DEM_MOTIFS values (default,'${artifactIdUpper}','Some information seems to be incorrect.','INFOS_ERRONEES','EN_ATTENTE_COMPL','en',null,null);
insert into ${artifactIdUpper}.DEM_MOTIFS values (default,'${artifactIdUpper}','Other.','ATTENTE_COMPL_AUTRE','EN_ATTENTE_COMPL','en',null,null);

insert into ${artifactIdUpper}.DEM_MOTIFS values (default,'${artifactIdUpper}','Duplicate request.','DEMANDE_EN_DOUBLE','REFUSEE','en',null,'Duplicate request. A request has already been made with regard to this vehicle.');
insert into ${artifactIdUpper}.DEM_MOTIFS values (default,'${artifactIdUpper}','The purchase was made before the entry into force of the Ministerial Decree.','ACHAT_AVANT_ARRETE_MINISTERIEL','REFUSEE','en',null,'The purchase was made before the entry into force of the Ministerial Decree no.2018-1182 of 18 December 2018. This Ministerial Decree is not retroactive.');
insert into ${artifactIdUpper}.DEM_MOTIFS values (default,'${artifactIdUpper}','Purchased more than 6 months ago. ','ACHAT_PLUS_6MOIS','REFUSEE','en',null,'Your request does not meet the criteria set out by the Ministerial Decree no.2018-1182 of 18 December 2018, as it was made more than six months after the invoice was issued for the vehicle');
insert into ${artifactIdUpper}.DEM_MOTIFS values (default,'${artifactIdUpper}','Other.','REFUSEE_AUTRE','REFUSEE','en',null,'Your vehicle does not meet the granting criteria set out in the Ministerial Decree no.2018-1182 of 18 December 2018.');

insert into ${artifactIdUpper}.DEM_MOTIFS values (default,'${artifactIdUpper}','Cancel by the user','ANNULATION_PAR_USAGER','ANNULEE','en',null,null);

-- Templates français

insert into ${artifactIdUpper}.DEM_TEMPLATES values (default, '${artifactIdUpper}', 'MAIL_CREATION_DEMANDE_USAGER_OBJET', 'Accusé de réception de votre demande ${identifiant}', 'fr');
insert into ${artifactIdUpper}.DEM_TEMPLATES values (default, '${artifactIdUpper}', 'MAIL_CREATION_DEMANDE_USAGER_CORPS', 'Bonjour,<br/><br/>Nous avons bien reçu votre demande d''aide à l''achat d''un véhicule écologique <a href="${urlFront}demande_view.html?id=${pkDemande}">${identifiant}</a>. Nous allons étudier votre demande.<br/><br/>Sincèrement,<br/>Direction de l''Environnement<br/>3, Avenue de Fontvieille<br/>MC 98013 MONACO<br/><br/>(+377) 98 98 83 41<br/>environnement@gouv.mc<br/><br/>Ce message a été envoyé automatiquement. Nous vous remercions de ne pas y répondre.<br/>Si vous n''êtes pas à l''origine de cette demande, veuillez simplement ignorer ce message.', 'fr');
insert into ${artifactIdUpper}.DEM_TEMPLATES values (default, '${artifactIdUpper}', 'MAIL_CREATION_DEMANDE_AGENT_OBJET', 'Nouvelle demande déposée', 'fr');
insert into ${artifactIdUpper}.DEM_TEMPLATES values (default, '${artifactIdUpper}', 'MAIL_CREATION_DEMANDE_AGENT_CORPS', 'Bonjour,<br/><br/>Une nouvelle demande vient d''être déposée. Vous pouvez la consulter <a href="${urlBack}">à cette adresse</a> dans le tableau des demandes en attente.<br/><br/>Notification automatique', 'fr');
insert into ${artifactIdUpper}.DEM_TEMPLATES values (default, '${artifactIdUpper}', 'MAIL_ACTION_REFUSER_OBJET', 'Votre demande ${identifiant}', 'fr');
insert into ${artifactIdUpper}.DEM_TEMPLATES values (default, '${artifactIdUpper}', 'MAIL_ACTION_REFUSER_CORPS', 'Bonjour,<br/><br/>Nous avons le regret de vous informer que votre demande n° ${identifiant} ne peut obtenir une suite favorable.<br/><br/>Vous pouvez consulter votre demande en cliquant sur ce <a href="${urlFront}demande_view.html?id=${pkDemande}">lien</a><br/><br/>Sincèrement,<br/>Direction de l''Environnement<br/>3, Avenue de Fontvieille<br/>MC 98013 MONACO<br/><br/>(+377) 98 98 83 41<br/>environnement@gouv.mc<br/><br/>Ce message a été envoyé automatiquement. Nous vous remercions de ne pas y répondre.<br/>Si vous n''êtes pas à l''origine de cette demande, veuillez simplement ignorer ce message.', 'fr');
--insert into ${artifactIdUpper}.DEM_TEMPLATES values (default, '${artifactIdUpper}', 'MAIL_ACTION_VALIDEE_EN_ATTENTE_PAIEMENT_OBJET', 'Votre demande ${identifiant}', 'fr');
--insert into ${artifactIdUpper}.DEM_TEMPLATES values (default, '${artifactIdUpper}', 'MAIL_ACTION_VALIDEE_EN_ATTENTE_PAIEMENT_CORPS', 'Bonjour,<br/><br/>Nous avons le plaisir de vous informer que votre demande n° ${identifiant} est validée et en attente de paiement.<br/><br/>Vous pouvez consulter votre demande en cliquant sur ce lien <a href="https://teleservice.gouv.mc/subvention-vehicule-ecologique/">https://teleservice.gouv.mc/subvention-vehicule-ecologique/</a><br/><br/>Sincèrement,<br/>Direction de l''Environnement<br/>3, Avenue de Fontvieille<br/>MC 98013 MONACO<br/><br/>(+377) 98 98 83 41<br/>environnement@gouv.mc<br/><br/>Ce message a été envoyé automatiquement. Nous vous remercions de ne pas y répondre.<br/>Si vous n''êtes pas à l''origine de cette demande, veuillez simplement ignorer ce message.', 'fr');
insert into ${artifactIdUpper}.DEM_TEMPLATES values (default, '${artifactIdUpper}', 'MAIL_ACTION_VALIDEE_ET_PAYEE_OBJET', 'Votre demande ${identifiant}', 'fr');
insert into ${artifactIdUpper}.DEM_TEMPLATES values (default, '${artifactIdUpper}', 'MAIL_ACTION_VALIDEE_ET_PAYEE_CORPS', 'Bonjour,<br/><br/>Nous avons le plaisir de vous informer que votre demande n° ${identifiant} est validée et payée.<br/><br/>Vous pouvez consulter votre demande en cliquant sur ce <a href="${urlFront}demande_view.html?id=${pkDemande}">lien</a><br/><br/>Sincèrement,<br/>Direction de l''Environnement<br/>3, Avenue de Fontvieille<br/>MC 98013 MONACO<br/><br/>(+377) 98 98 83 41<br/>environnement@gouv.mc<br/><br/>Ce message a été envoyé automatiquement. Nous vous remercions de ne pas y répondre.<br/>Si vous n''êtes pas à l''origine de cette demande, veuillez simplement ignorer ce message.', 'fr');
insert into ${artifactIdUpper}.DEM_TEMPLATES values (default, '${artifactIdUpper}', 'MAIL_ACTION_DEMANDEIC_OBJET', 'Compléter votre demande ${identifiant}', 'fr');
insert into ${artifactIdUpper}.DEM_TEMPLATES values (default, '${artifactIdUpper}', 'MAIL_ACTION_DEMANDEIC_CORPS', 'Bonjour,<br/><br/>Afin de procéder à l''étude de votre demande ${identifiant}, nous avons besoin de compléments d''informations.<br/><br/>Pour compléter votre demande par la démarche en ligne, veuillez cliquer sur ce <a href="${urlFront}demande_view.html?id=${pkDemande}">lien</a><br/><br/>Sincèrement,<br/>Direction de l''Environnement<br/>3, Avenue de Fontvieille<br/>MC 98013 MONACO<br/><br/>(+377) 98 98 83 41<br/>environnement@gouv.mc<br/><br/>Ce message a été envoyé automatiquement. Nous vous remercions de ne pas y répondre.<br/>Si vous n''êtes pas à l''origine de cette demande, veuillez simplement ignorer ce message.', 'fr');

insert into ${artifactIdUpper}.DEM_TEMPLATES values (default, '${artifactIdUpper}', 'MAIL_CONFIRMATION_ACTION_ANNULER_OBJET', 'Votre demande ${identifiant}', 'fr');
insert into ${artifactIdUpper}.DEM_TEMPLATES values (default, '${artifactIdUpper}', 'MAIL_CONFIRMATION_ACTION_ANNULER_CORPS', 'Bonjour,<br/><br/>Nous avons bien pris en compte l''annulation de votre demande n° ${identifiant}.<br/><br/>Vous pouvez consulter votre demande en cliquant sur ce <a href="${urlFront}demande_view.html?id=${pkDemande}">lien</a><br/><br/>Sincèrement,<br/>Direction de l''Environnement<br/>3, Avenue de Fontvieille<br/>MC 98013 MONACO<br/><br/>(+377) 98 98 83 41<br/>environnement@gouv.mc<br/><br/>Ce message a été envoyé automatiquement. Nous vous remercions de ne pas y répondre.<br/>Si vous n''êtes pas à l''origine de cette demande, veuillez simplement ignorer ce message.', 'fr');

insert into ${artifactIdUpper}.DEM_TEMPLATES values (default, '${artifactIdUpper}', 'MAIL_NOTIFICATION_REPONSE_IC_PAR_USAGER_OBJET', 'La demande ${identifiant} a été complétée', 'fr');
insert into ${artifactIdUpper}.DEM_TEMPLATES values (default, '${artifactIdUpper}', 'MAIL_NOTIFICATION_REPONSE_IC_PAR_USAGER_CORPS', 'Bonjour,<br/><br/>La demande ${identifiant} a été complétée. Vous pouvez la consulter <a href="${urlBack}">à cette adresse</a> dans le tableau des demandes en cours de traitement.<br/><br/>Notification automatique', 'fr');
insert into ${artifactIdUpper}.DEM_TEMPLATES values (default, '${artifactIdUpper}', 'MAIL_NOTIFICATION_REPONSE_IC_PAR_AGENT_OBJET', 'La demande ${identifiant} a été complétée', 'fr');
insert into ${artifactIdUpper}.DEM_TEMPLATES values (default, '${artifactIdUpper}', 'MAIL_NOTIFICATION_REPONSE_IC_PAR_AGENT_CORPS', 'Bonjour,<br/><br/>La demande ${identifiant} a été complétée par ${utilisateur}. Vous pouvez la consulter <a href="${urlBack}">à cette adresse</a> dans le tableau des demandes en cours de traitement.<br/><br/>Notification automatique', 'fr');
--insert into ${artifactIdUpper}.DEM_TEMPLATES values (default, '${artifactIdUpper}', 'MAIL_NOTIFICATION_ATTENTE_VALIDATION_COMPTABLE_OBJET', 'La demande ${identifiant} est en attente de validation comptable', 'fr');
--insert into ${artifactIdUpper}.DEM_TEMPLATES values (default, '${artifactIdUpper}', 'MAIL_NOTIFICATION_ATTENTE_VALIDATION_COMPTABLE_CORPS', 'Bonjour,<br/><br/>La demande ${identifiant} vient d''être traitée et nécessite votre validation comptable. Vous pouvez la consulter <a href="${urlBack}">à cette adresse</a> dans le tableau des demandes en attente.<br/><br/>Notification automatique', 'fr');


insert into ${artifactIdUpper}.DEM_TEMPLATES values (default, '${artifactIdUpper}', 'MAIL_DESINSCRIPTION_USAGER_OBJET', 'Désinscription de l''usager ${usager}', 'fr');
insert into ${artifactIdUpper}.DEM_TEMPLATES values (default, '${artifactIdUpper}', 'MAIL_DESINSCRIPTION_USAGER_CORPS', 'Bonjour,<br/><br/>L''usager ${usager} vient de se désinscrire de la démarche.<br/><br/>Par conséquent, les demandes suivantes sont passées à l''état "Annulée" :<br/>${demandes}<br/><br/>Notification automatique', 'fr');

insert into ${artifactIdUpper}.DEM_TEMPLATES values (default, '${artifactIdUpper}', 'MAIL_DESINSCRIPTION_USAGER_POUR_USAGER_OBJET', 'Désinscription du téléservice "Demander une aide à l''achat d''un véhicule écologique"', 'fr');
insert into ${artifactIdUpper}.DEM_TEMPLATES values (default, '${artifactIdUpper}', 'MAIL_DESINSCRIPTION_USAGER_POUR_USAGER_CORPS', 'Bonjour,<br/><br/>Nous vous confirmons votre désinscription du téléservice "Demander une aide à l''achat d''un véhicule écologique" sur votre compte Téléservices Principauté de Monaco pour l''identifiant ${identifiant_usager} (voir les <a href="https://teleservice.gouv.mc/subvention-vehicule-ecologique/legalterms.html">Conditions Générales d''Utilisation</a>).<br/><br/>Sincèrement,<br/>Direction de l''Environnement<br/>3, Avenue de Fontvieille<br/>MC 98013 MONACO<br/><br/>(+377) 98 98 83 41<br/>environnement@gouv.mc<br/><br/>Ce message a été envoyé automatiquement. Nous vous remercions de ne pas y répondre.<br/>Si vous n''êtes pas à l''origine de cette demande, veuillez simplement ignorer ce message.', 'fr');

insert into ${artifactIdUpper}.DEM_TEMPLATES values (default, '${artifactIdUpper}', 'MAIL_NOTIFICATION_ANNULATION_DEMANDE_PAR_USAGER_OBJET', 'Annulation de la demande ${identifiant} par l''usager', 'fr');
insert into ${artifactIdUpper}.DEM_TEMPLATES values (default, '${artifactIdUpper}', 'MAIL_NOTIFICATION_ANNULATION_DEMANDE_PAR_USAGER_CORPS', 'Bonjour,<br/><br/>L''usager ${usager} vient d''annuler sa demande ${identifiant}.<br/><br/>Vous pouvez la consulter <a href="${urlBack}/demandes/${pkDemande}">à cette adresse</a>.<br/><br/>Notification automatique', 'fr');

-- Templates anglais

insert into ${artifactIdUpper}.DEM_TEMPLATES values (default, '${artifactIdUpper}', 'MAIL_CREATION_DEMANDE_USAGER_OBJET', 'Acknowledgement of receipt - your request ${identifiant}', 'en');
insert into ${artifactIdUpper}.DEM_TEMPLATES values (default, '${artifactIdUpper}', 'MAIL_CREATION_DEMANDE_USAGER_CORPS', 'Hello,<br/><br/>We confirm that we have received your request for a subsidy for buying a clean energy vehicle <a href="${urlFront}demande_view.html?id=${pkDemande}">${identifiant}</a>. We will consider your request.<br/><br/>Yours sincerely,<br/>Direction de l''Environnement<br/>3, Avenue de Fontvieille<br/>MC 98013 MONACO<br/><br/>(+377) 98 98 83 41<br/>environnement@gouv.mc<br/><br/>This message has been sent automatically. Please do not reply to it.<br/> If you did not send this request, please simply ignore this message.', 'en');

insert into ${artifactIdUpper}.DEM_TEMPLATES values (default, '${artifactIdUpper}', 'MAIL_ACTION_DEMANDEIC_OBJET', 'Complete your request ${identifiant}', 'en');
insert into ${artifactIdUpper}.DEM_TEMPLATES values (default, '${artifactIdUpper}', 'MAIL_ACTION_DEMANDEIC_CORPS', 'Hello,<br/><br/>In order to study your request ${identifiant}, we require some additional information. <br/><br/>To complete your request using the online procedure, please click on this <a href="${urlFront}demande_view.html?id=${pkDemande}">link</a><br/><br/>Yours sincerely,<br/>Direction de l''Environnement<br/>3, Avenue de Fontvieille<br/>MC 98013 MONACO<br/><br/>(+377) 98 98 83 41<br/>environnement@gouv.mc<br/><br/>This message has been sent automatically. Please do not reply to it.<br/> If you did not send this request, please simply ignore this message.', 'en');

--insert into ${artifactIdUpper}.DEM_TEMPLATES values (default, '${artifactIdUpper}', 'MAIL_ACTION_VALIDEE_EN_ATTENTE_PAIEMENT_OBJET', 'Votre demande ${identifiant}', 'en');
--insert into ${artifactIdUpper}.DEM_TEMPLATES values (default, '${artifactIdUpper}', 'MAIL_ACTION_VALIDEE_EN_ATTENTE_PAIEMENT_CORPS', 'Bonjour,<br/><br/>Nous avons le plaisir de vous informer que votre demande n° ${identifiant} est validée et en attente de paiement.<br/><br/>Vous pouvez consulter votre demande en cliquant sur ce lien <a href="https://teleservice.gouv.mc/subvention-vehicule-ecologique/">https://teleservice.gouv.mc/subvention-vehicule-ecologique/</a><br/><br/>Sincèrement,<br/>Direction de l''Environnement<br/>3, Avenue de Fontvieille<br/>MC 98013 MONACO<br/><br/>(+377) 98 98 83 41<br/>environnement@gouv.mc<br/><br/>This message has been sent automatically. Please do not reply to it.<br/> If you did not send this request, please simply ignore this message.', 'en');

insert into ${artifactIdUpper}.DEM_TEMPLATES values (default, '${artifactIdUpper}', 'MAIL_ACTION_REFUSER_OBJET', 'Your request ${identifiant}', 'en');
insert into ${artifactIdUpper}.DEM_TEMPLATES values (default, '${artifactIdUpper}', 'MAIL_ACTION_REFUSER_CORPS', 'Hello,<br/><br/>We regret to inform you that your request No. ${identifiant} cannot be granted.<br/><br/>You can consult your request by clicking on this <a href="${urlFront}demande_view.html?id=${pkDemande}">link</a><br/><br/>Yours sincerely,<br/>Direction de l''Environnement<br/>3, Avenue de Fontvieille<br/>MC 98013 MONACO<br/><br/>(+377) 98 98 83 41<br/>environnement@gouv.mc<br/><br/>This message has been sent automatically. Please do not reply to it.<br/> If you did not send this request, please simply ignore this message.', 'en');

insert into ${artifactIdUpper}.DEM_TEMPLATES values (default, '${artifactIdUpper}', 'MAIL_ACTION_VALIDEE_ET_PAYEE_OBJET', 'Your request ${identifiant}', 'en');
insert into ${artifactIdUpper}.DEM_TEMPLATES values (default, '${artifactIdUpper}', 'MAIL_ACTION_VALIDEE_ET_PAYEE_CORPS', 'Hello,<br/><br/>We are pleased to inform you that your request No. ${identifiant} has been validated and paid.<br/><br/>You can consult your request by clicking on this <a href="${urlFront}demande_view.html?id=${pkDemande}">link</a><br/><br/>Yours sincerely,<br/>Direction de l''Environnement<br/>3, Avenue de Fontvieille<br/>MC 98013 MONACO<br/><br/>(+377) 98 98 83 41<br/>environnement@gouv.mc<br/><br/>This message has been sent automatically. Please do not reply to it.<br/> If you did not send this request, please simply ignore this message.', 'en');

insert into ${artifactIdUpper}.DEM_TEMPLATES values (default, '${artifactIdUpper}', 'MAIL_CONFIRMATION_ACTION_ANNULER_OBJET', 'Cancellation of your request ${identifiant}', 'en');
insert into ${artifactIdUpper}.DEM_TEMPLATES values (default, '${artifactIdUpper}', 'MAIL_CONFIRMATION_ACTION_ANNULER_CORPS', 'Hello,<br/><br/>We have taken the cancellation of your request No. ${identifiant} into account.<br/><br/>You can consult your request by clicking on this <a href="${urlFront}demande_view.html?id=${pkDemande}">link</a><br/><br/>Yours sincerely,<br/>Direction de l''Environnement<br/>3, Avenue de Fontvieille<br/>MC 98013 MONACO<br/><br/>(+377) 98 98 83 41<br/>environnement@gouv.mc<br/><br/>This message has been sent automatically. Please do not reply to it.<br/> If you did not send this request, please simply ignore this message.', 'en');

insert into ${artifactIdUpper}.DEM_TEMPLATES values (default, '${artifactIdUpper}', 'MAIL_DESINSCRIPTION_USAGER_POUR_USAGER_OBJET', 'Unsubscription from the online service', 'en');
insert into ${artifactIdUpper}.DEM_TEMPLATES values (default, '${artifactIdUpper}', 'MAIL_DESINSCRIPTION_USAGER_POUR_USAGER_CORPS', 'Hello,<br/><br/>We confirm that you have unsubscribed from the online service “Obtain a subsidy for buying a clean energy vehicle” on your account with the Principality of Monaco''s online services for the identifier ${identifiant_usager} (see the General Terms of Use, which are available on <a href="https://teleservice.gouv.mc/subvention-vehicule-ecologique/legalterms.html">this</a> page).<br/><br/>Yours sincerely,<br/>Direction de l''Environnement<br/>3, Avenue de Fontvieille<br/>MC 98013 MONACO<br/><br/>(+377) 98 98 83 41<br/>environnement@gouv.mc<br/><br/>This message has been sent automatically. Please do not reply to it.<br/> If you did not send this request, please simply ignore this message.', 'en');

