
--engine
GRANT SELECT, INSERT, DELETE, UPDATE ON TABLE "HAB"."ACT_GE_PROPERTY" TO USER hab;
GRANT SELECT, INSERT, DELETE, UPDATE ON TABLE "HAB"."ACT_GE_BYTEARRAY" TO USER hab;
GRANT SELECT, INSERT, DELETE, UPDATE ON TABLE "HAB"."ACT_RE_DEPLOYMENT" TO USER hab;
GRANT SELECT, INSERT, DELETE, UPDATE ON TABLE "HAB"."ACT_RE_MODEL" TO USER hab;
GRANT SELECT, INSERT, DELETE, UPDATE ON TABLE "HAB"."ACT_RU_EXECUTION" TO USER hab;
GRANT SELECT, INSERT, DELETE, UPDATE ON TABLE "HAB"."ACT_RU_JOB" TO USER hab;
GRANT SELECT, INSERT, DELETE, UPDATE ON TABLE "HAB"."ACT_RE_PROCDEF" TO USER hab;
GRANT SELECT, INSERT, DELETE, UPDATE ON TABLE "HAB"."ACT_RU_TASK" TO USER hab;
GRANT SELECT, INSERT, DELETE, UPDATE ON TABLE "HAB"."ACT_RU_IDENTITYLINK" TO USER hab;
GRANT SELECT, INSERT, DELETE, UPDATE ON TABLE "HAB"."ACT_RU_VARIABLE" TO USER hab;
GRANT SELECT, INSERT, DELETE, UPDATE ON TABLE "HAB"."ACT_RU_EVENT_SUBSCR" TO USER hab;
GRANT SELECT, INSERT, DELETE, UPDATE ON TABLE "HAB"."ACT_EVT_LOG" TO USER hab;
GRANT SELECT, INSERT, DELETE, UPDATE ON TABLE "HAB"."ACT_PROCDEF_INFO" TO USER hab;

--history

GRANT SELECT, INSERT, DELETE, UPDATE ON TABLE "HAB"."ACT_HI_PROCINST" TO USER hab;
GRANT SELECT, INSERT, DELETE, UPDATE ON TABLE "HAB"."ACT_HI_ACTINST" TO USER hab;
GRANT SELECT, INSERT, DELETE, UPDATE ON TABLE "HAB"."ACT_HI_TASKINST" TO USER hab;
GRANT SELECT, INSERT, DELETE, UPDATE ON TABLE "HAB"."ACT_HI_DETAIL" TO USER hab;
GRANT SELECT, INSERT, DELETE, UPDATE ON TABLE "HAB"."ACT_HI_COMMENT" TO USER hab;
GRANT SELECT, INSERT, DELETE, UPDATE ON TABLE "HAB"."ACT_HI_ATTACHMENT" TO USER hab;
GRANT SELECT, INSERT, DELETE, UPDATE ON TABLE "HAB"."ACT_HI_IDENTITYLINK" TO USER hab;
GRANT SELECT, INSERT, DELETE, UPDATE ON TABLE "HAB"."ACT_HI_VARINST" TO USER hab;


--identity
GRANT SELECT, INSERT, DELETE, UPDATE ON TABLE "HAB"."ACT_ID_GROUP" TO USER hab;
GRANT SELECT, INSERT, DELETE, UPDATE ON TABLE "HAB"."ACT_ID_MEMBERSHIP" TO USER hab;
GRANT SELECT, INSERT, DELETE, UPDATE ON TABLE "HAB"."ACT_ID_USER" TO USER hab;
GRANT SELECT, INSERT, DELETE, UPDATE ON TABLE "HAB"."ACT_ID_INFO" TO USER hab;






