#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
${symbol_pound}Maven properties
maven.name=@project.name@
maven.version=@project.version@
${symbol_pound}maven.build.date aura ce format : 2017-04-28T13:08:51Z
maven.build.date=@buildDate@

${symbol_pound}spring.jpa.show-sql = true
${symbol_pound} Pour afficher les valeurs des paramÃ¨tres des requÃ¨tes SQL
${symbol_pound}logging.level.org.hibernate.SQL=DEBUG
${symbol_pound}logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

${symbol_pound} Pour afficher les logs debug de Spring (autowiring troubleshooting etc.)
${symbol_pound} logging.level.org.springframework = DEBUG

server.port=${tsBackPort}
server.servlet.context-path=/${artifactIdLower}

${symbol_pound}https://github.com/spring-projects/spring-boot/issues/5638
security.filter-dispatcher-types=ASYNC, FORWARD, INCLUDE, REQUEST, ERROR

${symbol_pound} Pour empêcher que Velocity fasse sa config Java et s'interface dans la gestion des pages
${symbol_pound} Sinon on obtient: org.apache.velocity : ResourceManager : unable to find resource 'blablabla.vm' in any resource loader.
spring.velocity.enabled=false

${symbol_pound} Utilisation de ehCache
spring.cache.jcache.config=classpath:ehcache.xmlsta

${symbol_pound} Pour l'internationalisation
spring.messages.basename=messages/messages
spring.messages.cache-seconds=-1
spring.messages.encoding=UTF-8

spring.profiles.active=gouv

spring.datasource.initialize=false
spring.datasource.platform=postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.thymeleaf.cache=false

display.name=${artifactIdUpper}
db.name=${artifactIdUpper}
application.name=${artifactIdLower}

spring.http.multipart.maxFileSize: 5MB
spring.http.multipart.maxRequestSize: 5MB

${symbol_pound} Sert à pouvoir récupérer le BPMN depuis le JAR ${artifactIdLower}-service (par défaut c'est classpath:, pas classpath*:)
spring.activiti.processDefinitionLocationPrefix=classpath*:/processes/

${symbol_pound} https://stackoverflow.com/questions/31557076/spring-hibernate-query-plan-cache-memory-usage
spring.jpa.properties.hibernate.query.plan_cache_max_size=512

mc.gouv.${artifactIdLower}.indexing.enabled=true
