#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}
${symbol_pound} docx setup

${symbol_pound} Page size: use a value from org.docx4j.model.structure.PageSizePaper enum
${symbol_pound} eg A4, LETTER
docx4j.PageSize=A4
${symbol_pound} Page size: use a value from org.docx4j.model.structure.MarginsWellKnown enum
docx4j.PageMargins=NORMAL
docx4j.PageOrientationLandscape=false

${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}
${symbol_pound} docx4j general config

${symbol_pound} PDF output; ability to specify font substitutions.  See src/samples/_resources
${symbol_pound} Avoid using both this and fontMapper.getFontMappings() for the same fonts!
${symbol_pound} since docx4j 3.2.0
${symbol_pound}docx4j.fonts.fop.util.FopConfigUtil.substitutions=fop-substitutions.xml

${symbol_pound} This override available since docx4j 3.2.0
${symbol_pound} Defaults to org/docx4j/fonts/microsoft/MicrosoftFonts.xml
${symbol_pound} which is contained in the docx4j jar
${symbol_pound} If you need to override it in order to provide different file names for
${symbol_pound} one or more fonts, start by extracting and editing a copy of the existing file
docx4j.fonts.microsoft.MicrosoftFonts=org/docx4j/fonts/microsoft/MicrosoftFonts.xml

${symbol_pound} Whether to System.gc() before attempting to delete tmp image files.
${symbol_pound} Introduced in docx4j 3.  For consistency with previous versions, default is true 
docx4j.openpackaging.parts.WordprocessingML.BinaryPartAbstractImage.TempFiles.ForceGC=false

${symbol_pound} Unmarshalling via a DOM document (for XPath binder) can be 5x slower than
${symbol_pound} unmarshalling an input stream directly!
${symbol_pound} This setting lets you avoid eager unmarshalling via DOM, unless you know you'll be using XPath
${symbol_pound} (XPath should still work either way, but creating the binder is deferred where eager=false)
${symbol_pound} since docx4j 3.3.0
docx4j.openpackaging.parts.JaxbXmlPartXPathAware.binder.eager.MainDocumentPart=false
docx4j.openpackaging.parts.JaxbXmlPartXPathAware.binder.eager.OtherParts=false

${symbol_pound} If you haven't configured log4j yourself
${symbol_pound} docx4j will autoconfigure it. Set this to true to disable that
docx4j.Log4j.Configurator.disabled=true
